### ISSUE TITLE
Something about Traveller's Wings crashes MadPack server

### ISSUE THREAD

**Issue by japherwocky** [SlimeKnights/TinkersConstruct#1328]
Running madpack beta 10, minecraft 1.7.10, looks like TConstruct-1.7.10-1.7.1c.jar

equipped the Traveller's Wings (not for the first time) and got this traceback on the server.  same traceback when I try to login:

```
Caused by: java.lang.NullPointerException
        at tconstruct.modifiers.armor.ActiveTinkerArmor.onArmorTick(ActiveTinkerArmor.java:18) ~[ActiveTinkerArmor.class
:?]
        at tconstruct.library.armor.ArmorCore.onArmorTick(ArmorCore.java:96) ~[ArmorCore.class:?]
        at tconstruct.armor.items.TravelGear.onArmorTick(TravelGear.java:29) ~[TravelGear.class:?]
        at tconstruct.armor.items.TravelWings.onArmorTick(TravelWings.java:40) ~[TravelWings.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319) ~[yx.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538) ~[yz.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
```

**Comment by Adaptivity** [comment]
"1.7.1c" -> update to to 1.8.2a and try again.

**Comment by japherwocky** [comment]
if you guys aren't going to look at tracebacks from older versions, that's understandable, but maybe you could post that on the README or something so that we don't waste our time reporting bugs?

**Comment by bonii-xx** [comment]
1. It says on the frontpage/readme.md "Any modpack which uses Tinkers' Construct takes full responsibility for user support queries."
2. It's standard to check if an issue has been fixed in the latest version before reporting issues
3. It seems the check to prevent that crash is indeed still missing
4. However that crash can never happen with normal gear, something messed with the NBT of the item.

**Comment by japherwocky** [comment]
In the same comment you say that you can see where the crash is coming from, and you can see that it is indeed still an issue, but you're *not* going to do anything about it because I reported it directly to you and not to @kehaandk or @jbams01

**Comment by bonii-xx** [comment]
I never said I wouldn't do anything about it o_O
