### ISSUE TITLE
Er...I think it crashed

### ISSUE THREAD

**Issue by wqfc09** [SlimeKnights/TinkersConstruct#1347]
When I use in Windows 8.1(Jre 8u25),it's nothing wrong
But...When I use in Windows XP...It crash
The crash report:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 15-1-16  P.M. 9:37
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at tconstruct.client.TProxyClient.readManuals(TProxyClient.java:50)
	at tconstruct.client.TProxyClient.initialize(TProxyClient.java:32)
	at tconstruct.TConstruct.postInit(TConstruct.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.client.TProxyClient.readManuals(TProxyClient.java:50)
	at tconstruct.client.TProxyClient.initialize(TProxyClient.java:32)
	at tconstruct.TConstruct.postInit(TConstruct.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 327382848 bytes (312 MB) / 664117248 bytes (633 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 1 total; -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1264 Minecraft Forge 10.13.2.1264 42 mods loaded, 42 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1264} [Forge Mod Loader] (forge-1.7.10-10.13.2.1264.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1264} [Minecraft Forge] (forge-1.7.10-10.13.2.1264.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BetterFonts{1.1.3} [BetterFonts] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2-core{rv2-beta-7} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.3.77} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.77-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AppleCore{1.0.0} [AppleCore] (%5B1.7.10%5DDep-AppleCore-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	SpiceOfLife{1.2.2} [The Spice of Life] (%5B1.7.10%5DCore-SpiceOfLife-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RWG{Alpha 1.3.01} [Realistic World Gen Alpha] (%5B1.7.10%5DSub-RWG-alpha-1.3.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2{rv2-beta-7} [Applied Energistics 2] (appliedenergistics2-rv2-beta-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BambooMod{Minecraft1.7.10 var2.6.8.2} [BambooMod] (Bamboo-1.7.10-2.6.8.2 %5Bsf汉化%5D.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1036-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Thaumcraft{4.2.3.2} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Botania{r1.3-149} [Botania] (Botania r1.3-149.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CarpentersBlocks{3.3.3} [Carpenter's Blocks] (Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{2.1.3} [Chisel] (Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	extracells{2.2.25} [ExtraCells] (ExtraCells-1.7.10-2.2.25b45.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FastCraft{1.9} [FastCraft] (fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.43.730} [Iron Chest] (ironchest-1.7.10-6.0.43.730-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a_2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.6a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TiCTooltips{1.1.11b} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	ttCore{MC1.7.10-0.1.0-48} [ttCore] (ttCore-MC1.7.10-0.1.0-48.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IguanaTweaksTConstruct{1.7.10-2.0.7} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	AE2 Version: beta rv2-beta-7 for Forge 10.13.2.1230
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1264
	LWJGL: 2.9.1
	OpenGL: ASUS EAH6450 Series GL version 4.1.10664 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.7.10.zip]
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

it shows that TConstruct errored. but i am not sure whether it make minecraft crash or not.If not,Could you tell me what cause it?
I am a Chinese,If have some mistakes in the grammar,Please dont mind it.
Thanks for you help

**Comment by bonii-xx** [comment]
It looks like you don't have a language set. Is that in a dev environment?

**Comment by wqfc09** [comment]
Got it.I think that the launcher make the language set missed
I will use the minecraft launcher and test again
thanks for your answer

**Comment by bonii-xx** [comment]
It works now?

**Comment by SgtPunishment** [comment]
I don't want to bump this, but turns out I'm having the same issue (And it is in a dev environment, I'm using Java 8)
