### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by linkinkov** [SlimeKnights/TinkersConstruct#1372]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 27.01.15 14:46
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tconstruct.tools.blocks.EquipBlock.func_149720_d(EquipBlock.java:210)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4232)
	at tconstruct.tools.model.BattlesignRender.renderWorldBlock(BattlesignRender.java:22)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.tools.blocks.EquipBlock.func_149720_d(EquipBlock.java:210)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4232)
	at tconstruct.tools.model.BattlesignRender.renderWorldBlock(BattlesignRender.java:22)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['linkinkov'/587, l='MpServer', x=159,50, y=65,62, z=398,50]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,244), Chunk: (at 8,4,4 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3364002 game time, 3516379 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['linkinkov'/587, l='MpServer', x=159,50, y=65,62, z=398,50]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 320132736 bytes (305 MB) / 624951296 bytes (596 MB) up to 1398276096 bytes (1333 MB)
	JVM Flags: 1 total; -Xmx1500M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 24 mods loaded, 24 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest{6.0.41.729} [Iron Chest] ([5]ironchest-1.7.10-6.0.41.729.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	voxelmap{1.7.10} [VoxelMap No Radar] ([8]voxelmapNoRadar-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.3.2} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Botania{r1.3-153} [Botania] (Botaniar1.3-153.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] (DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	eternisles{Alpha 1.5} [Eternal Isles] (eternisles-1.7.10-b2-oleg599.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HerobrineFamPack{1.7.10} [HerobrineFamPack] (FamiliarsHerobrineFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MoreFurnaces{1.3.9} [More Furnaces] (MoreFurnaces-1.3.9-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	zzzzzcustomconfigs{1.4.1} [ZZZZZ Custom Configs] ([4]CustomConfigs-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 740M/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by bonii-xx** [comment]
What did you do to get it, place down a frying pan without NBT...?

**Comment by linkinkov** [comment]
i take item from NEI without NEI on server

**Comment by linkinkov** [comment]
Now i cant remove this block, without destroy map

**Comment by linkinkov** [comment]
Because client crash everytimes

**Comment by TherminatorX** [comment]
Use a word editing tool like MCEdit to remove the offending tile entity.

**Comment by linkinkov** [comment]
I do it, thank you

**Comment by bonii-xx** [comment]
Can you give me some specifics on which item it was? Frying pan? Battlesign? What materials? Did it look normal or like a rainbow square?

**Comment by laz2727** [comment]
Nei'd rp. So yes, just without nbt.
