### ISSUE TITLE
Crash when try to craft drying rack or read book Volume 1

### ISSUE THREAD

**Issue by Tankistodor** [SlimeKnights/TinkersConstruct#1389]
If i disable Tinker`s Armory in config file clents is crashed:

- on MacOS when try to craft drying rack;
- in Windows - this item not visible on NEI or creative mode, but when try to read Tinkers book client crashed on drying rack page.

[net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 06.02.15 20:53
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.ItemStack.func_94608_d(ItemStack.java:123)
	at mantle.client.RenderItemCopy.renderItemIntoGUI(RenderItemCopy.java:367)
	at mantle.client.RenderItemCopy.renderItemAndEffectIntoGUI(RenderItemCopy.java:483)
	at mantle.client.pages.CraftingPage.drawCraftingPage(CraftingPage.java:71)
	at mantle.client.pages.CraftingPage.renderContentLayer(CraftingPage.java:44)
	at mantle.client.gui.GuiManual.func_73863_a(GuiManual.java:186)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bonii-xx** [comment]
@progwml6 shouldn't it render an Iron pickaxe or something like that if the item is missing? I thought we changed something there.

**Comment by Adaptivity** [comment]
Valid one. Just checked.
