### ISSUE TITLE
Longbow Charging Crash (not sure if bug, but it probabaly is)

### ISSUE THREAD

**Issue by FireTheInfernape** [SlimeKnights/TinkersConstruct#1430]
So this bug has recently happend to me, and a couple of friends have the same crash. When i try to charge my longbow, it crashes most of the time. Any idea's/help?

Here is the crash report:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 26-2-15 16:49
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tconstruct.client.FlexibleToolRenderer.getIcons(FlexibleToolRenderer.java:266)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:60)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.doRender(ProjectileBaseRenderer.java:57)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:21)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:6)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.func_76986_a(ProjectileBaseRenderer.java:20)
	at tconstruct.weaponry.client.item.BowRenderer.specialAnimation(BowRenderer.java:78)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:232)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:486)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at morph.common.core.EventHandler.onRenderHand(EventHandler.java:238)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_115_EventHandler_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.client.FlexibleToolRenderer.getIcons(FlexibleToolRenderer.java:266)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:60)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.doRender(ProjectileBaseRenderer.java:57)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:21)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:6)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.func_76986_a(ProjectileBaseRenderer.java:20)
	at tconstruct.weaponry.client.item.BowRenderer.specialAnimation(BowRenderer.java:78)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:232)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:486)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at morph.common.core.EventHandler.onRenderHand(EventHandler.java:238)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_115_EventHandler_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)

**Comment by FireTheInfernape** [comment]
EDIT: It also happens at night, and here is a full report of it:
---- Minecraft Crash Report ----
// You're mean.

Time: 26-2-15 17:30
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tconstruct.client.FlexibleToolRenderer.getIcons(FlexibleToolRenderer.java:266)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:60)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.doRender(ProjectileBaseRenderer.java:57)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:21)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:6)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.func_76986_a(ProjectileBaseRenderer.java:20)
	at tconstruct.weaponry.client.item.BowRenderer.specialAnimation(BowRenderer.java:78)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:232)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:486)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.client.FlexibleToolRenderer.getIcons(FlexibleToolRenderer.java:266)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:60)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.doRender(ProjectileBaseRenderer.java:57)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:21)
	at tconstruct.weaponry.client.entity.ArrowEntityRenderer.doRender(ArrowEntityRenderer.java:6)
	at tconstruct.weaponry.client.entity.ProjectileBaseRenderer.func_76986_a(ProjectileBaseRenderer.java:20)
	at tconstruct.weaponry.client.item.BowRenderer.specialAnimation(BowRenderer.java:78)
	at tconstruct.client.FlexibleToolRenderer.renderItem(FlexibleToolRenderer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:232)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:486)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['ddzo1k'/321, l='MpServer', x=-115,30, y=82,62, z=214,02]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (196,64,256), Chunk: (at 4,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 326701 game time, 328811 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntitySheep['Sheep'/519, l='MpServer', x=-188,16, y=74,00, z=288,13], GCEntityClientPlayerMP['ddzo1k'/321, l='MpServer', x=-115,30, y=82,62, z=214,02], EntityItem['item.item.seeds'/322, l='MpServer', x=-86,06, y=69,13, z=210,88], EntityItem['item.item.seeds'/323, l='MpServer', x=-85,13, y=69,13, z=210,75], EntityCreeper['Creeper'/373, l='MpServer', x=-74,50, y=13,00, z=214,50], EntityBat['Bat'/577, l='MpServer', x=-85,25, y=33,90, z=284,53], EntityChicken['Chicken'/372, l='MpServer', x=-99,75, y=67,00, z=216,44], EntityBat['Bat'/375, l='MpServer', x=-106,61, y=19,30, z=262,49], EntityBat['Bat'/579, l='MpServer', x=-67,08, y=40,85, z=274,45], EntitySkeleton['Skeleton'/374, l='MpServer', x=-98,34, y=16,00, z=235,59], EntityBat['Bat'/371, l='MpServer', x=-100,51, y=22,05, z=256,88], EntityChicken['Chicken'/381, l='MpServer', x=-49,53, y=68,00, z=222,44], EntityCreeper['Creeper'/380, l='MpServer', x=-126,75, y=71,00, z=211,84], EntitySkeleton['Skeleton'/383, l='MpServer', x=-94,41, y=25,00, z=245,06], EntitySpider['Spider'/382, l='MpServer', x=-68,50, y=68,00, z=200,88], EntityCreeper['Creeper'/377, l='MpServer', x=-72,34, y=68,00, z=244,09], EntityChicken['Chicken'/376, l='MpServer', x=-79,47, y=68,00, z=192,59], BlueSlime['Blue Slime'/379, l='MpServer', x=-119,22, y=78,00, z=216,22], EntityArrow['arrow'/378, l='MpServer', x=-67,25, y=67,00, z=232,78], EntityZombie['Zombie'/410, l='MpServer', x=-109,72, y=60,00, z=183,38], EntitySheep['Sheep'/411, l='MpServer', x=-97,19, y=69,00, z=159,81], EntityHat['unknown'/1223, l='MpServer', x=-100,94, y=62,00, z=191,50], EntityZombie['Zombie'/408, l='MpServer', x=-141,41, y=70,00, z=227,00], EntityHat['unknown'/1222, l='MpServer', x=-98,50, y=22,00, z=248,00], EntityBat['Bat'/409, l='MpServer', x=-104,59, y=21,10, z=171,06], EntitySkeleton['Skeleton'/414, l='MpServer', x=-41,59, y=67,00, z=238,16], EntityZombie['Zombie'/415, l='MpServer', x=-72,75, y=52,00, z=259,78], EntityChicken['Chicken'/412, l='MpServer', x=-68,44, y=62,48, z=170,56], EntityHat['unknown'/1229, l='MpServer', x=-148,59, y=65,00, z=271,34], EntityCreeper['Creeper'/402, l='MpServer', x=-93,75, y=30,00, z=257,13], EntityBat['Bat'/403, l='MpServer', x=-113,29, y=13,22, z=253,97], EntityHat['unknown'/1230, l='MpServer', x=-82,84, y=70,00, z=290,44], EntitySkeleton['Skeleton'/401, l='MpServer', x=-46,66, y=68,00, z=221,16], EntityHat['unknown'/1225, l='MpServer', x=-132,56, y=37,00, z=248,00], EntityChicken['Chicken'/406, l='MpServer', x=-128,84, y=65,00, z=236,16], EntityHat['unknown'/1224, l='MpServer', x=-116,44, y=15,00, z=251,94], EntitySkeleton['Skeleton'/407, l='MpServer', x=-141,34, y=71,00, z=224,78], EntityHat['unknown'/1227, l='MpServer', x=-36,50, y=25,00, z=239,94], EntityHat['unknown'/1226, l='MpServer', x=-59,44, y=16,00, z=166,97], EntityBat['Bat'/405, l='MpServer', x=-100,75, y=25,85, z=274,04], EntitySkeleton['Skeleton'/395, l='MpServer', x=-62,16, y=66,00, z=230,50], EntityChicken['Chicken'/394, l='MpServer', x=-66,28, y=62,46, z=185,25], EntityChicken['Chicken'/393, l='MpServer', x=-78,44, y=63,00, z=182,53], EntityCreeper['Creeper'/399, l='MpServer', x=-117,72, y=65,00, z=188,06], EntityCreeper['Creeper'/398, l='MpServer', x=-116,44, y=15,00, z=251,94], EntityEnderman['Enderman'/397, l='MpServer', x=-78,56, y=55,00, z=254,00], EntitySkeleton['Skeleton'/396, l='MpServer', x=-49,50, y=68,00, z=230,50], EntityCreeper['Creeper'/387, l='MpServer', x=-98,50, y=22,00, z=248,00], EntityCreeper['Creeper'/386, l='MpServer', x=-104,50, y=17,00, z=245,50], EntityCreeper['Creeper'/385, l='MpServer', x=-94,50, y=29,00, z=248,50], EntityZombie['Zombie'/384, l='MpServer', x=-93,06, y=32,00, z=253,50], EntityZombie['Zombie'/391, l='MpServer', x=-107,48, y=69,00, z=209,56], EntitySkeleton['Skeleton'/390, l='MpServer', x=-100,94, y=62,00, z=191,50], EntitySkeleton['Skeleton'/389, l='MpServer', x=-106,91, y=61,00, z=183,50], EntityCreeper['Creeper'/388, l='MpServer', x=-125,78, y=70,00, z=205,16], EntityCreeper['Creeper'/440, l='MpServer', x=-149,50, y=64,00, z=246,50], EntityChicken['Chicken'/441, l='MpServer', x=-157,97, y=68,00, z=176,25], EntitySkeleton['Skeleton'/442, l='MpServer', x=-127,06, y=66,00, z=150,50], EntityZombie['Zombie'/443, l='MpServer', x=-59,47, y=68,00, z=147,03], EntityZombie['Zombie'/444, l='MpServer', x=-58,69, y=60,05, z=171,53], EntityZombie['Zombie'/445, l='MpServer', x=-53,50, y=69,00, z=148,50], EntityBat['Bat'/433, l='MpServer', x=-81,34, y=33,99, z=276,43], EntityChicken['Chicken'/434, l='MpServer', x=-79,59, y=74,00, z=272,63], EntityZombie['Zombie'/435, l='MpServer', x=-129,66, y=37,00, z=258,34], EntityChicken['Chicken'/436, l='MpServer', x=-129,53, y=71,00, z=259,44], EntityChicken['Chicken'/438, l='MpServer', x=-42,47, y=71,00, z=269,38], EntityChicken['Chicken'/439, l='MpServer', x=-116,44, y=67,00, z=287,56], EntityZombie['Zombie'/424, l='MpServer', x=-36,50, y=25,00, z=239,94], EntityCreeper['Creeper'/427, l='MpServer', x=-108,72, y=61,00, z=284,09], EntityBat['Bat'/426, l='MpServer', x=-97,25, y=28,10, z=273,63], EntityChicken['Chicken'/428, l='MpServer', x=-157,44, y=71,00, z=195,56], EntityZombie['Zombie'/416, l='MpServer', x=-132,56, y=37,00, z=248,00], EntityChicken['Chicken'/419, l='MpServer', x=-141,41, y=70,00, z=196,44], EntityChicken['Chicken'/418, l='MpServer', x=-139,59, y=66,00, z=255,63], EntitySquid['Squid'/421, l='MpServer', x=-116,59, y=61,00, z=156,09], EntityBat['Bat'/420, l='MpServer', x=-115,94, y=27,10, z=174,41], EntityCreeper['Creeper'/423, l='MpServer', x=-59,44, y=16,00, z=166,97], EntitySpider['Spider'/478, l='MpServer', x=-157,94, y=68,00, z=178,81], EntityZombie['Zombie'/479, l='MpServer', x=-169,50, y=67,00, z=177,50], EntityTrail['unknown'/748, l='MpServer', x=-115,30, y=82,62, z=214,02], EntitySkeleton['Skeleton'/470, l='MpServer', x=-163,56, y=11,00, z=222,94], EntityChicken['Chicken'/471, l='MpServer', x=-165,44, y=64,00, z=228,38], EntitySkeleton['Skeleton'/469, l='MpServer', x=-169,75, y=12,00, z=231,13], EntityBat['Bat'/467, l='MpServer', x=-103,60, y=22,49, z=262,34], EntitySkeleton['Skeleton'/463, l='MpServer', x=-82,84, y=70,00, z=290,44], EntityCreeper['Creeper'/462, l='MpServer', x=-89,50, y=68,00, z=293,50], EntityCow['Cow'/459, l='MpServer', x=-93,53, y=68,00, z=291,47], EntityCow['Cow'/458, l='MpServer', x=-92,47, y=68,00, z=291,50], EntityCow['Cow'/457, l='MpServer', x=-94,53, y=68,00, z=292,53], EntitySkeleton['Skeleton'/451, l='MpServer', x=-151,16, y=62,51, z=165,75], EntityChicken['Chicken'/450, l='MpServer', x=-148,59, y=65,00, z=271,34], EntityCreeper['Creeper'/449, l='MpServer', x=-132,59, y=53,00, z=281,00], EntityCreeper['Creeper'/448, l='MpServer', x=-147,06, y=40,00, z=276,50], EntitySheep['Sheep'/510, l='MpServer', x=-179,66, y=72,00, z=282,56], EntityHat['unknown'/714, l='MpServer', x=-115,30, y=82,62, z=214,02], EntitySpider['Spider'/500, l='MpServer', x=-180,72, y=67,14, z=158,63], EntitySheep['Sheep'/494, l='MpServer', x=-146,09, y=67,00, z=294,44], EntitySkeleton['Skeleton'/485, l='MpServer', x=-172,88, y=71,00, z=278,66], EntityZombie['Zombie'/480, l='MpServer', x=-162,50, y=67,00, z=182,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 340541264 bytes (324 MB) / 767492096 bytes (731 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1258 Minecraft Forge 10.13.2.1258 47 mods loaded, 47 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1258} [Forge Mod Loader] (forge-1.7.10-10.13.2.1258.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1258} [Minecraft Forge] (forge-1.7.10-10.13.2.1258.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpackscore{1.0} [Simply Jetpacks Coremod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	oresheepmod{v2.4} [Ore Sheep] (1.7.10-OreSheepMod-v2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	walljump{1.2.1c} [WallJump] ([1.7.10] [Forge] Wall Jump 1.2.1c by NukeDuck.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	hearts{1.0} [Hearts] ([1.7.10][1.7.2] Heart Crystal 1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.3.3} [BuildCraft] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.3.3} [BC Transport] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.3} [BC Silicon] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.3.3} [BC Builders] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.3.3} [BC Energy] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.3.3} [BC Factory] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CosmeticArmor{1.0.1} [Cosmetic Armor] (Cosmetic-Armor-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	deconstruction{2.2.5} [The Deconstruction Mod] (Deconstruction-Table-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eyemod{EyeOS4.1-1.7.10} [EyeMod] (Eyemod-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ftfloocraft{1.7.10-0.3.1} [Floocraft] (Floocraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	foxlib{1.7.10-0.6.0} [FoxLib] (FoxLib-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.660-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.660-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.257.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.257.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lootbags{1.4.1a} [Loot Bags] (LootBags-1.7.10-1.4.1a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Morph{0.9.0} [Morph] (Morphing-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.376.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SGCraft{1.9.0} [Greg's SG Craft] (SGCraft-1.9.0-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{1.0.0} [Simply Jetpacks] (Simply-Jetpacks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SwordPedestal{1.0(1.7.10)} [Sword Pedestal] (Sword-Pedestal-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Tails{1.7.10-1.2.3} [Tails] (Tails-1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1258
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.0.86, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by alpharulesirulee** [comment]
should be fixed in the next update

**Comment by bonii-xx** [comment]
Your arrows seem to not exist for some reason.
