### ISSUE TITLE
please halp meh

### ISSUE THREAD

**Issue by sparxs14** [SlimeKnights/TinkersConstruct#1447]
every time with 1.7.10 i put anything in the smelter it crashes and gives me this
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tconstruct.library.crafting.Smeltery.getLiquifyTemperature(Smeltery.java:107)
	at tconstruct.smeltery.logic.SmelteryLogic.updateTemperatures(SmelteryLogic.java:521)
	at tconstruct.smeltery.logic.SmelteryLogic.func_70296_d(SmelteryLogic.java:679)
	at tconstruct.smeltery.logic.SmelteryLogic.onDataPacket(SmelteryLogic.java:1169)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

**Comment by TherminatorX** [comment]
We need the full log in a pastebin, but you likely need to update your Mantle.

**Comment by sparxs14** [comment]
i will try that in a bit thanks will post full log if it dosent work

**Comment by sparxs14** [comment]
it fixed it thanks :)
