### ISSUE TITLE
Tconstruct incompatibilaty with zeldaswordskills

### ISSUE THREAD

**Issue by Xalis708** [SlimeKnights/TinkersConstruct#1497]
If this is an issue you what to fix I will be very happy, I love Everything about your mods.
Using TConstruct-1.7.10-1.8.3b with zeldaswordskills-2.2.5.b 

Thank you for all your hard work, it has brought me many hours of fun.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 22/03/15 10:15 AM
Description: Initializing game

java.lang.NoClassDefFoundError: tconstruct/items/tools/Broadsword
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: tconstruct.items.tools.Broadsword
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/tools/Weapon
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.tools.Weapon
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Vista (x86) version 6.0
	Java Version: 1.7.0_55, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 94888504 bytes (90 MB) / 256823296 bytes (244 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 21 mods loaded, 21 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed
	bspkrsCore{6.16} [bspkrsCore] (bspkrsCore-universal-6.16.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded
	TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar) Unloaded
	tinkersdefense{1.2} [Tinkers' Defense] (Tinkers-Defense-1.2.1.jar) Unloaded
	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded
	zeldaswordskills{1.7.10-2.2.5.b} [Zelda Sword Skills] (zeldaswordskills-2.2.5.b.jar) Unloaded
	IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce 8800 GT/PCI/SSE2 GL version 3.2.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by bonii-xx** [comment]
Full log?

**Comment by Xalis708** [comment]
I clicked select all, is something missing?

**Comment by bonii-xx** [comment]
Err, should've been more clear. I meant I'll need the full client/server-log from the logs folder not just the crashlog. I'm suspecting something changed with the classes zeldaswordskills uses which then breaks on startup.

**Comment by Xalis708** [comment]
Had to empty the folder to be sure what you needed, these are the 3 files
it left after recreating the crash.

For future reference which of the 3 did you need?.

Thank you.

**Comment by laz2727** [comment]
Just send everything already.

2015-03-23 23:35 GMT+06:00 Xalis708 <notifications@github.com>:

> Had to empty the folder to be sure what you needed, these are the 3 files
> it left after recreating the crash.
>
> For future reference which of the 3 did you need?.
>
> Thank you.
>

**Comment by Xalis708** [comment]
Do Attached files not show here, should I resend in pure text form?

**Comment by laz2727** [comment]
Just use a file hosting, like rghost.

**Comment by Xalis708** [comment]
http://rghost.net/88GwxSVbR

pass word 1234

Hope it works :)

**Comment by Xalis708** [comment]
oops deleted, I hate this sigh 1 sec

**Comment by Xalis708** [comment]
http://rghost.net/7LSsWhfql

**Comment by Xalis708** [comment]
No password anymore

**Comment by bonii-xx** [comment]
Ok. either this is a really weird forge/fml bug (unlikely), a really weird mod interaction (possible) or something in your tinkers file went incredibly wrong.
Try redownloading tinkers, and if it still happens create a clean instance with only tinkers and mantle, and then always add a few mods until it happens again to find out which mod causes the issue, then we might know more.
Only tinkers and zeldaswordskills works fine in my dev environment.

**Comment by bonii-xx** [comment]
Okay funny thing. Try renaming the file for mine and blade 2 battlegear so that it starts with "a". Just put an "a" at the front of the filename and see if that fixes it.

**Comment by Xalis708** [comment]
I tested "a" first in mod folder and config, I don't know any other files,
moving on to re-downloading, and try it again.

**Comment by Xalis708** [comment]
Interesting news, I had the new downloads installed, all fine, with
Tcon/zelda, then added battlegear, then Tdef all fine, then the iguana
crashes.

In my need for iguanatweaks I decided to hit play one more time, and... it
worked, I know I hit play many times before I sent the first crash report
as I have heard sometimes it may need a second restart.

Would you like me to send you the log? as I cant be sure what happened for
it to work, ether way I'm happy, it looks like a great adventure.

"a" not in use.

Thank you again.

**Comment by bonii-xx** [comment]
It seems to be an issue when battlegear loads before tinkers, hm. And I misspoke anyway, the "a" would've gone in front of tcon so it's loaded before battlegear. Weird.

**Comment by Xalis708** [comment]
Very weird, yet it's working great, case closed.

**Comment by bonii-xx** [comment]
518e04252ce9876f06e9289209cd25662181a296
