### ISSUE TITLE
Replace part Tool rod (stone) Client crash (IG Tweaks)

### ISSUE THREAD

**Issue by seppitm** [SlimeKnights/TinkersConstruct#1536]
The client crashes when i replace the rod of my tool with a stonerod (IG Tweaks Mod). i'm using tc 1.8.3b

---- Minecraft Crash Report ----
// Why did you do that?

Time: 12.04.15 16:11
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
at iguanaman.iguanatweakstconstruct.replacing.ReplacementLogic.exchangeToolPart(ReplacementLogic.java:85)
at iguanaman.iguanatweakstconstruct.replacing.ModPartReplacement.modify(ModPartReplacement.java:183)
at tconstruct.library.crafting.ModifyBuilder.modifyItem(ModifyBuilder.java:34)
at tconstruct.tools.logic.ToolStationLogic.buildTool(ToolStationLogic.java:84)
at tconstruct.tools.logic.ToolStationLogic.func_70296_d(ToolStationLogic.java:65)
at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bonii-xx** [comment]
Should be fixed in dev. Also wrong mod.
