### ISSUE TITLE
I keep on crashing because of null fluid something like that

### ISSUE THREAD

**Issue by hawk6242** [SlimeKnights/TinkersConstruct#1549]
This is the crash report can you tell me why its crashing and how do i fix it. Please and thank you :)

http://pastebin.com/thvsweLm

**Comment by TherminatorX** [comment]
Looks like Inter-Mod from that second line. Do you still crash when Thermal Smeltery is removed?

**Comment by TherminatorX** [comment]
Based on the Forge version, it seems like the same bug report we've been getting for awhile, which has been fixed in the repository.
Duplicate issue.

**Comment by hawk6242** [comment]
so how do i fix?

**Comment by cocopuffs99** [comment]
Same issue: So is this fixed in a later release?  I'll try the latest TConstruct and test.  Thx

Getting this CTD when trying to empty Tinkers smeltery fluid metal into casting basin:

Rendering screen
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
at net.minecraftforge.fluids.FluidStack.(FluidStack.java:29)
at net.minecraftforge.fluids.FluidStack.(FluidStack.java:59)
at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full log: http://pastebin.com/3MuAh56b

**Comment by TherminatorX** [comment]
No, this /will/ be fixed when there is another release. Right now, you have to compile from the source code in order to have a version that works with Forge 13**

**Comment by bonii-xx** [comment]
Use alpha or a forge version <1351.

**Comment by cocopuffs99** [comment]
Can't because Ex-U now has a dependency on 1355 and above, so this makes RR3 and many ATLauncher modpacks that use TCon (pretty much almost all) get the crash if they also use Ex-U or other mods that use the new forge also =(

**Goes and cries in a corner.

**Comment by bonii-xx** [comment]
Curseforge

**Comment by cocopuffs99** [comment]
You, sir, there are no words. Now I can get back to tinkering!  ^_^
