### ISSUE TITLE
Client-side crash on joining server, something about slime tall grass

### ISSUE THREAD

**Issue by sogortheogre** [SlimeKnights/TinkersConstruct#1607]
Hello! I've been doing some updating on my server lately, and my players and I have been getting this client side crash:

java.lang.ArrayIndexOutOfBoundsException: 2
	at tconstruct.blocks.slime.SlimeTallGrass.func_149691_a(SlimeTallGrass.java:40)
	at net.minecraft.client.renderer.RenderBlocks.func_147787_a(RenderBlocks.java:8232)
	at net.minecraft.client.renderer.RenderBlocks.func_147746_l(RenderBlocks.java:3551)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:258)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I tried Googling a bit, but couldn't find much information (which either means it's something not many people have come across, or my search engine skills just aren't on point tonight). Any chance anyone has any ideas?

Full error report: http://pastebin.com/aXCzvT1k

**Comment by bonii-xx** [comment]
For some reason the block has an invalid metadata. Remove the block with a world editor or something.
