### ISSUE TITLE
Crash with extra utilities

### ISSUE THREAD

**Issue by Agent-Chase-SK** [SlimeKnights/TinkersConstruct#1662]
minecraft (1.7.10) crashes before main menu
http://pastebin.com/ZGiHyn86
openeye: http://openeye.openmods.info/crashes/fe40267f46fb5904cdecb483f25751d3

fixes when: 1. tconstruct (1.8.5) is disabled
                   2. extra utilities (1.2.6) is disabled
                   3. extra utilities is downgraded to 1.2.5

versions are latest, downloaded from curse client

**Comment by carlobon** [comment]
I have the same problem, with tcon 1.8.5 and extra utilities 1.2.6 i crash while with extra utilities 1.2.5 i don't crash.
The problem is that is tcon that say error in the crash report

**Comment by MrKunji** [comment]
Funny enough, installing CoFH Core makes everything behave

![](http://i.imgur.com/lw0QkSO.png)

**Comment by Agent-Chase-SK** [comment]
Also works for me. But i haven't seen it as a reqirement.

**Comment by MrKunji** [comment]
Treat it as a workaround for now.

**Comment by carlobon** [comment]
Also work for me

**Comment by bonii-xx** [comment]
Extra utilities ships the RF API but gets loaded after TCon so it crashes. Adding CofhCore ensures the correct load order. It's basically an unfixable problem because of how APIs work.
So the gist of it: If anything in your modpack has RF, add CofhCore.

**Comment by Normal69** [comment]
Something is fishy about liquid bedrock - I have CofhCore installed.

java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_110450_ap from class com.rwtema.extrautils.modintegration.TConTextureResourcePackBedrockium
	at com.rwtema.extrautils.modintegration.TConTextureResourcePackBedrockium.getBedrockImage(TConTextureResourcePackBedrockium.java:60)
	at com.rwtema.extrautils.texture.TextureBedrockLava.processImage(TextureBedrockLava.java:30)
	at com.rwtema.extrautils.texture.TextureDerived.load(TextureDerived.java:77)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:174)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:124)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:76)
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:63)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by bonii-xx** [comment]
Stop unpacking your mods.
