### ISSUE TITLE
Minecraft crashes on startup when running TinkersConstruct

### ISSUE THREAD

**Issue by GyllieGyllie** [SlimeKnights/TinkersConstruct#1722]
I'm trying to make a custom mod pack for a series. All mods work except for the Tinkers construct.
When Tinkers construct version 1.8.5 is in the mods folder minecraft crashes when starting. If I remove just that one everything works fine.

Error:

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 10/08/15 16:01
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.tools.ToolCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 338842760 bytes (323 MB) / 585629696 bytes (558 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UC	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UC	backpacks16840{3.0.3} [Backpacks!] (Backpacks-Mod-by-Brad16840-1.7.10.jar) 
	UC	SC0_SpaceCore{0.7.14} [SpaceCore] (1.7.10-SpaceCore-0.7.14.jar) 
	UC	SC0_UsefulPets{1.3} [Useful Pets] (1.7.10-Useful_Pets-1.3.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	njaymod_4{1.1.1} [NJay's Unicorn Mod] ([1.7.x] NJays Unicorn Mod (v1.1.1).jar) 
	UC	CoroAI{v1.0} [CoroAI] (CoroUtil-1.0.jar) 
	UC	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.0.jar) 
	UC	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.0.jar) 
	UC	eggygoodness{1.0.0.1024} [Eggy Goodness] (eggygoodness-1.7.2-1.0.0.1024.jar) 
	UC	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UC	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UC	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UC	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UC	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UC	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UC	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
	UC	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UC	ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UC	ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre8.92-World.jar) 
	UE	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UC	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
	UC	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UC	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
	UC	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
	UC	ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UC	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UC	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar) 
	UC	runicdungeons{1.1.5c} [Runic Dungeons] (runicdungeons-1.1.5c.jar) 
	UC	telepads{1.6.4 v5} [Teleportation Pads] (Telepads-1.7.2_1.7.jar) 
	UC	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) 
	UC	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UC	weather2{v2.3.4} [weather2] (Weather-2.3.4.jar) 
	UC	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4600'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.

**Comment by MrKunji** [comment]
Install CoFH Core to sort the API load order.
