### ISSUE TITLE
Crash on village generation with Smeltery disabled

### ISSUE THREAD

**Issue by WalterWeight** [SlimeKnights/TinkersConstruct#1729]
I'm putting together a modpack, and have recently introduced Tinker's into my pack, however my pack is a very vanilla-esque pack, and as such, I've disabled pretty much everything in tinkers apart from the tool station. My TimkersModules.cfg is as follows:

    "modules: disabling these will disable a chunk of the mod" {
        # Adds a gear cast if other mods provide gears
        B:"Tinkers Gears"=false
    
        # Modifyable armors, such as the traveller's gear.
        B:"Tinkers' Armory"=false
    
        # Mechanical machinations and steampunk inspired shenanigans.
        B:"Tinkers' Mechworks"=false
    
        # Liquid metals, casting, and the multiblock structure.
        B:"Tinkers' Smeltery"=false
    
        # The main core of the mod! All of the tools, the tables, and the patterns are here.
        B:"Tinkers' Weaponry"=true
    }

I've tested this in both single player and multiplayer (with a dedicated server), and as soon as I approach a village and world gen starts to create a village with a smeltery, the server (or client in SMP) crashes. On restarting, I can then go to the village and I see the following, which obviously shows Tinker's attempting to build a smeltery. As you can see, it also halts generation of the village.

![2015-08-16_22 56 54](https://cloud.githubusercontent.com/assets/1747010/9295604/2f276b98-446b-11e5-890e-2446d384d1d8.png)

I've no other mods that affect village generation, and the crash log (attached) shows a reference to Tinkers and the (disabled) smeltery.

**Comment by WalterWeight** [comment]
`[22:54:14] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 16/08/15 22:54
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.gen.structure.StructureComponent.func_151550_a(StructureComponent.java:541)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_151550_a(StructureVillagePieces.java:1698)
	at net.minecraft.world.gen.structure.StructureComponent.func_151556_a(StructureComponent.java:607)
	at tconstruct.world.village.ComponentSmeltery.fillWithMetaBlocks(ComponentSmeltery.java:95)
	at tconstruct.world.village.ComponentSmeltery.func_74875_a(ComponentSmeltery.java:61)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
	at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:382)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:190)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.gen.structure.StructureComponent.func_151550_a(StructureComponent.java:541)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_151550_a(StructureVillagePieces.java:1698)
	at net.minecraft.world.gen.structure.StructureComponent.func_151556_a(StructureComponent.java:607)
	at tconstruct.world.village.ComponentSmeltery.fillWithMetaBlocks(ComponentSmeltery.java:95)
	at tconstruct.world.village.ComponentSmeltery.func_74875_a(ComponentSmeltery.java:61)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
	at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:382)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:190)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)`
