### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by EpicMan2** [SlimeKnights/TinkersConstruct#1781]
Well, i report again.
[14:08:44] [Client thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers' Armory...
[14:08:44] [Client thread/INFO] [LiteLoader/TConstruct]: Injecting onc0dpacketclosewindow[x1] in func_148833_a in C0DPacketCloseWindow
[14:08:44] [Client thread/WARN] [PulseManager-TConstruct/TConstruct]: Caught exception in findAndInvokeHandlers: java.lang.reflect.InvocationTargetException
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mantle.pulsar.control.PulseManager.findAndInvokeHandlers(PulseManager.java:235)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mantle.pulsar.control.PulseManager.preInit(PulseManager.java:189)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tconstruct.TConstruct.preInit(TConstruct.java:184)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at launcher.client.ClientLauncher.launch(ClientLauncher.java:261)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at launcher.client.ClientLauncher.main(ClientLauncher.java:176)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/client/FMLClientHandler
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tconstruct.client.tabs.TabRegistry.<clinit>(TabRegistry.java:42)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tconstruct.armor.ArmorProxyClient.preInit(ArmorProxyClient.java:73)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tconstruct.armor.TinkerArmor.preInit(TinkerArmor.java:79)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 49 more
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.client.FMLClientHandler
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:195)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 52 more
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
[14:08:44] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 54 more

But when i connect to the server i get:
[14:09:32] [Netty Client IO #0/ERROR] [FML/]: Failed to connect to server: there are 16 missing blocks and items
[14:09:32] [Netty Client IO #0/DEBUG] [FML/]: Missing list: [TConstruct:Armor.DryingRack, TConstruct:knapsack, TConstruct:diamondApple, TConstruct:travelBelt, TConstruct:travelBoots, TConstruct:jerky, TConstruct:bootsWood, TConstruct:travelWings, TConstruct:helmetWood, TConstruct:chestplateWood, TConstruct:heartCanister, TConstruct:travelGoggles, TConstruct:travelVest, TConstruct:Armor.DryingRack, TConstruct:travelGlove, TConstruct:leggingsWood]

Minecraft 1.7.10
Forge 7.99.32.1517
Java 8

Mod list:
bspkrsCore
ArmorStatusHUD
DirectionHUD
BiblioCraft
BiomesOPlenty
CoFHCore
CustomSpawner
DamageIndicatorsMod
MoCreatures
dungeonpack
FastCraft
IronChest
Mantle
iChunUtil
Morph
NEIAddons
ReiMinimap
CoFHLib
CoFHAPI
Baubles
TConstruct - 1.7.10-1.8.7.build979
Thaumcraft
ForgeMultipart
ThaumicTinkerer
Optifine

Can you help me?

**Comment by AlterAkima** [comment]
It feels like a module is disabled, check the configuration files.

**Comment by EpicMan2** [comment]
All enabled. Config is ok.

**Comment by AlterAkima** [comment]
It may be disabled in the server side.

**Comment by EpicMan2** [comment]
Well i checked server's config - all enabled too.
# Configuration file

"modules: disabling these will disable a chunk of the mod" {
    # Adds a gear cast if other mods provide gears
    B:"Tinkers Gears"=true

    # Modifyable armors, such as the traveller's gear.
    B:"Tinkers' Armory"=true

    # Mechanical machinations and steampunk inspired shenanigans.
    B:"Tinkers' Mechworks"=true

    # Liquid metals, casting, and the multiblock structure.
    B:"Tinkers' Smeltery"=true

    # The main core of the mod! All of the tools, the tables, and the patterns are here.
    B:"Tinkers' Weaponry"=true
}


    B:"Enable mod blue slime tools"=true
    B:"Enable mod bone tools"=true
    B:"Enable mod cactus tools"=true
    B:"Enable mod flint tools"=true
    B:"Enable mod netherrack tools"=true
    B:"Enable mod paper tools"=true
    B:"Enable mod slime tools"=true
    B:"Enable mod stone tools"=true
    B:"Enable mod wooden tools"=true

**Comment by bonii-xx** [comment]
Remove mods until it works. Start with Liteloader, Optifine and Fastcraft.

**Comment by EpicMan2** [comment]
Well, it was CustomNPC.
Can you do something or i must report this issue to CustomNPC author?

**Comment by bonii-xx** [comment]
I can only tell you that it's nothing tcon does.
