### ISSUE TITLE
Client crash to loader when viewing smeltery GUI.

### ISSUE THREAD

**Issue by Dooglesmile** [SlimeKnights/TinkersConstruct#1861]
Hi, I'm in the process of putting a mod pack together and while testing I keep getting a crash to desktop while looking in the smeltery GUI after melting down some ore.
The error seems to be to do with an unknown fluid entry when hovering over a tiny amount of lava in the right hand fuel display.

[01:26:07] [Client thread/DEBUG] [FML/]: Method tconstruct.smeltery.gui.SmelteryGui.getLiquidTooltip(Lnet/minecraftforge/fluids/FluidStack;Z)Ljava/util/List;: Replacing GETFIELD fluidID with INVOKEVIRTUAL getFluidID
[01:26:07] [Client thread/DEBUG] [FML/]: Method tconstruct.smeltery.gui.SmelteryGui.func_73864_a(III)V: Replacing GETFIELD fluidID with INVOKEVIRTUAL getFluidID
[01:26:07] [Client thread/INFO] [inventorytweaks/]: tconstruct.smeltery.gui.SmelteryGui
[01:26:14] [Client thread/WARN] [FML/]: ****************************************
[01:26:14] [Client thread/WARN] [FML/]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[01:26:14] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[01:26:14] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[01:26:14] [Client thread/WARN] [FML/]: *  at tconstruct.smeltery.gui.SmelteryGui.drawGuiContainerForegroundLayer(SmelteryGui.java:160)
[01:26:14] [Client thread/WARN] [FML/]: *  at tconstruct.client.gui.NewContainerGui.func_73863_a(NewContainerGui.java:165)
[01:26:14] [Client thread/WARN] [FML/]: *  at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:60)
[01:26:14] [Client thread/WARN] [FML/]: *  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)...
[01:26:14] [Client thread/WARN] [FML/]: ****************************************
Screenshot below show the fluid container, it allows me to hover over the melted liquid, showing the tooltip, but when I move the mouse over the tiny bit of lava left on the right side, the game crashes to desktop.

(Image wasn't uploading so putting it on postimg.org website)
http://postimg.org/image/drdx3ecpv/

Full crash log is here:
http://pastebin.com/7K2ZU9uC

Any ideas what I can do to fix this crash?

**Comment by bonii-xx** [comment]
TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar)
Your TCon version is 1 1/2 years old.

**Comment by Dooglesmile** [comment]
Ah right, I'll check that then.
That'll be because I downloaded the file from here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287648-tinkers-construct
Which is still pointing to version 1.6.0d40!

**Comment by bonii-xx** [comment]
>This thread has moved to a new owner.

:P
