### ISSUE TITLE
Putting a Buildcraft Pipe into a Crafting Station in 1.8.9

### ISSUE THREAD

**Issue by LyraKitsune** [SlimeKnights/TinkersConstruct#1878]
[20:56:51] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:105) ~[bgd.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:192) ~[bht.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78) ~[bhp.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121) ~[bho.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:903) ~[bfr.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057) ~[bfk.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051) ~[ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at javax.vecmath.Tuple3f.<init>(Tuple3f.java:81) ~[vecmath-1.5.2.jar:1.5.2]
	at javax.vecmath.Vector3f.<init>(Vector3f.java:65) ~[vecmath-1.5.2.jar:1.5.2]
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.put(TRSRBakedModel.java:153) ~[TRSRBakedModel$Transformer.class:?]
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:64) ~[UnpackedBakedQuad.class:?]
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:75) ~[TRSRBakedModel.class:?]
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42) ~[TRSRBakedModel.class:?]
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38) ~[TRSRBakedModel.class:?]
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:134) ~[BakedTableModel.class:?]
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:87) ~[BakedTableModel.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152) ~[bgd.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93) ~[bgd.class:?]
	... 24 more
[20:56:51] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-27.jar)
  LoadingPlugin (FastLeaveDecay-1.2.jar)
  LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  TrashSlot (trashslot-mc1.8.9-2.0.7.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 14/01/16 8:56 PM
Description: Tesselating block in world

java.lang.ArrayIndexOutOfBoundsException: 0
	at javax.vecmath.Tuple3f.<init>(Tuple3f.java:81)
	at javax.vecmath.Vector3f.<init>(Vector3f.java:65)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.put(TRSRBakedModel.java:153)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:64)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:75)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:134)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:87)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:192)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:903)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at javax.vecmath.Tuple3f.<init>(Tuple3f.java:81)
	at javax.vecmath.Vector3f.<init>(Vector3f.java:65)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.put(TRSRBakedModel.java:153)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:64)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:75)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:134)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:87)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152)

-- Block being tesselated --
Details:
	Block type: ID #1300 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.block.BlockToolTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (270,65,-205), Chunk: (at 14,4,3 in 16,-13; contains blocks 256,0,-208 to 271,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:192)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:903)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['<PROFILE NAME>'/1599, l='MpServer', x=270.80, y=65.00, z=-201.64]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 204.00,64.00,-104.00 - World: (204,64,-104), Chunk: (at 12,4,8 in 12,-7; contains blocks 192,0,-112 to 207,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 90542 game time, 90542 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 43 total; [EntityRabbit['Rabbit'/1344, l='MpServer', x=208.34, y=65.00, z=-206.72], EntityPlayerSP['<PROFILE NAME>'/1599, l='MpServer', x=270.80, y=65.00, z=-201.64], EntityRabbit['Rabbit'/1345, l='MpServer', x=213.91, y=67.00, z=-201.38], EntityCow['Cow'/1410, l='MpServer', x=312.16, y=69.00, z=-247.28], EntityCow['Cow'/1411, l='MpServer', x=308.53, y=68.00, z=-180.97], EntityRabbit['Rabbit'/1412, l='MpServer', x=313.59, y=67.00, z=-172.75], EntityPig['Pig'/1348, l='MpServer', x=217.00, y=70.00, z=-123.81], EntityCow['Cow'/1413, l='MpServer', x=314.84, y=68.00, z=-167.00], EntityRabbit['Rabbit'/1414, l='MpServer', x=322.06, y=73.00, z=-150.56], EntityPig['Pig'/1350, l='MpServer', x=215.75, y=70.00, z=-123.00], EntityRabbit['Rabbit'/1415, l='MpServer', x=310.47, y=81.00, z=-140.91], EntityPig['Pig'/1351, l='MpServer', x=216.44, y=71.00, z=-127.72], EntityRabbit['Rabbit'/1355, l='MpServer', x=223.22, y=65.00, z=-197.38], EntityRabbit['Rabbit'/1356, l='MpServer', x=235.34, y=65.00, z=-166.44], EntityCow['Cow'/1423, l='MpServer', x=326.69, y=67.00, z=-198.56], EntityRabbit['Rabbit'/1424, l='MpServer', x=328.72, y=72.00, z=-130.06], EntityAuraNode['Aura Node'/1425, l='MpServer', x=328.50, y=80.50, z=-135.50], EntityAuraNode['Aura Node'/1363, l='MpServer', x=251.50, y=87.50, z=-237.50], EntityRabbit['Rabbit'/1364, l='MpServer', x=240.34, y=67.00, z=-165.78], EntityRabbit['Rabbit'/1365, l='MpServer', x=243.34, y=64.00, z=-170.81], EntityRabbit['Rabbit'/1366, l='MpServer', x=250.31, y=63.00, z=-158.88], EntityAuraNode['Aura Node'/1367, l='MpServer', x=248.50, y=72.50, z=-97.50], EntityPig['Pig'/1441, l='MpServer', x=347.28, y=64.00, z=-222.47], EntityAuraNode['Aura Node'/1442, l='MpServer', x=341.50, y=65.50, z=-99.50], EntityRabbit['Rabbit'/1389, l='MpServer', x=260.81, y=63.00, z=-245.09], EntityAuraNode['Aura Node'/1390, l='MpServer', x=266.50, y=64.50, z=-251.50], EntityRabbit['Rabbit'/1391, l='MpServer', x=267.84, y=64.00, z=-251.78], EntityItem['item.tile.stonebrick'/1392, l='MpServer', x=268.66, y=61.00, z=-205.66], EntityItem['item.tile.waterlily.lily_medium'/1393, l='MpServer', x=264.56, y=61.00, z=-205.28], EntityItem['item.tile.stonebrick'/1394, l='MpServer', x=266.66, y=61.00, z=-205.13], EntityVillager['Villager'/1396, l='MpServer', x=273.38, y=65.00, z=-229.31], EntityVillager['Villager'/1397, l='MpServer', x=273.13, y=63.00, z=-217.56], EntityAuraNode['Aura Node'/1333, l='MpServer', x=205.50, y=48.50, z=-194.50], EntityVillager['Villager'/1398, l='MpServer', x=272.16, y=62.28, z=-217.63], EntityRabbit['Rabbit'/1334, l='MpServer', x=205.50, y=71.00, z=-193.56], EntityVillager['Villager'/1399, l='MpServer', x=279.13, y=65.00, z=-211.50], EntityCow['Cow'/1335, l='MpServer', x=199.91, y=72.00, z=-146.09], EntityBat['Bat'/1400, l='MpServer', x=279.25, y=50.10, z=-205.34], EntityCow['Cow'/1336, l='MpServer', x=194.75, y=72.00, z=-144.50], EntityRabbit['Rabbit'/1401, l='MpServer', x=290.88, y=66.00, z=-244.72], EntityCow['Cow'/1337, l='MpServer', x=196.38, y=76.00, z=-130.38], EntityBat['Bat'/1402, l='MpServer', x=288.34, y=53.10, z=-192.25], EntityRabbit['Rabbit'/1403, l='MpServer', x=305.25, y=75.00, z=-151.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 626765480 bytes (597 MB) / 2116550656 bytes (2018 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 90
	FML: MCP 9.19 Powered by Forge 11.15.0.1696 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1696-universal.jar) 
	UCHIJAAAA	Forge{11.15.0.1696} [Minecraft Forge] (forge-1.8.9-11.15.0.1696-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.0-pre6} [BuildCraft] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.0-pre6} [BC Energy] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	ActuallyAdditions{1.8.9-r23} [Actually Additions] (ActuallyAdditions-1.8.9-r23.jar) 
	UCHIJAAAA	FurnaceEvolved{1.8.9-0.0.1.3} [Furnace Evolved] (Alt-F4-0.0.1.3.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	aura{unspecified} [Aura Cascade] (AuraCascade-1.8.8-v0.2.2a.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1623-universal.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-4} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-4.jar) 
	UCHIJAAAA	Thaumcraft{5.1.3} [Thaumcraft] (Thaumcraft-1.8.9-5.1.3.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-404d994.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.0-pre6} [BC Transport] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.0-pre6} [BC Factory] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.0-pre6} [BC Silicon] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.0-pre6} [BC Robotics] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.0-pre6} [BC Builders] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	mcmultipart{1.0.3} [MCMultiPart] (MCMultiPart-1.0.3-universal.jar) 
	UCHIJAAAA	CharsetLib{0.1.2} [â€½] (Charset-0.1.2-c53ca8e9d27473d2368de884.jar) 
	UCHIJAAAA	CharsetTweaks{0.1.2} [*] (Charset-0.1.2-c53ca8e9d27473d2368de884.jar) 
	UCHIJAAAA	CharsetWires{0.1.2} [+] (Charset-0.1.2-c53ca8e9d27473d2368de884.jar) 
	UCHIJAAAA	CharsetPipes{0.1.2} [|] (Charset-0.1.2-c53ca8e9d27473d2368de884.jar) 
	UCHIJAAAA	CharsetGates{0.1.2} [&] (Charset-0.1.2-c53ca8e9d27473d2368de884.jar) 
	UCHIJAAAA	chiselsandbits{@version@} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8-beta1.jar) 
	UCHIJAAAA	craftingtweaks{3.0.15} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.15.jar) 
	UCHIJAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.2.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-1.2.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
	UCHIJAAAA	foundry{1.3.2.0} [Foundry] (Foundry-1.8.9-1.3.2.0.jar) 
	UCHIJAAAA	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCHIJAAAA	inventorytweaks{1.60-dev-27-43ecdd2} [Inventory Tweaks] (InventoryTweaks-1.60-dev-27.jar) 
	UCHIJAAAA	IronChest{6.0.119.765} [Iron Chest] (ironchest-1.8.9-6.0.119.765.jar) 
	UCHIJAAAA	JEI{2.15.1.71} [Just Enough Items] (jei_1.8.9-2.15.1.71.jar) 
	UCHIJAAAA	JEIAddons{0.7.1.28} [Just Enough Items Addons] (JEIAddons_1.8.9-0.7.1.28.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	jeresources{0.0.1.@BUILD@} [Just Enough Resources] (JustEnoughResources-1.8.9-0.0.1.jar) 
	UCHIJAAAA	mantle{1.8.8-0.6.jenkins60} [Mantle] (Mantle-1.8.8-0.6.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJAAAA	NoNausea{1.0} [No Nausea] (NoNausea-MC1.8-1.0.jar) 
	UCHIJAAAA	packingtape{0.3} [Packing Tape] (Packing Tape-0.3.jar) 
	UCHIJAAAA	progressiveautomation{1.6.16} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.16.jar) 
	UCHIJAAAA	RandomThings{3.5.7} [Random Things] (RandomThings-MC1.8.8-3.5.7.jar) 
	UCHIJAAAA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJAAAA	rftools{4.20beta8} [RFTools] (rftools-1.8.9-4.20beta8.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.8.8.16} [Similsax Transtructors] (SimilsaxTranstructors-1.8.8.16.jar) 
	UCHIJAAAA	simpleretrogen{2.1} [Simple Retrogen] (simpleretrogen-2.1.jar) 
	UCHIJAAAA	sodacanutils{2.0.0} [Sodacan Utilities] (sodacanutils-2.0.jar) 
	UCHIJAAAA	Talismans 2{2.2.0} [Talismans 2] (Talismans2-1.8.9-2.2.0.jar) 
	UCHIJAAAA	tconstruct{1.8.8-2.0.1} [Tinkers' Construct] (TConstruct-1.8.8-2.0.1.jar) 
	UCHIJAAAA	totemic{1.8.9-0.6.3} [Totemic] (Totemic-1.8.9-0.6.3.jar) 
	UCHIJAAAA	trashslot{2.0.7} [TrashSlot] (trashslot-mc1.8.9-2.0.7.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	wawla{1.4.1} [What Are We Looking At] (Wawla-1.4.1-1.8+.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
FMLPlugin (InventoryTweaks-1.60-dev-27.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (FastLeaveDecay-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  
LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
TrashSlot (trashslot-mc1.8.9-2.0.7.jar)
  net.blay09.mods.trashslot.coremod.GuiContainerClassTransformer
  net.blay09.mods.trashslot.coremod.MinecraftClassTransformer
  net.blay09.mods.trashslot.coremod.InventoryTweaksClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12618 Compatibility Profile Context 13.251.9001.1001' Renderer: 'AMD Radeon HD 8330'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerMaterials (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8330 GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A4-5000 APU with Radeon(TM) HD Graphics 
[20:56:51] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Lyra\Desktop\MultiMC\instances\Modded 1.8\minecraft\crash-reports\crash-2016-01-14_20.56.51-client.txt
[20:56:51] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: mod.chiselsandbits.integration.jei.JEIPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: com.zerofall.ezstorage.jei.EZStoragePlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: exter.foundry.integration.jei.JEIFoundryPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: mezz.jei.plugins.vanilla.VanillaPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: mezz.jeiaddons.JEIAddonsPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: WayofTime.bloodmagic.compat.jei.BloodMagicPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: vapourdrive.furnaceevolved.FE_JEIPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: jeresources.jei.JEIConfig
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: mod.flatcoloredblocks.integration.PluginJEI
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: slimeknights.tconstruct.plugin.jei.JEIPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: mezz.jeiaddons.plugins.thaumcraft.PluginThaumcraft
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: vazkii.botania.client.integration.jei.JEIBotaniaPlugin
[20:56:52] [Server thread/INFO] [JEI]: Registered plugin: mezz.jei.plugins.jei.JEIPlugin
[20:56:53] [Server thread/INFO] [FML]: Applying holder lookups
[20:56:53] [Server thread/INFO] [FML]: Holder lookups applied
[20:56:53] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[20:56:53] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Game exited with exitcode -1.

**Comment by LyraKitsune** [comment]
Oh sorry, I didn't realized this was already reported.
