### ISSUE TITLE
Exception Spam on 1.8.9 dedicated server

### ISSUE THREAD

**Issue by Gaelan** [SlimeKnights/TinkersConstruct#1888]
When a player is logged into a dedicated server (on `localhost`, if that matters), this exception is spammed to the console:

```
[15:54:53] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Ticking player
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:379) ~[lf.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at slimeknights.tconstruct.library.tools.ToolCore.preventSlowDown(ToolCore.java:378) ~[ToolCore.class:?]
	at slimeknights.tconstruct.tools.item.LongSword.func_77663_a(LongSword.java:44) ~[LongSword.class:?]
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:410) ~[zx.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:315) ~[wm.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:542) ~[wn.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614) ~[pr.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283) ~[wn.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:328) ~[lf.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
```
As far as I can tell, everything works fine in spite of this.

**Comment by Gaelan** [comment]
Just noticed that players can only move client-side, not server-side. Not sure if this is a related issue.

**Comment by Gaelan** [comment]
UPDATE: Movement works fine if there is no longsword in the player's inventory. (Mattock works fine, haven't tested other TCon tools) Definitely seems like a TCon bug to me.

**Comment by bonii-xx** [comment]
Fixed indev.
