### ISSUE TITLE
[Issue] Longsword for T-Con v1.8.8-2.0.1 error, Locks up the player

### ISSUE THREAD

**Issue by Zenton8787** [SlimeKnights/TinkersConstruct#1889]
Minecraft v1.8.9
T-Con v1.8.8-2.0.1
Forge v1.8.9-11.15.0.1695
problem doesnt produce a crash report persay, but I was able to get a copy of the message forge was spitting out during the issue. that message is at the end.

the game started spitting out this data and prevented me from picking things up or breaking blocks, I think this was due to the issue taking sole priority over all actions for the player. this was done in a multiplayer server, but noone else was on to determain if it was just my game or the whole server. The issue started after I made a longsword in the T-Con crafting table. It essentially locked me in place. I could still move around and all but the server wouldnt register my actions. even after logging off then back intot he server, if I had moved it would put me back to the spot I was when I crafted the sword in front of the crafting table. in case it was how I made the sword, I made it with an iron blade, a stone stick, and a wood stick. 

Snippet of forge logs follow...
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
 at slimeknights.tconstruct.library.tools.ToolCore.preventSlowDown(ToolCore.java:378) ~[ToolCore.class:?]
 at slimeknights.tconstruct.tools.item.LongSword.func_77663_a(LongSword.java:44) ~[LongSword.class:?]
 at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:410) ~[zx.class:?]
 at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:315) ~[wm.class:?]
 at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:542) ~[wn.class:?]
 at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614) ~[pr.class:?]
 at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283) ~[wn.class:?]
 at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:328) ~[lf.class:?]
 at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
 at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
 at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[ip.class:?]
 at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_66]
 at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_66]
 at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
 ... 5 more

this message kept repeating on both the server command prompt window as well as the forge minecraft server monitor window

**Comment by Gaelan** [comment]
I already reported this in #1888.
