### ISSUE TITLE
Issue with Gold and Knight Slime in the Smeltery

### ISSUE THREAD

**Issue by ssblur** [SlimeKnights/TinkersConstruct#1911]
Whenever certain materials are moused over or clicked in the smeltery, namely gold and Knight Slime, a client would crash to desktop.

This issue does not seem to be replicable with other metals, but is replicable with other clients using Gold or Knight Slime.

This seems to be an issue with an ill-defined liquid 'name' as it were, as the crash produces this stack trace:
> java.lang.NullPointerException: Rendering screen
	at slimeknights.tconstruct.smeltery.client.GuiSmeltery.calcFluidGuiEntries(GuiSmeltery.java:226)
> 	at slimeknights.tconstruct.smeltery.client.GuiSmeltery.liquidToString(GuiSmeltery.java:195)
> 	at slimeknights.tconstruct.smeltery.client.GuiSmeltery.func_146979_b(GuiSmeltery.java:86)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:113)
> 	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:164)
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by ssblur** [comment]
Sorry about that, found duplicate issue at https://github.com/SlimeKnights/TinkersConstruct/issues/1900
