### ISSUE TITLE
Minecraft crashes when breaking blocks holding bows

### ISSUE THREAD

**Issue by littlebeast** [SlimeKnights/TinkersConstruct#1923]
So yeah that.  The game crashes when you use a bow to break a block.  This applies to both shortbows and crossbows at least, haven't tested with longbows.  Seems like it's probably all blocks, though I'm not sure; I've observed it with leaf blocks, OpenBlocks graves, and netherrack.

This is in TiC 1.8.8 build 988 in the Revolution pack.

The probably relevant part of the log:
```
[18/2/2016 18:35:13 PM] [18:35:13] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@2fb11025:
[18/2/2016 18:35:13 PM] java.lang.NullPointerException
[18/2/2016 18:35:13 PM] 	at Reika.DragonAPI.ModInteract.ItemHandlers.TinkerToolHandler.getPart(TinkerToolHandler.java:568) ~[TinkerToolHandler.class:?]
[18/2/2016 18:35:13 PM] 	at Reika.DragonAPI.ModInteract.DeepInteract.TinkerMaterialHelper.breakDisallowedTools(TinkerMaterialHelper.java:84) ~[TinkerMaterialHelper.class:?]
[18/2/2016 18:35:13 PM] 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1532_TinkerMaterialHelper_breakDisallowedTools_BreakEvent.invoke(.dynamic) ~[?:?]
[18/2/2016 18:35:13 PM] 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[18/2/2016 18:35:13 PM] 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) [ForgeHooks.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259) [mx.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217) [mx.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498) [nh.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) [ji.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) [ji.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[18/2/2016 18:35:13 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by bonii-xx** [comment]
Reikas bug.
