### ISSUE TITLE
Texture Stitching Error: 1.8.9-2.1.0 Dev (139)

### ISSUE THREAD

**Issue by artdude543** [SlimeKnights/TinkersConstruct#1929]
Heyo,

While updating support for Soartex I am expecting an issue with upsizing the patterns (both casts and wooden) to 64x. Which the game removes all resourcepacks from the game.
```
java.lang.ArrayIndexOutOfBoundsException: 392
	at slimeknights.tconstruct.library.client.texture.PatternTexture.colorPixel(PatternTexture.java:39) ~[PatternTexture.class:?]
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.processData(AbstractColoredTexture.java:103) ~[AbstractColoredTexture.class:?]
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.load(AbstractColoredTexture.java:84) ~[AbstractColoredTexture.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:120) ~[bmh.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:94) ~[bmh.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:125) ~[ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28) ~[bou.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130) ~[bnn.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111) ~[bnn.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:732) [ave.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:168) [azo.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466) [axu.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:176) [azo.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554) [axu.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.func_146274_d(SourceFile:77) [azo.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523) [axu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) [ave.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

Removing our textures stops the issue from preventing. But seems like it's not liking "higher" res textures?

Before the error above is posted Forge logs this not sure if it's releated or not:
`[Client thread/INFO] [FML]: Max texture size: 16384`

Other mod versions:
- Forge: 11.15.1.1766
- Mantle: 1.8.9-0.8.2

**Comment by artdude543** [comment]
Thank you! :)
