### ISSUE TITLE
An Unexpected Crash

### ISSUE THREAD

**Issue by ThePhisics101** [SlimeKnights/TinkersConstruct#1940]
I don't know if it actually is tinkers' fault

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.0.5.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-0.3.0.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 3/4/16 7:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/event/FMLInitializationEvent
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/event/FMLInitializationEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:533)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.event.FMLInitializationEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 896566648 bytes (855 MB) / 1076363264 bytes (1026 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UC	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UC	bowinfinityfix{rv2} [Bow Infinity Fix] (minecraft.jar) 
	UC	<CCTweaks ASM>{0.3.0.2} [<CCTweaks ASM>] (minecraft.jar) 
	UC	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UC	aura{592} [Aura Cascade] (AuraCascade-592.jar) 
	UC	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UC	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1926-universal.jar) 
	UC	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UC	CCTweaks{0.3.0.2} [CCTweaks] (CCTweaks-1.8.9-0.3.0.2.jar) 
	UC	mcmultipart{1.0.7} [MCMultiPart] (MCMultiPart-1.0.7-universal.jar) 
	UC	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UC	ComputerCraftEdu{1.79pr1} [ComputerCraftEdu] (ComputerCraftEdu1.79pr1.jar) 
	UC	ElecCore{1.5} [ElecCore] (ElecCore-1.8.9-1.4.234.jar) 
	UC	deepresonance{1.1.4beta7} [DeepResonance] (deepresonance-1.8.9-1.1.4beta7.jar) 
	UC	Ding{MC1.8.9v2} [Ding] (Ding-MC1.8.9v2.jar) 
	UC	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UC	reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
	UC	fluxedredstone{1.3.0.31} [FluxedRedstone] (Fluxed Redstone-1.3.0.31.jar) 
	UC	fluxedsolars{$GRADLEVERSION} [Fluxed Solars] (fluxedsolars-1.9.jar) 
	UC	Harvest{1.8.9-1.0.0-2} [Harvest] (Harvest-1.8.9-1.0.0-2.jar) 
	UC	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UC	HydCraft{1.8.9-3.1.65} [Hydraulicraft] (HydCraft-1.8.9-3.1.65-universal.jar) 
	UC	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UC	InventoryCenterer{1.8.9-0.1.1} [Inventory Centerer] (InventoryCenterer-1.8.9-0.1.1.jar) 
	UC	inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
	UC	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UC	JEI{2.28.6.173} [Just Enough Items] (jei_1.8.9-2.28.6.173.jar) 
	UC	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UC	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UC	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UC	malisiscore{1.8.9-2.0.5} [MalisisCore] (malisiscore-1.8.9-2.0.5.jar) 
	UC	malisisswitches{1.8.9-1.0.1} [Malisis Switches] (malisisswitches-1.8.9-1.0.1.jar) 
	UC	mantle{1.8.9-0.8.2.jenkins95} [Mantle] (Mantle-1.8.9-0.8.2.jar) 
	UC	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UE	numina{0.4.0.131.jar} [Numina] (ModularPowersuits-1.8.9-0.0.1-1.jar) 
	UE	powersuits{1.0} [powersuits] (ModularPowersuits-1.8.9-0.0.1-1.jar) 
	UC	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
	UC	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UC	Psi{beta-19} [Psi] (Psi-beta-19.jar) 
	UC	quantumflux{2.0.0} [QuantumFlux] (quantumflux-1.8.9-2.0.0.jar) 
	UC	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UC	rftools{4.22beta28} [RFTools] (rftools-1.8.9-4.22beta28.jar) 
	UC	rftoolsdim{4.22beta25} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta25.jar) 
	UC	simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
	UC	storagesilo{1.2.2} [StorageSilo] (storagesilo-1.8.9-1.2.2b.jar) 
	UC	substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
	UC	SuperMultiDrills{1.3.0-beta3} [Super Multi-Drills] (SuperMultiDrills-1.8.9-1.3.0-beta3-25.jar) 
	UC	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UC	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UC	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	Loaded coremods (and transformers): 
CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  
MalisisCorePlugin (malisiscore-1.8.9-2.0.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  com.github.parker8283.bif.Transformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
TweaksLoadingPlugin (CCTweaks-1.8.9-0.3.0.2.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GT 430/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

**Comment by bonii-xx** [comment]
No.
