### ISSUE TITLE
TinkersConstruct bug - version 1.8.9-2.2.0b

### ISSUE THREAD

**Issue by dafireflame** [SlimeKnights/TinkersConstruct#1954]
While using the Minecraft Curse client i updated to this version and upon loading up it crashes, i then removed TinkersConstruct from my mod list and it loaded up fine.

this was the crash report i was given:

_______________________________________________________________________________
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  BiomeTweakerCore (BiomeTweaker-1.8.9-2.0.184.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 18/03/16 4:34 PM
Description: Initializing game

java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
	... 33 more
Caused by: java.lang.NullPointerException
	at net.minecraft.client.resources.model.ModelBakery.registerItemVariants(ModelBakery.java:759)
	at slimeknights.tconstruct.shared.FluidsClientProxy.registerFluidModels(FluidsClientProxy.java:45)
	at slimeknights.tconstruct.shared.FluidsClientProxy.registerModels(FluidsClientProxy.java:28)
	at slimeknights.tconstruct.common.CommonProxy.preInit(CommonProxy.java:27)
	at slimeknights.tconstruct.shared.TinkerFluids.preInit(TinkerFluids.java:236)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1146491888 bytes (1093 MB) / 1456472064 bytes (1389 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 29 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCH	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCH	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCH	BBG{3.0.0} [BetterBedrockGen] (BBG-3.0.0.jar) 
	UCH	BiomeTweaker{2.0.184} [BiomeTweaker] (BiomeTweaker-1.8.9-2.0.184.jar) 
	UCH	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1927-universal.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.1.jar) 
	UCH	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCH	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCH	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCH	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCH	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCH	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCH	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCH	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCH	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCH	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCH	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCH	mantle{1.8.9-0.9.1.jenkins99} [Mantle] (Mantle-1.8.9-0.9.1.jar) 
	UCH	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCH	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UC	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UC	VeinMiner{0.31.4_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.4.unknown.jar) 
	UC	VeinMinerModSupport{0.31.4_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.4.unknown.jar) 
	UC	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UC	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.6.jar) 
	UC	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.2.jar) 
	UD	BiomeTweakerCore{2.0.184} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
BiomeTweakerCore (BiomeTweaker-1.8.9-2.0.184.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.3.0' Renderer: 'GeForce GT 630/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Launched Version: forge-11.15.1.1764
	LWJGL: 2.9.4
	OpenGL: GeForce GT 630/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4100 Quad-Core Processor 
_____________________________________________________________________________

hope this was helpful.

**Comment by bonii-xx** [comment]
I need to know which other mod causes this.

**Comment by laz2727** [comment]
Try to remove other mods one by one. There's something weird with
ModelBakery, but it shouldn't *crash*.

2016-03-18 20:21 GMT+05:00 boni <notifications@github.com>:

**Comment by dafireflame** [comment]
i tried again after a few mods updated (Biomes O' Plenty and one other) but the outcome was the same. Also going through the list of mods i could disable, some of those mods would trigger another mod off at the same time which prevented me from being able to single out the other mod to cause the issue. However one of the simultaneous disabling's included Mantle which immediately also disabled TinkersConstruct. I also believe that that mod was one of the mods i updated along with TinkersConstruct yesterday before i discovered the problem.

Upon writing this i tried to just have mantle and TinkersConsruct load up by themselves and the same crash occurred.

**Comment by rckymtnrfc** [comment]
Check your TinkerModules.cfg in the config folder.  Mine had an extra line in it that doesn't appear when I delete it and let it regenerate the file.

B:TinkerMaterials=true

With that removed, no more crash.

**Comment by bonii-xx** [comment]
That line shouldn't have any impact. But maybe you had some other things disabled?

**Comment by bonii-xx** [comment]
@dafireflame please post your tconstruct.cfg, tinkermodels.cfg and the full log

**Comment by dafireflame** [comment]
i did that and that fixed it. although i had not edited those modules before hand so is it possible that that was set as the default?

**Comment by bonii-xx** [comment]
You probably had an old config file from before the smeltery was implemented. It was disabled there.

It shouldn't happen either way, but that's an issue with a library TCon uses so I can't fix it directly.

**Comment by homemmakako** [comment]
Hi, I was having the same problem with the latest versions of Tcon and mantle even with the smeltery module turned on. In fact the only thing that solved it was turning it off. After some experimentation I found out that what was causing this was the mod techReborn. I think it was because of a tinkers compatibility configuration that was tuned off in the techReborn config file, but can't confirm that. What I can confirm is that deleting the TR config file solved the problem. Just wanted to post here so if anyone is having the same problem even with the smeltery config turned on and happens to find this issue, TechReborn's config might be the problem

**Comment by Redlotus99** [comment]
I got an error very similar and tracked it down to Surge. I removed Surge and the issue was resolved.

**Comment by KnightMiner** [comment]
No, you do not have the same bug. You have a crash during init with a mod that uses Mantle, which all start the same. Report to Natura and they can resolve it.
