### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by SpaneBoswell** [SlimeKnights/TinkersConstruct#1977]
NOTE : This may not be your mod that is causing the problem but it might be
Anyways starting today forge crashed always during Pre-Intialization phase
I do not know why and I am not a tech genious but I know a little but not enough to understand
my issue. So I have pasted the crash log right below
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.8.9-1.4.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  LucraftForgeLoading (LucraftCore-1.8.9-1.0.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 3/26/16 2:01 PM
Description: Initializing game

java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	at lumien.custommainmenu.configuration.GuiConfig.loadLabels(GuiConfig.java:306)
	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:105)
	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:95)
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:66)
	... 36 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2483744688 bytes (2368 MB) / 2826436608 bytes (2695 MB) up to 11810111488 bytes (11263 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -Xmn3076M -Xms3076M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1794 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1794.jar) 
	UCH	Forge{11.15.1.1794} [Minecraft Forge] (forge-1.8.9-11.15.1.1794.jar) 
	UCH	AntMan{Pre-1.8.9-1.0.0} [AntMan] (AntMan-Pre-1.8.9-1.0.0.jar) 
	UCH	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCH	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1927-universal.jar) 
	UCH	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCH	buildingbrickscompatvanilla{1.8.9-1.4.2} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.4.2.jar) 
	UCH	buildingbricks{1.8.9-1.4.2} [Building Bricks] (BuildingBricks-1.8.9-1.4.2.jar) 
	UCH	cfm{3.6} [MrCrayfish's Furniture Mod] (cfm-3.6.1-mc1.8.9.jar) 
	UCH	cfmce{1.0.1} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0.1-mc1.8.9.jar) 
	UCH	Chameleon{1.8.9-1.0.0} [Chameleon] (Chameleon-1.8.9-1.0.0.jar) 
	UCH	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCH	chiselsandbits{8.6} [Chisels & Bits] (chiselsandbits-8.6.jar) 
	UCE	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCH	golems{2.5.01} [Extra Golems] (Extra-Golems[1.8.9]-2.5.01.jar) 
	UCH	flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8 (1).jar) 
	UCH	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCH	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCH	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCH	gemsplus{1.6.4} [Gems+] (gemsplus-1.6.4-mc1.8.8.jar) 
	UCH	InventoryPets{1.3.91} [Inventory Pets] (inventorypets-1.8.9-1.3.91.jar) 
	UCH	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCH	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCH	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCH	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCH	launchgui{1.8.8-2.0.1-19} [LaunchGUI] (LaunchGui-1.8.8-2.0.1-19-client.jar) 
	UCH	LucraftCore{1.8.9-1.0.0} [Lucraft: Core] (LucraftCore-1.8.9-1.0.0.jar) 
	UCH	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCH	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
	UCH	MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar) 
	UCH	moarsigns{2.0.0} [MoarSigns] (MoarSigns-1.8.9-2.0.0.jar) 
	UCH	oceancraft{1.5.3} [Oceancraft] (Oceancraft v1.5.3 (MC 1.8.9).jar) 
	UCH	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.9-1.4.jar) 
	UCH	smf{1.0} [Scarab's Missing Furniture Mod] (smf-1.0.jar) 
	UCH	StorageDrawers{1.8.9-2.5.0} [Storage Drawers] (StorageDrawers-1.8.9-2.5.0.jar) 
	UCH	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UCH	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.8.9-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
LucraftForgeLoading (LucraftCore-1.8.9-1.0.0.jar)
  lucraft.mods.lucraftcore.access.LucraftClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4352' Renderer: 'Intel(R) HD Graphics 4600'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.8.9-forge1.8.9-11.15.1.1794
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4352, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700k CPU @ 4.20GHz

**Comment by SpaneBoswell** [comment]
EDIT: Removing all mods causes no issue during startup

**Comment by bonii-xx** [comment]
CustomMainMenu is at fault, your main menu json is broken. Or just remove it.

**Comment by SpaneBoswell** [comment]
OMG! Thank you also thank you for fixing it way quicker than I thought.
