### ISSUE TITLE
Crash when using buildcraft pipes on a Tinkers Construct crafting table

### ISSUE THREAD

**Issue by Ideki** [SlimeKnights/TinkersConstruct#1979]
I have Buildcraft 7.2.3 and Tinkers Construct 1.8-9-2.2.0b
 I wanted to make a power output pipe (wooden pipe + redstone)
 As soon I put the wooden pipe on the TConstuct crafting table, the game crashed and I got the following error. (And now I cannot load that world anymore...)

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/27/16 11:23 AM
Description: Tesselating block in world

java.lang.ArrayIndexOutOfBoundsException: 3
	at javax.vecmath.Tuple4f.<init>(Tuple4f.java:91)
	at javax.vecmath.Vector4f.<init>(Vector4f.java:65)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.put(TRSRBakedModel.java:146)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:60)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:75)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:136)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:95)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:905)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at javax.vecmath.Tuple4f.<init>(Tuple4f.java:91)
	at javax.vecmath.Vector4f.<init>(Vector4f.java:65)
	at slimeknights.mantle.client.model.TRSRBakedModel$Transformer.put(TRSRBakedModel.java:146)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:60)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:75)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:42)
	at slimeknights.mantle.client.model.TRSRBakedModel.<init>(TRSRBakedModel.java:38)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:136)
	at slimeknights.tconstruct.shared.client.BakedTableModel.handleBlockState(BakedTableModel.java:95)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152)

-- Block being tesselated --
Details:
	Block type: ID #226 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.block.BlockToolTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-263,63,110), Chunk: (at 9,3,14 in -17,6; contains blocks -272,0,96 to -257,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:905)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ideki'/1556, l='MpServer', x=-261.51, y=63.00, z=110.60]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 03 - amplified, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -172.00,64.00,232.00 - World: (-172,64,232), Chunk: (at 4,4,8 in -11,14; contains blocks -176,0,224 to -161,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1027880 game time, 1093991 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntityZombie['Zombie'/1292, l='MpServer', x=-261.50, y=30.00, z=123.06], EntityZombie['Zombie'/1293, l='MpServer', x=-264.50, y=37.00, z=124.50], EntityPig['Pig'/1294, l='MpServer', x=-267.94, y=63.00, z=123.06], EntityCow['Cow'/1295, l='MpServer', x=-259.16, y=63.00, z=122.84], EntityPig['Pig'/1296, l='MpServer', x=-267.34, y=63.00, z=126.81], EntityBat['Bat'/1297, l='MpServer', x=-260.63, y=47.10, z=135.38], EntityCow['Cow'/1298, l='MpServer', x=-258.94, y=63.00, z=128.59], EntityCow['Cow'/1299, l='MpServer', x=-256.72, y=63.00, z=129.66], EntityPlayerSP['Ideki'/1556, l='MpServer', x=-261.51, y=63.00, z=110.60], EntitySquid['Squid'/1310, l='MpServer', x=-239.78, y=62.38, z=58.13], EntitySquid['Squid'/1311, l='MpServer', x=-244.13, y=62.41, z=68.32], EntityZombie['Bold Zombie'/1312, l='MpServer', x=-243.78, y=18.00, z=110.31], EntityBat['Bat'/1313, l='MpServer', x=-239.03, y=37.81, z=106.41], EntityChicken['Chicken'/1314, l='MpServer', x=-241.50, y=74.00, z=103.78], EntityItem['item.item.egg'/1315, l='MpServer', x=-241.13, y=74.00, z=103.41], EntityBat['Bat'/1316, l='MpServer', x=-254.50, y=35.38, z=126.94], EntityCow['Cow'/1317, l='MpServer', x=-254.94, y=63.00, z=123.06], EntityCow['Cow'/1318, l='MpServer', x=-254.41, y=63.00, z=124.06], EntityCow['Cow'/1319, l='MpServer', x=-255.03, y=63.00, z=128.94], EntityMechanicalArm['entity.BuildCraft|Builders.bcMechArm.name'/1705, l='MpServer', x=-210.00, y=34.00, z=110.00], EntitySquid['Squid'/1341, l='MpServer', x=-240.64, y=62.16, z=70.20], EntitySquid['Squid'/1342, l='MpServer', x=-238.55, y=61.00, z=73.61], EntityPig['Pig'/1343, l='MpServer', x=-234.47, y=63.00, z=88.94], EntityCreeper['Creeper'/1344, l='MpServer', x=-238.03, y=72.00, z=109.50], EntityBat['Bat'/1345, l='MpServer', x=-235.25, y=22.91, z=120.25], EntityChicken['Chicken'/1346, l='MpServer', x=-234.25, y=63.31, z=116.31], EntityChicken['Chicken'/1347, l='MpServer', x=-234.84, y=63.78, z=116.19], EntityChicken['Chicken'/1348, l='MpServer', x=-234.91, y=63.53, z=116.81], EntityChicken['Chicken'/1349, l='MpServer', x=-234.53, y=107.00, z=172.59], EntityCow['Cow'/1350, l='MpServer', x=-225.44, y=110.00, z=166.19], EntityChicken['Chicken'/1228, l='MpServer', x=-220.53, y=104.00, z=107.78], EntityCreeper['Creeper'/1358, l='MpServer', x=-208.50, y=23.00, z=137.50], EntitySkeleton['Vampiric Skeleton'/1367, l='MpServer', x=-196.50, y=73.00, z=50.13], EntityCreeper['Creeper'/1368, l='MpServer', x=-195.72, y=84.00, z=72.25], EntityBat['Bat'/1240, l='MpServer', x=-340.72, y=48.00, z=45.53], EntityChicken['Chicken'/1369, l='MpServer', x=-194.63, y=137.00, z=132.50], EntityZombie['Zombie'/1241, l='MpServer', x=-340.41, y=44.00, z=98.00], EntityChicken['Chicken'/1370, l='MpServer', x=-198.34, y=165.00, z=135.28], EntitySheep['Sheep'/1242, l='MpServer', x=-338.41, y=226.00, z=167.41], EntityChicken['Chicken'/1371, l='MpServer', x=-189.22, y=170.16, z=186.50], EntityChicken['Chicken'/1384, l='MpServer', x=-186.66, y=83.00, z=69.09], EntityChicken['Chicken'/1385, l='MpServer', x=-184.47, y=130.00, z=129.50], EntityBat['Bat'/1258, l='MpServer', x=-329.47, y=25.53, z=32.84], EntityChicken['Chicken'/1386, l='MpServer', x=-185.03, y=140.00, z=123.84], EntityCreeper['Creeper'/1259, l='MpServer', x=-325.50, y=126.00, z=120.50], EntityCreeper['Creeper'/1390, l='MpServer', x=-189.50, y=115.00, z=183.50], EntitySheep['Sheep'/1264, l='MpServer', x=-297.69, y=84.00, z=42.09], EntitySheep['Sheep'/1265, l='MpServer', x=-300.47, y=85.00, z=51.66], EntityChicken['Chicken'/1266, l='MpServer', x=-288.31, y=84.00, z=120.59], EntityItem['item.item.egg'/1267, l='MpServer', x=-288.47, y=84.00, z=120.25], EntityChicken['Chicken'/1268, l='MpServer', x=-295.66, y=111.00, z=125.31], EntitySheep['Sheep'/1275, l='MpServer', x=-274.97, y=86.00, z=34.00], EntitySpider['Spider'/1276, l='MpServer', x=-282.50, y=86.00, z=47.50], EntitySquid['Squid'/1277, l='MpServer', x=-281.19, y=62.44, z=104.57], EntitySheep['Sheep'/1278, l='MpServer', x=-276.94, y=63.00, z=123.06], EntitySheep['Sheep'/1279, l='MpServer', x=-272.59, y=63.00, z=124.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1462348816 bytes (1394 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 5, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.3} [BuildCraft] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.3} [BC Builders] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.3} [BC Transport] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.3} [BC Energy] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.3} [BC Silicon] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.3} [BC Robotics] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.3} [BC Factory] (buildcraft-7.2.3.jar) 
	UCHIJAAAA	exnihilo2{0.28} [Ex Nihilo 2] (ExNihilo2-0.28.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.1.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.1.jenkins99} [Mantle] (Mantle-1.8.9-0.9.1.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.8.9-forge1.8.9-11.15.1.1764
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz

**Comment by TherminatorX** [comment]
To fix, open the world in MCEdit and remove the pipe.

And don't try to automate crafting with the CStation, bad times will be had.

**Comment by Ideki** [comment]
I did not try to automate crafting.
I just wanted to make a power output pipe from Buildcraft.

According to them, you are not handling properly the pipe model rendering on top of the crafting table.
And you do not catch that exception that causes the index out of bound exception.

So while MCEditing the pipe out would probably fix the world, it will not fix the problem you have in your code when you do not check that the index is within the boundaries of your array.

I would be very thankful if you could fix that exception in your code so I do not have to do an MCedit my world.

**Comment by TherminatorX** [comment]
@Ideki I was confused by your report, my bad.

**Comment by Ideki** [comment]
no problem. :)
Now I just have to wait for a fix.

**Comment by bonii-xx** [comment]
Update mantle.

**Comment by Ideki** [comment]
I confirm that latest version of mantle fixes the issue.
I can load my world and make the Buildcraft pipes without problems.
Thanks a lot :)
