### ISSUE TITLE
Hey its me Again!

### ISSUE THREAD

**Issue by SpaneBoswell** [SlimeKnights/TinkersConstruct#2000]
I am really sorry. Anyways recently I created an issue here that was not yours but the same things happened again crashing but it is not the mod because it is not there(Captain Obvious). Anyways it crashes before the program does not even open. Also if you have any tips for me to find out what is happening in the crash log please let me know. Also I love your mod it is awesome keep up the great work!
2016-04-05 20:22:10,154 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-04-05 20:22:10,157 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[20:22:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:22:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:22:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:22:10] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1808 for Minecraft 1.8.9 loading
[20:22:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
2016-04-05 20:22:10,565 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-04-05 20:22:10,596 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-04-05 20:22:10,599 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[20:22:10] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:22:11] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:22:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:22:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:22:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:22:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:22:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:22:15] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:22:15] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:22:16] [main/INFO] [Bookshelf]: Starting to apply transformations
[20:22:16] [main/INFO] [Bookshelf]: Starting to apply transformations
[20:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:22:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[20:22:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[20:22:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[20:22:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[20:22:16] [main/INFO] [malisiscore]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[20:22:16] [main/INFO] [malisiscore]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockRendererDispatcher
[20:22:16] [main/INFO] [malisiscore]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.entity.RenderItem
[20:22:16] [main/INFO] [malisiscore]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockModelShapes
[20:22:16] [main/INFO] [malisiscore]: [TextureMapTransformer] Hook registered for net.minecraft.client.renderer.texture.TextureMap
[20:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:22:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:22:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:22:16] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@389562d6 from coremod AppleCore
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.8.9-11.15.1.1808.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: Unexpected instruction pattern encountered in drawHoveringText
	at squeek.applecore.asm.module.ModuleDrawTooltip.addDrawHoveringTextHook(ModuleDrawTooltip.java:69) ~[AppleCore-mc1.8.9-1.3.0.jar:?]
	at squeek.applecore.asm.module.ModuleDrawTooltip.transform(ModuleDrawTooltip.java:33) ~[AppleCore-mc1.8.9-1.3.0.jar:?]
	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:40) ~[AppleCore-mc1.8.9-1.3.0.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8.9-11.15.1.1808.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Exception in thread "main" [20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ryanjo1982** [comment]
It looks as if Malisis Core and Apple Core are what is causing your problem. Try removing them and see which one is causing the problem by adding them one at a time. Then post the log file to their github/forum.

**Comment by SpaneBoswell** [comment]
Thanks a lot!
