### ISSUE TITLE
Putting in invalid block will crash client.

### ISSUE THREAD

**Issue by shortybsd** [SlimeKnights/TinkersConstruct#2013]
MC version 1.9
Forge version 1.9-12.16.0.1862
TinkersConstruct version TConstruct-1.9-2.2.2

(I know you shouldn't put blocks of this type in)
If you attempt to put a chiseled stone block into the smeltry your client will crash and will no longer be able to join the world. Every time you join the world the block will still be in the smeltry, leading to the same client crash. Here is the crash:

Time: 4/13/16 6:37 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at team.chisel.client.render.ModelChiselBlock.handlePerspective(ModelChiselBlock.java:169)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:369)
	at slimeknights.tconstruct.smeltery.client.SmelteryRenderer.renderTileEntityAt(SmelteryRenderer.java:105)
	at slimeknights.tconstruct.smeltery.client.SmelteryRenderer.func_180535_a(SmelteryRenderer.java:23)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:140)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:118)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:696)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at team.chisel.client.render.ModelChiselBlock.handlePerspective(ModelChiselBlock.java:169)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:369)
	at slimeknights.tconstruct.smeltery.client.SmelteryRenderer.renderTileEntityAt(SmelteryRenderer.java:105)
	at slimeknights.tconstruct.smeltery.client.SmelteryRenderer.func_180535_a(SmelteryRenderer.java:23)

-- Block Entity Details --
Details:
	Name: tconstruct.smeltery_controller // slimeknights.tconstruct.smeltery.tileentity.TileSmeltery
	Block type: ID #695 (tile.tconstruct.smeltery_controller // slimeknights.tconstruct.smeltery.block.BlockSmelteryController)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-319,44,1125), Chunk: (at 1,2,5 in -20,70; contains blocks -320,0,1120 to -305,255,1135), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Actual block type: ID #695 (tile.tconstruct.smeltery_controller // slimeknights.tconstruct.smeltery.block.BlockSmelteryController)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:140)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:118)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:696)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

**Comment by bonii-xx** [comment]
Calling @tterrag1098 to investigate whether a parameter is missing or you got a derp.
