### ISSUE TITLE
Liquid in casting table causes crash.

### ISSUE THREAD

**Issue by Fisher28** [SlimeKnights/TinkersConstruct#2015]
EDIT: Hoping this is the right place to put it, I'm completely new to this site.
So, today I was just testing out the 1.9 version of Tinkers Construct, and I, being the crazy self I am, decided to put a liquid (not a bucket of liquid, the raw item) from the creative menu into the casting table. Everything disappeared on screen, and Minecraft crashed. I've made repeated attempts at rejoining the world, but as soon as stuff begins to render on screen, the same thing happens. Here's the crash report: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/14/16 9:34 AM
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get unlisted property net.minecraftforge.common.property.PropertyFloat@7f68e671 as it does not exist in ExtendedBlockState{block=tconstruct:casting, properties=[type]}
	at net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.getValue(ExtendedBlockState.java:129)
	at net.minecraftforge.client.model.ModelFluid$BakedFluid.getCorners(ModelFluid.java:144)
	at net.minecraftforge.client.model.ModelFluid$BakedFluid.func_188616_a(ModelFluid.java:356)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.mantle.client.model.BakedCompositeModel.func_188616_a(BakedCompositeModel.java:30)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.tconstruct.shared.client.BakedTableModel.func_188616_a(BakedTableModel.java:146)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:98)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:84)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:45)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:36)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:196)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:99)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:140)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:949)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.getValue(ExtendedBlockState.java:129)
	at net.minecraftforge.client.model.ModelFluid$BakedFluid.getCorners(ModelFluid.java:144)
	at net.minecraftforge.client.model.ModelFluid$BakedFluid.func_188616_a(ModelFluid.java:356)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.mantle.client.model.BakedCompositeModel.func_188616_a(BakedCompositeModel.java:30)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.tconstruct.shared.client.BakedTableModel.func_188616_a(BakedTableModel.java:146)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:98)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:84)

-- Block model being tesselated --
Details:
	Block: tconstruct:casting[type=table]
	Block location: World: (327,70,271), Chunk: (at 7,4,15 in 20,16; contains blocks 320,0,256 to 335,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:45)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:36)

-- Block being tesselated --
Details:
	Block type: ID #237 (tile.tconstruct.casting // slimeknights.tconstruct.smeltery.block.BlockCasting)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (327,70,271), Chunk: (at 7,4,15 in 20,16; contains blocks 320,0,256 to 335,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:196)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:99)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:140)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:949)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Fisher28000000'/239, l='MpServer', x=327.26, y=70.00, z=270.16]]
	Chunk stats: MultiplayerChunkCache: 1071, 1071
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (144,64,256), Chunk: (at 0,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 63864 game time, 63864 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 121 total; [EntityCreeper['Creeper'/279, l='MpServer', x=352.50, y=65.00, z=232.50], EntityCreeper['Creeper'/280, l='MpServer', x=354.08, y=55.00, z=270.00], EntitySkeleton['Skeleton'/281, l='MpServer', x=356.72, y=55.00, z=263.53], EntitySheep['Sheep'/282, l='MpServer', x=366.43, y=70.00, z=266.82], EntityBat['Bat'/283, l='MpServer', x=352.80, y=55.10, z=275.69], EntityEnderman['Enderman'/284, l='MpServer', x=352.46, y=53.00, z=276.55], EntityZombie['Zombie'/285, l='MpServer', x=364.25, y=70.00, z=273.64], EntityCreeper['Creeper'/286, l='MpServer', x=366.16, y=70.00, z=280.47], EntityPig['Pig'/289, l='MpServer', x=370.47, y=64.00, z=349.68], EntityBat['Bat'/292, l='MpServer', x=375.53, y=44.64, z=204.41], EntityCreeper['Creeper'/293, l='MpServer', x=370.21, y=66.00, z=195.33], EntityZombie['Zombie'/294, l='MpServer', x=383.50, y=28.00, z=222.50], EntityZombie['Zombie'/295, l='MpServer', x=378.35, y=67.00, z=217.35], EntitySkeleton['Skeleton'/296, l='MpServer', x=371.50, y=32.00, z=234.50], EntityZombie['Zombie'/297, l='MpServer', x=383.50, y=45.00, z=250.50], EntityBat['Bat'/298, l='MpServer', x=378.91, y=26.89, z=256.10], EntityCreeper['Creeper'/299, l='MpServer', x=369.19, y=70.00, z=257.49], EntitySheep['Sheep'/300, l='MpServer', x=372.27, y=69.00, z=285.54], EntitySpider['Spider'/301, l='MpServer', x=375.50, y=40.00, z=312.50], EntityBat['Bat'/302, l='MpServer', x=383.04, y=18.05, z=348.48], EntitySkeleton['Skeleton'/308, l='MpServer', x=391.50, y=38.00, z=192.50], EntityZombie['Zombie'/309, l='MpServer', x=392.50, y=35.00, z=210.50], EntityPig['Pig'/310, l='MpServer', x=387.54, y=68.00, z=219.25], EntityPig['Pig'/311, l='MpServer', x=387.50, y=68.00, z=232.50], EntityPig['Pig'/312, l='MpServer', x=388.50, y=68.00, z=233.50], EntityPig['Pig'/313, l='MpServer', x=390.27, y=68.00, z=225.55], EntityCreeper['Creeper'/314, l='MpServer', x=389.50, y=68.00, z=237.50], EntitySkeleton['Skeleton'/315, l='MpServer', x=387.78, y=69.00, z=253.34], EntityCreeper['Creeper'/316, l='MpServer', x=386.50, y=70.00, z=277.50], EntityCreeper['Creeper'/317, l='MpServer', x=388.50, y=63.00, z=303.50], EntityPig['Pig'/328, l='MpServer', x=406.01, y=68.00, z=231.05], EntityPig['Pig'/329, l='MpServer', x=401.50, y=68.00, z=232.50], EntitySkeleton['Skeleton'/331, l='MpServer', x=405.50, y=17.00, z=252.50], EntityPig['Pig'/336, l='MpServer', x=404.47, y=70.00, z=270.73], EntitySpider['Spider'/337, l='MpServer', x=403.99, y=68.00, z=312.56], EntityCreeper['Creeper'/125, l='MpServer', x=253.50, y=27.00, z=219.50], EntityCreeper['Creeper'/128, l='MpServer', x=251.50, y=28.00, z=226.50], EntityZombie['Zombie'/129, l='MpServer', x=248.74, y=73.00, z=257.54], EntityCow['Cow'/131, l='MpServer', x=250.21, y=78.00, z=279.50], EntityCow['Cow'/132, l='MpServer', x=249.21, y=71.00, z=294.49], EntityCow['Cow'/133, l='MpServer', x=248.62, y=80.00, z=285.84], EntitySpider['Spider'/142, l='MpServer', x=269.50, y=90.00, z=194.50], EntitySkeleton['Skeleton'/143, l='MpServer', x=259.50, y=88.00, z=213.26], EntityCreeper['Creeper'/144, l='MpServer', x=256.83, y=76.00, z=253.48], EntityPig['Pig'/145, l='MpServer', x=271.27, y=78.00, z=281.46], EntityPig['Pig'/146, l='MpServer', x=258.74, y=80.00, z=285.55], EntityZombie['Zombie'/147, l='MpServer', x=257.30, y=79.00, z=300.70], EntityPig['Pig'/148, l='MpServer', x=264.55, y=80.00, z=298.98], EntityPig['Pig'/149, l='MpServer', x=265.90, y=80.00, z=289.37], EntitySpider['Spider'/150, l='MpServer', x=260.05, y=80.00, z=300.95], EntityPig['Pig'/151, l='MpServer', x=265.41, y=68.00, z=327.21], EntityPig['Pig'/152, l='MpServer', x=258.50, y=68.00, z=326.50], EntityPig['Pig'/153, l='MpServer', x=264.78, y=68.00, z=326.26], EntityPig['Pig'/154, l='MpServer', x=260.10, y=68.00, z=326.10], EntityCreeper['Creeper'/155, l='MpServer', x=269.50, y=68.00, z=326.50], EntityCreeper['Creeper'/157, l='MpServer', x=273.19, y=89.00, z=190.52], EntityZombie['Zombie'/158, l='MpServer', x=274.49, y=84.00, z=227.20], EntitySheep['Sheep'/159, l='MpServer', x=280.44, y=74.00, z=270.79], EntitySheep['Sheep'/160, l='MpServer', x=274.81, y=75.00, z=268.79], EntitySheep['Sheep'/161, l='MpServer', x=276.82, y=75.00, z=288.56], EntityZombie['Zombie'/162, l='MpServer', x=282.77, y=50.00, z=311.55], EntityCreeper['Creeper'/164, l='MpServer', x=303.50, y=27.00, z=192.50], EntityCow['Cow'/165, l='MpServer', x=301.69, y=73.00, z=230.85], EntityCow['Cow'/166, l='MpServer', x=288.63, y=73.00, z=243.83], EntityCow['Cow'/167, l='MpServer', x=293.50, y=71.00, z=251.50], EntityCow['Cow'/168, l='MpServer', x=297.46, y=73.00, z=244.81], EntityCow['Cow'/169, l='MpServer', x=301.45, y=72.00, z=242.45], EntityCow['Cow'/170, l='MpServer', x=290.58, y=73.00, z=241.85], EntityPig['Pig'/171, l='MpServer', x=296.49, y=73.00, z=244.64], EntityCreeper['Creeper'/172, l='MpServer', x=298.50, y=73.00, z=246.50], EntitySheep['Sheep'/173, l='MpServer', x=289.49, y=73.00, z=268.74], EntityBat['Bat'/174, l='MpServer', x=304.40, y=29.28, z=280.25], EntityPlayerSP['Fisher28000000'/239, l='MpServer', x=327.26, y=70.00, z=270.16], EntitySheep['Sheep'/175, l='MpServer', x=289.49, y=72.00, z=278.79], EntityPig['Pig'/176, l='MpServer', x=298.78, y=68.00, z=304.33], EntitySkeleton['Skeleton'/177, l='MpServer', x=288.50, y=36.00, z=320.50], EntityCow['Cow'/182, l='MpServer', x=319.47, y=70.00, z=190.85], EntityCow['Cow'/183, l='MpServer', x=314.45, y=69.00, z=192.72], EntityCow['Cow'/184, l='MpServer', x=312.89, y=68.00, z=195.49], EntityPig['Pig'/186, l='MpServer', x=308.80, y=72.00, z=238.67], EntityCow['Cow'/187, l='MpServer', x=318.46, y=71.00, z=237.82], EntityBat['Bat'/188, l='MpServer', x=334.83, y=41.13, z=271.94], EntityCreeper['Creeper'/189, l='MpServer', x=315.51, y=58.00, z=283.22], EntitySkeleton['Skeleton'/190, l='MpServer', x=317.55, y=52.00, z=299.28], EntityItem['item.item.slimeball'/191, l='MpServer', x=311.57, y=22.00, z=313.13], EntityItem['item.item.slimeball'/192, l='MpServer', x=311.75, y=22.00, z=314.13], EntityBat['Bat'/194, l='MpServer', x=304.25, y=24.03, z=195.53], EntityCreeper['Creeper'/195, l='MpServer', x=330.50, y=21.00, z=211.50], EntityPig['Pig'/196, l='MpServer', x=334.26, y=70.00, z=216.45], EntitySheep['Sheep'/197, l='MpServer', x=324.58, y=70.00, z=249.23], EntityBat['Bat'/198, l='MpServer', x=332.25, y=39.10, z=271.25], EntityItem['item.item.string'/199, l='MpServer', x=330.30, y=70.00, z=271.84], EntityCreeper['Creeper'/200, l='MpServer', x=333.50, y=46.00, z=273.50], EntitySkeleton['Skeleton'/201, l='MpServer', x=331.50, y=46.00, z=272.50], EntityBat['Bat'/202, l='MpServer', x=335.10, y=40.10, z=279.70], EntityBat['Bat'/203, l='MpServer', x=332.84, y=41.10, z=274.25], EntityBat['Bat'/204, l='MpServer', x=319.52, y=35.23, z=280.17], EntityBat['Bat'/205, l='MpServer', x=324.30, y=38.79, z=279.46], EntityCreeper['Creeper'/206, l='MpServer', x=316.79, y=58.00, z=283.48], EntityBlueSlime['Blue Slime'/207, l='MpServer', x=320.91, y=69.00, z=298.38], EntitySkeleton['Skeleton'/208, l='MpServer', x=331.67, y=68.00, z=317.48], EntityBat['Bat'/213, l='MpServer', x=349.53, y=44.10, z=193.75], EntityPig['Pig'/214, l='MpServer', x=343.22, y=69.00, z=213.30], EntityPig['Pig'/215, l='MpServer', x=341.50, y=69.00, z=206.27], EntitySkeleton['Skeleton'/216, l='MpServer', x=347.50, y=17.00, z=215.50], EntityPig['Pig'/217, l='MpServer', x=338.48, y=69.00, z=208.55], EntityCow['Cow'/218, l='MpServer', x=343.31, y=70.00, z=234.88], EntityCow['Cow'/219, l='MpServer', x=345.50, y=70.00, z=231.32], EntityCow['Cow'/220, l='MpServer', x=337.26, y=70.00, z=229.86], EntityCow['Cow'/221, l='MpServer', x=335.82, y=70.00, z=233.75], EntityPig['Pig'/222, l='MpServer', x=339.36, y=70.00, z=228.76], EntityBat['Bat'/223, l='MpServer', x=344.65, y=62.10, z=251.08], EntitySkeleton['Skeleton'/224, l='MpServer', x=337.76, y=40.00, z=266.70], EntitySkeleton['Skeleton'/225, l='MpServer', x=336.20, y=40.00, z=261.66], EntityBat['Bat'/226, l='MpServer', x=350.52, y=64.10, z=257.25], EntityBlueSlime['Blue Slime'/227, l='MpServer', x=346.20, y=134.72, z=277.36], EntityBlueSlime['Blue Slime'/228, l='MpServer', x=344.48, y=134.64, z=279.53], EntityBlueSlime['Blue Slime'/229, l='MpServer', x=338.12, y=69.00, z=295.78], EntitySpider['Spider'/230, l='MpServer', x=348.96, y=69.00, z=298.04], EntitySkeleton['Skeleton'/237, l='MpServer', x=360.50, y=27.00, z=192.50], EntityZombie['Zombie'/238, l='MpServer', x=354.57, y=68.00, z=214.72]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 234614464 bytes (223 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.0.1864 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1864-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1864} [Minecraft Forge] (forge-1.9-12.16.0.1864-1.9.jar) 
	UCHIJAAAA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJAAAA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9600 GT/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.9-forge1.9-12.16.0.1864-1.9
	LWJGL: 2.9.4
	OpenGL: GeForce 9600 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU @ 2.40GHz

**Comment by bonii-xx** [comment]
Same issue as #2013
