### ISSUE TITLE
Crafting station bug

### ISSUE THREAD

**Issue by skytheraiders** [SlimeKnights/TinkersConstruct#2017]
If you craft something in the crafting station and have to immediately put it back into the crafting grid in the UI, the game will crash and the only way to fix it is to uninstall the mod and load up the world, reinstall the mod.

**Comment by bonii-xx** [comment]
Log?

**Comment by skytheraiders** [comment]
Also I found that if you put in something that is craft able such as
buildcraft pipes or the storage draws draws, it will crash. And again, to
fix this you'll have to uninstall the mod, open your world, quit the game,
then reinstall the mod.

On Sat, Apr 16, 2016 at 3:23 AM, boni <notifications@github.com> wrote:

> Log?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SlimeKnights/TinkersConstruct/issues/2017#issuecomment-210756719>
>

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 4/16/16 10:23 AM
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=block, clazz=class com.jaquadro.minecraft.storagedrawers.api.storage.EnumBasicDrawer, values=[full1, full2, full4, half2, half4]} as it does not exist in ExtendedBlockState{block=tconstruct:tooltables, properties=[type]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Model.buildModel(BasicDrawerModel.java:83)
	at com.jaquadro.minecraft.chameleon.model.ProxyBuilderModel.setProxy(ProxyBuilderModel.java:85)
	at com.jaquadro.minecraft.chameleon.model.ProxyBuilderModel.func_188616_a(ProxyBuilderModel.java:34)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.mantle.client.model.BakedCompositeModel.func_188616_a(BakedCompositeModel.java:30)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.tconstruct.shared.client.BakedTableModel.func_188616_a(BakedTableModel.java:146)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:169)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:85)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:64)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:269)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:121)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:163)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1404)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1658)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1552)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1331)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Model.buildModel(BasicDrawerModel.java:83)
	at com.jaquadro.minecraft.chameleon.model.ProxyBuilderModel.setProxy(ProxyBuilderModel.java:85)
	at com.jaquadro.minecraft.chameleon.model.ProxyBuilderModel.func_188616_a(ProxyBuilderModel.java:34)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.mantle.client.model.BakedCompositeModel.func_188616_a(BakedCompositeModel.java:30)
	at slimeknights.mantle.client.model.TRSRBakedModel.func_188616_a(TRSRBakedModel.java:82)
	at slimeknights.tconstruct.shared.client.BakedTableModel.func_188616_a(BakedTableModel.java:146)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:169)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:67)

-- Block model being tesselated --
Details:
	Block: tconstruct:tooltables[type=craftingstation]
	Block location: World: (225,68,24), Chunk: (at 1,4,8 in 14,1; contains blocks 224,0,16 to 239,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:85)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:64)

-- Block being tesselated --
Details:
	Block type: ID #276 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.block.BlockToolTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (225,68,24), Chunk: (at 1,4,8 in 14,1; contains blocks 224,0,16 to 239,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:269)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:121)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:163)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1404)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1658)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1552)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['skytheraiders'/275, l='MpServer', x=226.43, y=69.00, z=25.72]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (229,64,30), Chunk: (at 5,4,14 in 14,1; contains blocks 224,0,16 to 239,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 589017 game time, 589017 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntitySquid['Squid'/128, l='MpServer', x=239.61, y=56.61, z=-20.83], EntitySquid['Squid'/129, l='MpServer', x=232.11, y=55.72, z=-14.71], EntityZombie['Zombie'/141, l='MpServer', x=240.07, y=22.00, z=-7.15], EntityHorse['Horse'/79, l='MpServer', x=192.61, y=62.65, z=-10.14], EntityHorse['Horse'/80, l='MpServer', x=206.81, y=62.05, z=-10.09], EntityRabbit['Rabbit'/81, l='MpServer', x=192.48, y=62.76, z=-9.20], EntityHorse['Horse'/82, l='MpServer', x=201.74, y=64.00, z=-7.52], EntityZombie['Zombie'/83, l='MpServer', x=196.80, y=44.00, z=11.48], EntityPlayerSP['skytheraiders'/275, l='MpServer', x=226.43, y=69.00, z=25.72], EntitySpider['Spider'/84, l='MpServer', x=204.00, y=64.00, z=24.49], EntityZombie['Zombie'/85, l='MpServer', x=193.50, y=37.00, z=55.50], EntityBat['Bat'/86, l='MpServer', x=193.55, y=38.92, z=57.75], EntityZombie['Zombie'/87, l='MpServer', x=196.50, y=37.00, z=64.50], EntityEnderman['Enderman'/95, l='MpServer', x=220.50, y=27.00, z=-18.50], EntitySquid['Squid'/161, l='MpServer', x=270.97, y=54.88, z=-3.36], EntitySquid['Squid'/162, l='MpServer', x=274.83, y=52.96, z=-9.25], EntitySkeleton['Skeleton'/102, l='MpServer', x=210.50, y=30.00, z=-11.50], EntitySkeleton['Skeleton'/103, l='MpServer', x=208.50, y=30.00, z=-8.50], EntityCreeper['Creeper'/104, l='MpServer', x=217.50, y=20.00, z=-8.50], EntityCreeper['Creeper'/105, l='MpServer', x=216.50, y=20.00, z=-7.50], EntityCreeper['Creeper'/106, l='MpServer', x=219.55, y=45.00, z=-10.80], EntitySkeleton['Skeleton'/107, l='MpServer', x=219.50, y=34.00, z=-9.50], EntityHorse['Horse'/108, l='MpServer', x=212.37, y=62.34, z=-9.26], EntityHorse['Horse'/109, l='MpServer', x=218.90, y=62.07, z=-8.29], EntityCreeper['Creeper'/110, l='MpServer', x=216.50, y=25.00, z=2.50], EntityCreeper['Creeper'/111, l='MpServer', x=213.50, y=48.00, z=3.50], EntitySkeleton['Skeleton'/112, l='MpServer', x=222.46, y=69.00, z=13.68], EntityCreeper['Creeper'/113, l='MpServer', x=222.30, y=69.00, z=16.30], EntityZombie['Zombie'/57, l='MpServer', x=180.77, y=24.00, z=1.52], EntityCreeper['Creeper'/58, l='MpServer', x=191.50, y=35.00, z=5.50], EntityCreeper['Creeper'/59, l='MpServer', x=189.50, y=38.00, z=4.50], EntitySkeleton['Skeleton'/60, l='MpServer', x=189.50, y=41.00, z=19.50], EntitySquid['Squid'/124, l='MpServer', x=231.47, y=59.20, z=-11.56], EntityBat['Bat'/61, l='MpServer', x=182.66, y=42.10, z=52.20], EntityBat['Bat'/127, l='MpServer', x=235.57, y=23.10, z=-5.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:453)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Mac OS X (x86_64) version 10.11.4
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1041501240 bytes (993 MB) / 1832636416 bytes (1747 MB) up to 3194421248 bytes (3046 MB)
	JVM Flags: 6 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256m -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 Optifine OptiFine_1.9_HD_U_B1 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	JEI{3.2.10.185} [Just Enough Items] (jei_1.9-3.2.10.185.jar) 
	UCHIJAAAA	BloodMagic{1.9-2.0.0-32} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-32.jar) 
	UCHIJAAAA	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJAAAA	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCHIJAAAA	chiselsandbits{9.13} [Chisels & Bits] (chiselsandbits-9.13.jar) 
	UCHIJAAAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9-rc.jar) 
	UCHIJAAAA	ElecCore{9} [ElecCore] (ElecCore-1.9-1.4.261.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHIJAAAA	inventorytweaks{1.61-dev-45-29e0ed5} [Inventory Tweaks] (InventoryTweaks-1.61-dev-45.jar) 
	UCHIJAAAA	IronChest{6.0.132.776} [Iron Chest] (ironchest-1.9-6.0.132.776.jar) 
	UCHIJAAAA	journeymap{1.9-5.1.6b2} [JourneyMap] (journeymap-1.9-5.1.6b2-unlimited.jar) 
	UCHIJAAAA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJAAAA	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCHIJAAAA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJAAAA	neotech{3.0.5} [NeoTech] (NeoTech-1.9-3.0.5.jar) 
	UCHIJAAAA	progressiveautomation{1.6.38} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.38.jar) 
	UCHIJAAAA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJAAAA	rftools{4.23beta44} [RFTools] (rftools-1.9.0-4.23beta44.jar) 
	UCHIJAAAA	StorageDrawers{1.9-3.1.5} [Storage Drawers] (StorageDrawers-1.9-3.1.5.jar) 
	UCHIJAAAA	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
	LWJGL: 2.9.2
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-10.14.58, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.9_HD_U_B1
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.14.58
	OpenGlRenderer: Intel Iris OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 4
