### ISSUE TITLE
(1.9) Crafting Station has no GUI

### ISSUE THREAD

**Issue by PossesiveGamer** [SlimeKnights/TinkersConstruct#2064]
I made a new 1.9 mod pack to play with the new Tinkers Construct and after I made a Crafting Station it has no GUI not even through the Stencil Table or any other block. I have to stick to the Crafting Table now :( 
Image:
http://imgur.com/xwUjYsD

P.S.
This is created with the newest version of Tinkers Construct for 1.9 (TConstruct-1.9-2.3.0) and Mantle(Mantle-1.9-0.10.0)
If this bug has been reported already don't get all worked up about it. I looked and couldn't find it but I suck at looking so if it has and needs to be removed please do.

Thanks,
PossessedGamer

**Comment by PossesiveGamer** [comment]
I'm also using the latest version of Forge(1.9 - 12.16.1.1892)

**Comment by PossesiveGamer** [comment]
I also keep getting this spammed in my console:

> Exception Details:
  Location:
    slimeknights/tconstruct/tools/inventory/ContainerCraftingStation.func_75130_a(Lnet/minecraft/inventory/IInventory;)V @16: aload_0
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab4 001d 2ab4 0016 2ab4 0067 b800 adb1
    0x0000010: 2ab4 0016 03b8 00b3 2ab4 001d 2ab4 0067
    0x0000020: b600 b7b9 00bd 0300 b1                 

	at slimeknights.tconstruct.tools.tileentity.TileCraftingStation.createContainer(TileCraftingStation.java:28) ~[TileCraftingStation.class:?]
	at slimeknights.mantle.common.GuiHandler.getServerGuiElement(GuiHandler.java:18) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:244) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:80) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462) ~[zj.class:?]
	at slimeknights.tconstruct.tools.block.BlockToolTable.openGui(BlockToolTable.java:86) ~[BlockToolTable.class:?]
	at slimeknights.tconstruct.tools.network.TinkerStationTabPacket.handleServerSafe(TinkerStationTabPacket.java:57) ~[TinkerStationTabPacket.class:?]
	at slimeknights.mantle.network.AbstractPacketThreadsafe$2.run(AbstractPacketThreadsafe.java:31) ~[AbstractPacketThreadsafe$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more
[15:01:51] [Server thread/INFO]: Saving and pausing game...
[15:01:51] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[15:01:51] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[15:04:45] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.VerifyError: Expecting a stack map frame

**Comment by PossesiveGamer** [comment]
I also keep getting this spammed in my console:
`Exception Details:
  Location:
    slimeknights/tconstruct/tools/inventory/ContainerCraftingStation.func_75130_a(Lnet/minecraft/inventory/IInventory;)V @16: aload_0
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab4 001d 2ab4 0016 2ab4 0067 b800 adb1
    0x0000010: 2ab4 0016 03b8 00b3 2ab4 001d 2ab4 0067
    0x0000020: b600 b7b9 00bd 0300 b1                 

	at slimeknights.tconstruct.tools.tileentity.TileCraftingStation.createContainer(TileCraftingStation.java:28) ~[TileCraftingStation.class:?]
	at slimeknights.mantle.common.GuiHandler.getServerGuiElement(GuiHandler.java:18) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:244) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:80) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462) ~[zj.class:?]
	at slimeknights.tconstruct.tools.block.BlockToolTable.openGui(BlockToolTable.java:86) ~[BlockToolTable.class:?]
	at slimeknights.tconstruct.tools.network.TinkerStationTabPacket.handleServerSafe(TinkerStationTabPacket.java:57) ~[TinkerStationTabPacket.class:?]
	at slimeknights.mantle.network.AbstractPacketThreadsafe$2.run(AbstractPacketThreadsafe.java:31) ~[AbstractPacketThreadsafe$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more
[15:01:51] [Server thread/INFO]: Saving and pausing game...
[15:01:51] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[15:01:51] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[15:04:45] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.VerifyError: Expecting a stack map frame`

**Comment by PossesiveGamer** [comment]
I also keep getting this spammed in my console:
http://pastebin.com/xbsZQvWv

Hope I have provided adequate information for this bug

**Comment by bonii-xx** [comment]
Looks like some other mods AMS derpage. Hold f3+C ingame, this'll crash it. Upload the crashlog

**Comment by PossesiveGamer** [comment]
Ok nevermind I made a new modpack and redownloaded tinkers construct and it works now
