### ISSUE TITLE
[1.8] NoSuchMethodError crash

### ISSUE THREAD

**Issue by TATDK** [SlimeKnights/TinkersConstruct#2073]
Version: TConstruct-1.8.9-2.2.1.jar

Short crashlog
```
java.lang.NoSuchMethodError: net.minecraft.world.biome.BiomeGenBase.func_76727_i()F
	at slimeknights.tconstruct.tools.traits.TraitAridiculous.calcAridiculousness(TraitAridiculous.java:37)
	at slimeknights.tconstruct.tools.traits.TraitAridiculous.miningSpeed(TraitAridiculous.java:25)
	at slimeknights.tconstruct.tools.TraitEvents.mineSpeed(TraitEvents.java:29)
```

Full crashlog here: https://pastebin.com/raw/yi743sQp

**Comment by bonii-xx** [comment]
Has this happened again in 1.9?
