### ISSUE TITLE
[1.9] NoSuchMethodError

### ISSUE THREAD

**Issue by UristMcClaws** [SlimeKnights/TinkersConstruct#2092]
Happens when a Pattern chest was placed next to a part builder.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 5/16/16 11:54 PM
Description: Unexpected error

java.lang.NoSuchMethodError: slimeknights.mantle.tileentity.TileInventory.writeInventoryToNBT(Lnet/minecraft/inventory/IInventory;Lnet/minecraft/nbt/NBTTagCompound;)V
at slimeknights.tconstruct.shared.block.BlockTable.getDrops(BlockTable.java:177)
at slimeknights.tconstruct.shared.block.BlockTable.getPickBlock(BlockTable.java:189)
at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:206)
at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:96)
at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:65)
at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:77)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_198_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
at org.multimc.EntryPoint.listen(EntryPoint.java:170)
at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
Minecraft Version: 1.9
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_91, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1472890560 bytes (1404 MB) / 2487746560 bytes (2372 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
FML: MCP 9.23 Powered by Forge 12.16.1.1898 29 mods loaded, 29 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAmcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAFML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1898-universal.jar) 
UCHIJAForge{12.16.1.1898} [Minecraft Forge] (forge-1.9-12.16.1.1898-universal.jar) 
UCHIJABBG{4.0.0} [BetterBedrockGen] (BetterBedrockGenerator-1.9.0-3.0.0.jar) 
UCHIJABiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
UCHIJAJEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
UCHIJABloodMagic{1.9-2.0.0-38} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-38.jar) 
UCHIJAChame[ElecCore] (ElecCore-1.9-1.4.270.jar) 
UCHIJAdeepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar) 
UCHIJAflatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.9-v2.2.jar) 
UCHIJAgraves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar) 
UCHIJAinventorytweaks{1.61-dev-fa19242-dirty} [Inventory Tweaks] (InventoryTweaks-1.61-dev.jar) 
UCHIJAIronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
UCHIJAjourneymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
UCHIJAmantle{1.9-0.10.0.jenkins132} [Mantle] (Mantle-1.9-0.10.0.jar) 
UCHIJAMorpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
UCHIJAnotenoughwands{1.3.3} [Not Enough Wands] (notenoughwands-1.9.0-1.3.3.jar) 
UCHIJAPsi{beta-31} [Psi] (Psi-beta-31.jar) 
UCHIJArftools{4.48} [RFTools] (rftools-1.9.0-4.48.jar) 
UCHIJArftoolsdim{4.23beta38} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta38.jar) 
UCHIJAStorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
UCHIJAtconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
UCHIJAWaila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
UCHIJAICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
UCHIJAwawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 980/PCIe/SSE2'
Pulsar/tconstruct loaded Pulses: 
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)

Launched Version: MultiMC5
LWJGL: 2.9.1
OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0
NVIDIA 364.72, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz

**Comment by KnightMiner** [comment]
Update Tinkers

**Comment by bonii-xx** [comment]
As KnightMiner said, you're using the alpha version of Mantle for the alpha version of TiC, without the alpha version of TiC. Upgrade TiC or downgrade Mantle.
