### ISSUE TITLE
crash with matteroverdrive's androids and TiC's piggybackpack

### ISSUE THREAD

**Issue by meelock** [SlimeKnights/TinkersConstruct#2182]
when i load my world it crashes with the error code (it has been shortened to be more readable.): 

[Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerEvent$LoadFromFile@12258e27:
java.lang.ClassCastException: slimeknights.tconstruct.library.capability.TinkerPiggybackHandler cannot be cast to matteroverdrive.entity.android_player.AndroidPlayer
	at matteroverdrive.entity.player.MOPlayerCapabilityProvider.GetAndroidCapability(MOPlayerCapabilityProvider.java:30) ~[MOPlayerCapabilityProvider.class:?]
	at matteroverdrive.handler.PlayerEventHandler.onPlayerLoadFromFile(PlayerEventHandler.java:156) ~[PlayerEventHandler.class:?]

**Comment by KnightMiner** [comment]
Duplicate of #2177.
