### ISSUE TITLE
[1.10] Hammer doesn't work

### ISSUE THREAD

**Issue by MachinegunMarty** [SlimeKnights/TinkersConstruct#2199]
Server:  forge-1.10-12.18.0.1992

I know that you don't support 1.10
(But just in case you decide to do ;-) )

Made a stone hammer and that only breaks the middle block and makes it impossible to walk through the removed stone again.
Solution: place a block on the removed stone and then you can walk through it.

So hammer only breaks 1 stone and spits out an error on the server console:

[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at slimeknights.tconstruct.library.utils.ToolHelper.breakExtraBlock(ToolHelper.java:372) ~[ToolHelper.class:?]
	at slimeknights.tconstruct.library.tools.ToolCore.onBlockStartBreak(ToolCore.java:187) ~[ToolCore.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:306) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[17:36:22] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at slimeknights.tconstruct.library.utils.ToolHelper.breakExtraBlock(ToolHelper.java:372) ~[ToolHelper.class:?]
	at slimeknights.tconstruct.library.tools.ToolCore.onBlockStartBreak(ToolCore.java:187) ~[ToolCore.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:306) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[17:36:40] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at slimeknights.tconstruct.library.utils.ToolHelper.breakExtraBlock(ToolHelper.java:372) ~[ToolHelper.class:?]
	at slimeknights.tconstruct.library.tools.ToolCore.onBlockStartBreak(ToolCore.java:187) ~[ToolCore.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:306) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[17:37:39] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at slimeknights.tconstruct.library.utils.ToolHelper.breakExtraBlock(ToolHelper.java:372) ~[ToolHelper.class:?]
	at slimeknights.tconstruct.library.tools.ToolCore.onBlockStartBreak(ToolCore.java:187) ~[ToolCore.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:306) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by Joker200215** [comment]
plz fix this i run 1.10 and i really like tinkers construct but cant use my favorite tool the hammer

**Comment by irontom10** [comment]
same problem

**Comment by Nightstalker350119** [comment]
Java Dev kit is required for this! Not Jre.
Download Here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Forge: http://files.minecraftforge.net/

Github: Your on it. Download it.

Under System Properties > Environment Variables. There must be a variable named "JAVA_HOME" then the variable value should be the path to your JDK file. Mine is "C:\Program Files\Java\jdk1.8.0_91"

Okay, i have found a fix, after spending half the day figuring out how to create mods and de-compiling Tinkers Mod. It's as simple as updating the mod it self, no code is need. First install Eclipse, then pull repository's on git hub by using the bash shell in get hub. This is the command "git clone https://github.com/SlimeKnights/TinkersConstruct.git". Now download the latest version of Forge. Make sure you download the MDK version and unzip it. Copy the eclipse folder from the unziped forge folder and paste the eclipse folder in TinkersConstruct directory (This is the git hub folder you downloaded). Next go back to the shell window. Point the shell window to TinkersConstruct folder by typing "cd TinkersConstruct" next paste this command in "./gradlew setupDecompWorkspace"   Once it finishes, next this command "./gradlew eclipse" . Now the tough part is over. Load up Eclipse  and point Eclipse's work space directory to the TinkersConstruct folder and then the Eclipse folder. Click the play button and presto. Minecraft forge loads and you have a working hammer. To rebuild the mod, open up bash and type "./gradlew build" this will build the java file to put in your mods folder. The compiled jar file should be located in "GitHub\Tinkers-Construct\TinkersConstruct\build\libs"

This is the download to the fixed jar file http://www.mediafire.com/download/elzym4rmdxlttd5/TConstruct-1.10-2.3.3.DEV.91cef91.jar

Credit goes to Stone Miner on: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2538275-tinkers-construct-re-implementing

**Comment by LovelyFlare** [comment]
@Nightstalker350119 And why would you post this here?

**Comment by jriwanek** [comment]
@Nightstalker350119 It's you're not your, but yeah, who exactly was that for, pretty sure not the Tcon people as they've demonstrated many a time they know perfectly well how to compile a mod and how to use gradle.

**Comment by Nightstalker350119** [comment]
@LovelyFlare I posted a quick fix for the other people who didn't know how to fix it off hand and that for the people that didn't want to wait for an official update itself so i provided the fix and a fixed jar file for their needs. I didn't want to make a separate thread on a whole different site for simplicity reasons.

**Comment by Nightstalker350119** [comment]
@jriwanek I posted the whole tutorial for the people who haven't compiled Tinkers Construct and were wanting to know how to do it. Plus I was just providing the steps on how I went about fixing it. I could have just left it as simple as recompile the mod with the version of forge and your done. I just listed the steps for people who didn't know how to do it :)

**Comment by LovelyFlare** [comment]
@Nightstalker350119 TiC updates come out pretty quickly...  also you're asking people to install 1 or 2 separate programs designed mostly for development, asking them to mess with their PATH variable (and them possibly unknowingly screwing it up with other programs that use it) for a fix they can wait for...  at least add a disclaimer.  There is no reason to compile it on your own unless you're so desperate you can't wait for an update...  Also, I would say this is not a place to post tutorials for DIY fixes, this is an issue tracker where issues can be tracked and official fixes can be provided for.  That's the whole point of this, is it not?  Therefore, a more appropriate place would be to put it on Minecraft Forums or such.  Also, this is pretty much listed in the README, it's vague so that people who know what they're doing will understand it.

**Comment by jriwanek** [comment]
Indeed. @LovelyFlare Btw, you might wanna look at your french translations PR and squash it like boni (I think it was boni) asked and then let him know.

**Comment by LovelyFlare** [comment]
@jriwanek Off topic, and I am aware.  When I am done with the translation, rather than squashing it, I will just close it and make a new PR with all the complete changes.

**Comment by Nightstalker350119** [comment]
@LovelyFlare Will Do. :)
