### ISSUE TITLE
[1.10] Server Crash killing skeleton with Broadsword

### ISSUE THREAD

**Issue by MachinegunMarty** [SlimeKnights/TinkersConstruct#2204]
Made a broadsword, updated with nether quartz, lapis (Loot 3) and diamond.

I killed different monsters without problem.

Fighting a skeleton: His last hit didn't kill him instead he stay there for 2 seconds and then the server crashed.

So i tried a bow with the broadsword in my hand and a bow in the shield slot, hit a skeleton 2 times, 3rd time server crashed.

Then i tried holding a normal vanilla diamond sword --> same crash
The i tried holding a vanilla diamond sword and use the a bow --> same crash

crash (took this from the client:

[18:37:56] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDropsEvent@5ac02001:
java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.func_82202_m()I
	at slimeknights.tconstruct.tools.ToolEvents.onLivingDrop(ToolEvents.java:82) ~[ToolEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_570_ToolEvents_onLivingDrop_LivingDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:509) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1090) [sf.class:?]
	at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(SourceFile:199) [zd.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970) [sf.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73) [yx.class:?]
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(SourceFile:337) [zv.class:?]
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:254) [zv.class:?]
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:79) [aam.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1955) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1925) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1748) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[18:37:57] [Server thread/ERROR] [FML/]: Index: 21 Listeners:

Lost all my tools and weapons because I had to remove tconstruct now because the world got unplayable :-(

I miss it allready.

Hope you will find time eventually to update to 1.10.

Thanx for an awesome mod !

grtz,

Machinegun_Marty

**Comment by KnightMiner** [comment]
This is one of those mods that is not entirely compatible with 1.10 due to the skeleton changes.

It was already fixed in the repository here, there are just a few more bugs to fix before a 1.10 release.

**Comment by MachinegunMarty** [comment]
Sweet,

Thanx for the update !

You mod makers are doing an awesome job. 
I got a private server where i'm testing 1.10 with a bunch of mods.
Any errors i find, i'm reporting to all the mod makers so you can make your mods even better.

Thanx again for an awesome mod and i will test the update when it's ready and of course report when i find anything strange.

grtz

Machinegun_Marty
