### ISSUE TITLE
[1.8.9] Ender io + Tinkers Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [SlimeKnights/TinkersConstruct#2206]
We seem to stumble upon a crash with tinkers and ender io. this is indeed in a modpack but we cant seem to find a fix. 

I'm going off the server crash log only and through that it points to ender io and tinkers.

Time: 6/27/16 1:57 PM
Description: Watching Server

java.lang.Error
	at net.minecraft.world.World.func_175625_s(World.java:2300)
	at slimeknights.tconstruct.smeltery.multiblock.MultiblockDetection.assignMultiBlock(MultiblockDetection.java:158)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.checkSmelteryStructure(TileSmeltery.java:376)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.notifyChange(TileSmeltery.java:354)
	at slimeknights.mantle.multiblock.MultiServantLogic.notifyMasterOfChange(MultiServantLogic.java:115)
	at slimeknights.tconstruct.smeltery.block.BlockEnumSmeltery.func_176204_a(BlockEnumSmeltery.java:54)
	at net.minecraft.world.World.func_180496_d(World.java:505)
	at net.minecraft.world.World.func_175685_c(World.java:452)
	at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyConduitNeighbours(RedstoneConduitNetwork.java:207)
	at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyNeigborsOfSignalUpdate(RedstoneConduitNetwork.java:178)
	at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.addSignal(RedstoneConduitNetwork.java:103)
	at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.addSignals(RedstoneConduitNetwork.java:95)
	at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.afterChunkUnload(RedstoneConduitNetwork.java:241)
	at crazypants.enderio.conduit.redstone.RedstoneConduit.onChunkUnload(RedstoneConduit.java:114)
	at crazypants.enderio.conduit.TileConduitBundle.onChunkUnload(TileConduitBundle.java:220)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

This is the error that points me to both Ender io conduits and tinkers. I don't however exactly know what is wrong. If you want full crash log let me know.

We are using forge build 1902
Ender io:1.8.9-latest
Tinkers Construct:1.8.9-latest

Ps: if you are no longer focused on 1.8.9, can you just let me know what the issue may be? and if its unfixable we may take one of the mods out. Thanks!

**Comment by bonii-xx** [comment]
1.8.9 is indeed done. However for the issue it looks like something goes wrong when updating the smeltery structure. This was changed some time later. Just keep redstone (and redstone conduits) at least 1 block away from the smeltery and you should be fine.

**Comment by EPIICTHUNDERCAT** [comment]
thank you, and yeah I thought so I hate bothering people with unsupported versions but needs to be fixed someway. thank you once again!
