### ISSUE TITLE
Server Crash from smeltery

### ISSUE THREAD

**Issue by mezz** [SlimeKnights/TinkersConstruct#2259]
MattaBase had a smeltery with iron in it, with a redstone clock attached to a faucet. When he placed down a casting table under the faucet, the server crashed with this error:

```
<FC1sm> [Server thread/ERROR]: Encountered an unexpected exception
<FC1sm> net.minecraft.util.ReportedException: Exception while updating neighbours
<FC1sm> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
<FC1sm> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
<FC1sm> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
<FC1sm> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
<FC1sm> at java.lang.Thread.run(Thread.java:745)
* ForgeCraft1 has quit (Remote host closed the connection)
<FC1sm> Caused by: java.lang.NullPointerException
<FC1sm> at slimeknights.tconstruct.library.smeltery.BucketCastingRecipe.matches(BucketCastingRecipe.java:29)
<FC1sm> at slimeknights.tconstruct.library.TinkerRegistry.getTableCasting(TinkerRegistry.java:531)
<FC1sm> at slimeknights.tconstruct.smeltery.tileentity.TileCastingTable.findRecipe(TileCastingTable.java:17)
<FC1sm> at slimeknights.tconstruct.smeltery.tileentity.TileCasting.findRecipe(TileCasting.java:207)
<FC1sm> at slimeknights.tconstruct.smeltery.tileentity.TileCasting.initNewCasting(TileCasting.java:217)
<FC1sm> at slimeknights.tconstruct.library.fluid.FluidHandlerCasting.fill(FluidHandlerCasting.java:39)
<FC1sm> at slimeknights.tconstruct.smeltery.tileentity.TileFaucet.doTransfer(TileFaucet.java:108)
<FC1sm> at slimeknights.tconstruct.smeltery.tileentity.TileFaucet.activate(TileFaucet.java:54)
<FC1sm> at slimeknights.tconstruct.smeltery.tileentity.TileFaucet.handleRedstone(TileFaucet.java:62)
<FC1sm> at slimeknights.tconstruct.smeltery.block.BlockFaucet.func_189540_a(BlockFaucet.java:111)
<FC1sm> at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
<FC1sm> at net.minecraft.world.World.func_180496_d(World.java:517)
<FC1sm> at net.minecraft.world.World.func_175685_c(World.java:465)
<FC1sm> at net.minecraft.world.World.func_175722_b(World.java:421)
<FC1sm> at net.minecraft.world.World.markAndNotifyBlock(World.java:366)
<FC1sm> at net.minecraft.world.World.func_180501_a(World.java:347)
<FC1sm> at com.rwtema.extrautils2.blocks.BlockRedstoneClock.func_180650_b(BlockRedstoneClock.java:139)
<FC1sm> at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:742)
<FC1sm> at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
<FC1sm> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
<FC1sm> ... 4 more
<FC1sm> Process exited with status 0.
```

After restarting the server, everything is fine.

**Comment by KnightMiner** [comment]
Looks like the bucket handler checks if the cast stack's item equals a vanilla bucket without checking if the stack is not null (a.k.a, the table is empty). You should be able to reproduce it by pouring anything into an entirely empty table, so I guess don't do that until it's fixed :)
