### ISSUE TITLE
[SOLVED] 1.7.10 issue java.lang.NoSuchMethodError: tconstruct.util.network.PacketPipeline

### ISSUE THREAD

**Issue by DarkSerpent** [SlimeKnights/TinkersConstruct#2295]
Whenever a player interacts with a Stencil Table, among other things, this error occurs:

There was a critical exception handling a packet on channel TConstruct
java.lang.NoSuchMethodError: tconstruct.util.network.PacketPipeline.getClientPlayer()Lnet/minecraft/entity/player/EntityPlayer;
	at tconstruct.util.network.PacketPipeline.decode(PacketPipeline.java:102) ~[PacketPipeline.class:?]
	at tconstruct.util.network.PacketPipeline.decode(PacketPipeline.java:22) ~[PacketPipeline.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:Server-1.7.10-2.1403.1.54]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]

**Comment by DarkSerpent** [comment]
Solved, the problem was a plugin called "SoundCenter"

**Comment by LovelyFlare** [comment]
Feel free to close this issue as well
