### ISSUE TITLE
Game is crashing when destroying blocks

### ISSUE THREAD

**Issue by stef456** [SlimeKnights/TinkersConstruct#2352]
HI, 

the game is crashing when i destroy most fo the blocks in the mod included (Toolstation etc)

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 30.08.16 16:43
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1907)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1343)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
	at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:668)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1907)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1343)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Prolog'/268, l='MpServer', x=-878,13, y=79,00, z=-705,07]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-180,64,68), Chunk: (at 12,4,4 in -12,4; contains blocks -192,0,64 to -177,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 258708 game time, 258708 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 23 total; [EntityBat['Bat'/417, l='MpServer', x=-904,11, y=21,09, z=-727,49], EntityBat['Bat'/418, l='MpServer', x=-906,47, y=23,08, z=-747,89], EntityBat['Bat'/387, l='MpServer', x=-935,41, y=19,10, z=-666,61], EntityCow['Cow'/388, l='MpServer', x=-942,18, y=76,00, z=-669,47], EntitySheep['Sheep'/389, l='MpServer', x=-933,20, y=76,00, z=-670,69], EntityMinecartChest['Minecart with Chest'/358, l='MpServer', x=-932,50, y=20,06, z=-753,50], EntityBat['Bat'/390, l='MpServer', x=-917,52, y=14,10, z=-783,75], EntityMinecartChest['Minecart with Chest'/359, l='MpServer', x=-955,50, y=13,06, z=-741,50], EntityBat['Bat'/360, l='MpServer', x=-956,49, y=17,67, z=-768,01], EntityBat['Bat'/459, l='MpServer', x=-806,75, y=24,10, z=-681,24], EntityCow['Cow'/396, l='MpServer', x=-926,44, y=74,00, z=-632,93], EntityPlayerSP['Prolog'/268, l='MpServer', x=-878,13, y=79,00, z=-705,07], EntitySheep['Sheep'/376, l='MpServer', x=-937,66, y=72,00, z=-677,63], EntitySheep['Sheep'/377, l='MpServer', x=-931,87, y=72,00, z=-686,36], EntityCow['Cow'/378, l='MpServer', x=-936,83, y=75,00, z=-674,49], EntityBat['Bat'/379, l='MpServer', x=-949,04, y=51,10, z=-661,17], EntityBat['Bat'/443, l='MpServer', x=-856,54, y=21,06, z=-693,96], EntityBat['Bat'/380, l='MpServer', x=-941,88, y=49,24, z=-673,35], EntityBat['Bat'/444, l='MpServer', x=-878,04, y=14,62, z=-652,95], EntitySheep['Sheep'/381, l='MpServer', x=-928,70, y=67,00, z=-703,71], EntityMinecartChest['Minecart with Chest'/445, l='MpServer', x=-836,50, y=28,06, z=-642,51], EntityBat['Bat'/382, l='MpServer', x=-941,51, y=21,00, z=-699,50], EntityBat['Bat'/446, l='MpServer', x=-866,81, y=35,23, z=-641,81]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333098208 bytes (317 MB) / 955621376 bytes (911 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2043 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2043.jar) 
	UCHIJAAAA	Forge{12.18.1.2043} [Minecraft Forge] (forge-1.10.2-12.18.1.2043.jar) 
	UCHIJAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4(1).jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0(2).jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.81' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2043
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz

**Comment by KnightMiner** [comment]
Update Forge, not our fault

**Comment by stef456** [comment]
Thank you
