### ISSUE TITLE
Serious!!!!!!!!People can get unlimited items by hovering their mouse on the item

### ISSUE THREAD

**Issue by 5igm** [SlimeKnights/TinkersConstruct#2367]
https://my.pcloud.com/publink/show?code=XZuGQWZtFe4VlojngYaHNNRxFX0IzfPHVvV
The video shows all.

**Comment by 5igm** [comment]
MC 1.10.2 - 2.4.0

**Comment by bonii-xx** [comment]
Hold F3+C and post the crash to pastebin

**Comment by 5igm** [comment]
There is no crash. As I said, you can know everything when you  watch this video. Please watch it. Or you can try to show this error by yourself. You just need to hover your mouse on the tconstruct's equipment and then press "q" to drop them away. Now, you will find you can drop unlimited same item. Please fix it, thanks. @bonii-xx

**Comment by bonii-xx** [comment]
Again. Hold F3+C and post the crash to pastebin. SSP or SMP?

**Comment by utoc** [comment]
I am not seeing this behavior in TiCo 2.4.0 w Mantle 0.10.4

**Comment by Lazarix** [comment]
I am also not seeing this issue with TConstruct-1.10.2-2.4.0

**Comment by Lazarix** [comment]
SSP

**Comment by bonii-xx** [comment]
Pssst. I know. I"m trying to get him to tell me what causes it.

**Comment by 5igm** [comment]
Excuse me. I am confused. There is no reaction when I pressed F3 and C at the same time.

**Comment by bonii-xx** [comment]
>Hold

**Comment by 5igm** [comment]
There still no reaction.

**Comment by 5igm** [comment]
While I pressed F3 and C, I hovered mouse on the tconstruct equipment and press "q" to drop it. Their is no feedback appearing in console.

**Comment by KnightMiner** [comment]
Hold *both* F3 and C until something happens. Do not let go of the two keys until something does. It normally takes about 5 seconds

**Comment by 5igm** [comment]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.0.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 16-9-5 上午2:56
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1866)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1866)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DeitySSS'/1309, l='MpServer', x=-173.50, y=186.00, z=-106.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-171,187,-107), Chunk: (at 5,11,5 in -11,-7; contains blocks -176,0,-112 to -161,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 13447035 game time, 1004627 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityPlayerSP['DeitySSS'/1309, l='MpServer', x=-173.50, y=186.00, z=-106.50], EntityHorse['马'/165, l='MpServer', x=-246.42, y=71.00, z=-171.69], EntityHorse['骷髅马'/186, l='MpServer', x=-154.41, y=62.38, z=-90.90]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556114960 bytes (530 MB) / 1354878976 bytes (1292 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 2 total; -Xincgc -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.32 Powered by Forge 12.18.1.2073 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2073.jar) 
	UCHIJA	Forge{12.18.1.2073} [Minecraft Forge] (forge-1.10.2-12.18.1.2073.jar) 
	UCHIJA	AntiCheat3{AntiCheat 3 Mod} [AntiCheat 3 Mod] (AntiCheat-3.4.3-beta-1.9.4.jar) 
	UCHIJA	JEI{3.9.0.245} [Just Enough Items] (jei_1.10.2-3.9.0.245.jar) 
	UCHIJA	AppleCore{2.0.0} [AppleCore] (AppleCore-mc1.10.2-2.0.0.jar) 
	UCHIJA	appleskin{1.0.1} [AppleSkin] (AppleSkin-mc1.10.2-1.0.1.jar) 
	UCHIJA	Psi{r1.0-39} [Psi] (Psi-r1.0-39.jar) 
	UCHIJA	AutoRegLib{1.0-1} [AutoRegLib] (AutoRegLib-1.0-1.jar) 
	UCHIJA	BetterHorseHud{1.0} [Better Horse Hud] (BetterHorseHud-[1.9-1.10.2]-1.0.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.9.4-2.0.0-40.jar) 
	UCHIJA	BloodMagic{1.9.4-2.0.4-56} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.4-56.jar) 
	UCHIJA	chiselsandbits{11.7} [Chisels & Bits] (chiselsandbits-11.7.jar) 
	UCHIJA	CustomMainMenu{2.0.1} [Custom Main Menu] (CustomMainMenu-MC1.9.4-2.0.1.jar) 
	UCHIJA	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
	UCHIJA	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.1.jar) 
	UCHIJA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJA	hidenames{1.2.1} [HideNames] (HideNames-1.10.2-1.2.1.jar) 
	UCHIJA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJA	mod_quiver{1.10-1.2.2} [FF Quiver Mod] (mod_ffQuiver_forge-1.10-1.2.2.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJA	ShieldHider{1.0.1} [Shield Hider] (ShieldHider-1.0.1_1.9.4.jar) 
	UCHIJA	Souls{1.1.0} [Souls] (Souls-1.10.2-1.1.0.jar) 
	UCHIJA	SpiceOfLife{1.3.3} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.3.jar) 
	UCHIJA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_MC1.9.4.jar) 
	UCHIJA	WailaHarvestability{1.1.8} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.8.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  lumien.custommainmenu.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-2.0.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.74' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2073
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.74, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 奇点专用材质包
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
```

**Comment by 5igm** [comment]
Does it you want?

**Comment by bonii-xx** [comment]
Yes, that's what I wanted. Are you playing singleplayer or on a server?

**Comment by 5igm** [comment]
server

**Comment by 5igm** [comment]
It is a sponge server.

**Comment by KnightMiner** [comment]
Can you reproduce it on a regular Forge server? If not, Sponge is your issue. If so, try and narrow down which mod is the issue, as this does not happen in Tinkers Construct by itself

**Comment by bonii-xx** [comment]
I guess I know what the issue is. Either sponge or that weird anti-cheat mod are trying to spawn that stuff using vanilla commands. Vanilla commands are bugged though, and spawn items with custom entities twice.

**Comment by 5igm** [comment]
@bonii-xx  Thank you very much. I think the problem might is not related to anti-cheat mod. This mod is used to prevent players from installing cheating mods or resources by checking md5 codes. And when I only installed Mantle, Tconstruct, and Sponge, the problem still appeared.

**Comment by bonii-xx** [comment]
Ok, thanks for checking. Knowing the Sponge guys we'll probably know why soon.

**Comment by 5igm** [comment]
Nice. I will wait for it. One more stuff, what is your meaning about "knowing the Sponge guys"? Because English is not my first language,  I am confused for your meaning...

**Comment by Syndaryl** [comment]
@5igm "As we know what the people who make Sponge are like..." or "Using our knowledge of what the people who make Sponge are like..."
