### ISSUE TITLE
[1.10.2] Empty string not allowed

### ISSUE THREAD

**Issue by gdude2002** [SlimeKnights/TinkersConstruct#2402]
Forge: 12.18.1.2092 51
TConstruct: 2.5.2

Just had a server crash due to this error. I had just added some tin and copper to a smeltery, and was wandering back to my house.

Upon restarting the server, the items I had put inside the smeltery were gone, and no liquids were in it, although there was still some lava left in the tank.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  LoadingPlugin (Quark-r1.0-55.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/20/16 10:05 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:100)
	at slimeknights.tconstruct.library.smeltery.SmelteryTank.writeToNBT(SmelteryTank.java:147)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.func_189515_b(TileSmeltery.java:364)
	at slimeknights.tconstruct.smeltery.tileentity.TileMultiblock.func_189518_D_(TileMultiblock.java:165)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:272)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:100)
	at slimeknights.tconstruct.library.smeltery.SmelteryTank.writeToNBT(SmelteryTank.java:147)
	at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.func_189515_b(TileSmeltery.java:364)
	at slimeknights.tconstruct.smeltery.tileentity.TileMultiblock.func_189518_D_(TileMultiblock.java:165)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:272)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['arbot'/1669851, l='world', x=230.47, y=64.00, z=382.37], EntityPlayerMP['Kandrion'/1795380, l='world', x=-363.70, y=62.07, z=60.54]]
	Chunk stats: ServerChunkCache: 1157 Drop: 0
	Level seed: -5331457623312841337
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-65,63,104), Chunk: (at 15,3,8 in -5,6; contains blocks -80,0,96 to -65,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1212223 game time, 1464018 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 16783 (now: true), thunder time: 45898 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 476744144 bytes (454 MB) / 1519910912 bytes (1449 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 1 total; -Xmx12288M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2092 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	UCHIJAAAA	Forge{12.18.1.2092} [Minecraft Forge] (minecraft_server.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r63} [Actually Additions] (ActuallyAdditions-1.10.2-r63.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJAAAA	JEI{3.9.5.255} [Just Enough Items] (jei_1.10.2-3.9.5.255.jar) 
	UCHIJAAAA	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCHIJAAAA	Quark{r1.0-55} [Quark] (Quark-r1.0-55.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4b.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
	UCHIJAAAA	bookshelfapi{3.2.2} [Bookshelf] (Bookshelf-API-1.10.2-3.2.2.jar) 
	UCHIJAAAA	Botania{r1.8-321} [Botania] (Botania-unofficial.r1.8-321.jar) 
	UCHIJAAAA	BuildersGuides{1.10.2-1.0.2} [Builder's Guides] (buildersguides-1.10.2-1.0.2.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.15} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.15.jar) 
	UCHIJAAAA	shadowmc{3.4.4} [ShadowMC] (ShadowMC-1.10.2-3.4.4.jar) 
	UCHIJAAAA	DiscordChat{1.4.0} [DiscordChat] (DiscordChat-1.10.2-1.4.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.107_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.107_beta.jar) 
	UCHIJAAAA	IC2{2.6.69-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.69-ex110.jar) 
	UCHIJAAAA	forestry{5.2.12.256} [Forestry] (forestry_1.10.2-5.2.12.256.jar) 
	UCHIJAAAA	graves{1.10.2-b28-universal} [Graves Mod] (Graves-1.10.2-b28-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.9.796} [Iron Chest] (ironchest-1.10.2-7.0.9.796.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHIJAAAA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
	UCHIJAAAA	progressiveautomation{1.6.51} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51.jar) 
	UCHIJAAAA	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCHIJAAAA	reborncore{2.7.1.38} [RebornCore] (RebornCore-1.10.2-2.7.1.38-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.7.1.38} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.7.1.38-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJAAAA	refinedstorage{1.0.4} [Refined Storage] (refinedstorage-1.0.4.jar) 
	UCHIJAAAA	rftools{5.23} [RFTools] (rftools-1.10-5.23.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.4} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.4.jar) 
	UCHIJAAAA	stacksonstacks{1.1.4} [stacksonstacks] (StacksOnStacks2-1.1.4.jar) 
	UCHIJAAAA	substratum{1.8.1.0} [Substratum] (Substratum-1.10.2-1.8.1.0.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct] (TConstruct-1.10.2-2.5.2.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAA	UniDict{1.10.2-1.8c} [UniDict] (UniDict-1.10.2-1.8c.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.69-ex110.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-r1.0-55.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/AMP/.ampdata/instances/Minecraft-Mystic/Minecraft/mods/mcjtylib-1.10-2.1.0.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Player Count: 2 / 30; [EntityPlayerMP['arbot'/1669851, l='world', x=230.47, y=64.00, z=382.37], EntityPlayerMP['Kandrion'/1795380, l='world', x=-363.70, y=62.07, z=60.54]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by bonii-xx** [comment]
Found any way to reproduce this?

**Comment by gdude2002** [comment]
Nope, I'm beginning to think it was a broken world. Let's hope, I guess!
