### ISSUE TITLE
Mod Incompatibility causing Crash

### ISSUE THREAD

**Issue by BrisingrAerowing** [SlimeKnights/TinkersConstruct#2436]
ref hea3ven/BuildingBricks#95

The newest TConstruct (2.5.3) causes BuildingBricks to crash as that mod fails a getting the material of `tconstruct:materials/vine.json`

I am not sure if this is on BuildingBricks' side or TConstruct's side.

**Comment by iTraumatik** [comment]
Getting this same crash..... Building bricks hasnt been updated since July from what i can see but also dont know if TC or BB....

java.lang.RuntimeException: Could not load material from tconstruct:materials/vine.json
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:30)
	at com.hea3ven.buildingbricks.core.ProxyCommonBuildingBricks.onPreInitEvent(ProxyCommonBuildingBricks.java:86)
	at com.hea3ven.buildingbricks.core.ModBuildingBricks.preInit(ModBuildingBricks.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: com.google.gson.JsonParseException: material does not have an id
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser$MaterialDeserializer.deserialize(MaterialParser.java:46)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser$MaterialDeserializer.deserialize(MaterialParser.java:37)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser.loadMaterialFromStream(MaterialParser.java:34)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:26)
	... 46 more

**Comment by bonii-xx** [comment]
Building Bricks is trying to load files that don't belong to building bricks. Simple as that.

**Comment by BubbaVB** [comment]
It looks like Building Bricks just updated today (10/9/16).  This appears to have resolved the issue.
