### ISSUE TITLE
Help Please.

### ISSUE THREAD

**Issue by Lion4K** [SlimeKnights/TinkersConstruct#2482]
It crashes at Startup.
Idk what to do.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  offlineskins (OfflineSkins-1.10.2-v1a.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 12/10/16 01:34
XRay version: 39
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.tconstruct.library.client.model.MaterialModel.bakeIt(MaterialModel.java:75)
	at slimeknights.tconstruct.library.client.model.MaterialModel.bake(MaterialModel.java:51)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 341992728 bytes (326 MB) / 759377920 bytes (724 MB) up to 3207856128 bytes (3059 MB)
	Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@2d3f68d6
	LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@3cd3fa1c
	LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@53f8f092
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.2.2105 Optifine OptiFine_1.10.2_HD_U_C3 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2105.jar) 
	UCHIJA	Forge{12.18.2.2105} [Minecraft Forge] (forge-1.10.2-12.18.2.2105.jar) 
	UCHIJA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJA	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCHIJA	JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
	UCHIJA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJA	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHIJA	offlineskins{1.10.2-v1a} [OfflineSkins] (OfflineSkins-1.10.2-v1a.jar) 
	UCHIJA	tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
	UCHIJA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.1.2026.jar) 
	Loaded coremods (and transformers): 
offlineskins (OfflineSkins-1.10.2-v1a.jar)
  lain.mods.skins.asm.ASMTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4425' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.2.2105
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4425, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4425
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4`

**Comment by KnightMiner** [comment]
Same crash as #2483 it appears. Removing Optifine will solve the issue.

**Comment by Lion4K** [comment]
But How do I play w/o Optifine? it used to work fine before.

**Comment by KnightMiner** [comment]
Whatever steps you took to install optifine, do the opposite.  Or redownload and install Forge and add all other mods to the new instalation.

**Comment by Lion4K** [comment]
You don't get it, I can't play w/o Optfine, i know how to install/uninstall it.
My computer does not run the game well w/o optifine.

**Comment by GirafiStudios** [comment]
The issue should be fixed in OptiFine C4 when that is out, so you wuold have to wait for that :)

**Comment by KnightMiner** [comment]
You can either try another lag reducing mod such as [BetterFPS](https://minecraft.curseforge.com/projects/betterfps), but if that does not work you have to either remove Tinkers or remove Optifine and some other mods in attempt to lighten the load. Sorry this is the case, but we cannot possibly know what Optifine is doing to even attempt to support their changes. 

Alternatively, sp614x said on #2483 that he may have discovered the cause of the issue so hopefully can have it fixed on Optifine's side. While it still won't be supported by us, it hopefully won't crash anymore.

**Comment by Lion4K** [comment]
gonna try that, thanks.
