### ISSUE TITLE
[1.10.2] Tinkers' Construct not working?

### ISSUE THREAD

**Issue by AeroDragonic** [SlimeKnights/TinkersConstruct#2527]
Using: Forge 12.18.1.2073

---- Minecraft Crash Report ----
// You're mean.

Time: 16. 10. 30  11:15AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1477)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:415)
	at net.minecraft.world.World.func_72833_a(World.java:1468)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1691)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1243)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.getSkyColorBody(World.java:1477)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:415)
	at net.minecraft.world.World.func_72833_a(World.java:1468)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1691)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1243)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 476975520 bytes (454 MB) / 1122979840 bytes (1070 MB) up to 1402208256 bytes (1337 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1350M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 87
	FML: MCP 9.32 Powered by Forge 12.18.1.2073 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2073.jar) 
	UCHIJAAAA	Forge{12.18.1.2073} [Minecraft Forge] (forge-1.10.2-12.18.1.2073.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r67} [Actually Additions] (ActuallyAdditions-1.10.2-r67.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJAAAA	gravestone{1.5.8} [Gravestone] (GraveStone Mod 1.5.8.jar) 
	UCHIJAAAA	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.9836 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 545v'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2073
	LWJGL: 2.9.4
	OpenGL: ATI Mobility Radeon HD 545v GL version 3.3.9836 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz

**Comment by ArukaAlter** [comment]
Something is requesting the sky color and failing to do so, not Tinkers' fault.

**Comment by AeroDragonic** [comment]
Ok. Do you know what is wrong with the sky color? I've tried multiple Forge clients and none of them seems to work.

**Comment by KnightMiner** [comment]
Impossible to tell from just the report, try removing mods until it stops then add them back until you are sure what causes it. Tinkers does nothing with the sky color nor anything that would modify the world class, so I am closing this as another mod causing it.
