### ISSUE TITLE
Conflict with EnderIO and ImmerviseEngineering mods 

### ISSUE THREAD

**Issue by Reydenge** [SlimeKnights/TinkersConstruct#2536]
Hello, i've done my modpack for Minecraft 1.10.2 with this three mods  - Tinker's Construct, EnderIO and ImmersiveEngineering. Also i have subsidiary mods like InventoryTweaks, Just Enough Items, Just Enough Resources, TreeChopper and VoxelMap. And some addons for Tinker's Construct (TinkerToolLeveling), EnderIOAddons. Forge and LiteLoader's versions are the last.
Then i start the modpack, it crashes. May some of you look at me crash-report? Thank you.  

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 03.11.16 12:35
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.google.common.base.CharMatcher$NegatedMatcher.<init>(CharMatcher.java:635)
	at com.google.common.base.CharMatcher.negate(CharMatcher.java:623)
	at com.google.common.base.CharMatcher.retainFrom(CharMatcher.java:1095)
	at net.minecraftforge.fml.client.FMLClientHandler.stripSpecialChars(FMLClientHandler.java:1035)
	at net.minecraftforge.fml.common.FMLCommonHandler.stripSpecialChars(FMLCommonHandler.java:743)
	at net.minecraftforge.fml.common.ProgressManager$ProgressBar.step(ProgressManager.java:126)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:175)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:291)
	at com.mumfrey.liteloader.client.ClientProxy.onStartupComplete(ClientProxy.java:55)
	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzg000(Minecraft.java:46)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:555)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.google.common.base.CharMatcher$NegatedMatcher.<init>(CharMatcher.java:635)
	at com.google.common.base.CharMatcher.negate(CharMatcher.java:623)
	at com.google.common.base.CharMatcher.retainFrom(CharMatcher.java:1095)
	at net.minecraftforge.fml.client.FMLClientHandler.stripSpecialChars(FMLClientHandler.java:1035)
	at net.minecraftforge.fml.common.FMLCommonHandler.stripSpecialChars(FMLCommonHandler.java:743)
	at net.minecraftforge.fml.common.ProgressManager$ProgressBar.step(ProgressManager.java:126)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:175)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:291)
	at com.mumfrey.liteloader.client.ClientProxy.onStartupComplete(ClientProxy.java:55)
	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzg000(Minecraft.java:46)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:555)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1432 bytes (0 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2117 Optifine OptiFine_1.10.2_HD_U_C3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2117.jar) 
	UCHIJA	Forge{12.18.2.2117} [Minecraft Forge] (forge-1.10.2-12.18.2.2117.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJA	JEI{3.13.0.338} [Just Enough Items] (jei_1.10.2-3.13.0.338.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.125_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.125_beta.jar) 
	UCHIJA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJA	jeresources{0.5.4.67} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.4.67.jar) 
	UCHIJA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJA	treechopper{1.1.0} [Tree Chopper] (TreeChopper-1.10.2-1.1.0.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 7600M Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7600M Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.10.2-r4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 7600M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by Reydenge** [comment]
And one more bug - when i open Stirling Generator Minecraft also chashed.

**Comment by ArukaAlter** [comment]
Try without LiteLoader.

**Comment by Reydenge** [comment]
@ArukaAlter oo, without liteloader everything works, thanks. But i have one more problem. Then i open Stirling Generator, after 5 sec Minecraft chashes, can you help me with this problem?

**Comment by Reydenge** [comment]
@ArukaAlter oo, without LiteLoader everything works, thanks
