### ISSUE TITLE
Weird crash on hovering tooltip

### ISSUE THREAD

**Issue by darkhax** [SlimeKnights/TinkersConstruct#2569]
Hi, I got this crash when looking at the tooltip of a shovel head. Not sure on any of the other details. One of the players on a server tossed it to me.

```
java.lang.NullPointerException: Rendering screen
	at slimeknights.tconstruct.library.tools.ToolPart.func_77624_a(ToolPart.java:116)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:614)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by LovelyFlare** [comment]
Do you have a list of mods?

**Comment by darkhax** [comment]
Unfortunately not. This was all I was able to grab at the time. Should be more than enough for Boni or whoever to figure out what's going on though. I have the means to reproduce the entire crash log if needed though.

**Comment by bonii-xx** [comment]
What material was the head made out of? Looks like an incorrectly registered material.

**Comment by darkhax** [comment]
The crash happens when you look at the tooltip, so I can't really tell what material it is. It looks like just the black outline of a tool part. Not really sure how players are getting them either.

**Comment by ArukaAlter** [comment]
You can get the full mod list by sending the full log (on pastebin or hastebin), so the mod that adds that material can be tracked more easily.

**Comment by bonii-xx** [comment]
Yup, that sounds like they're having toolparts with materials that don't exist per se. There are some materials that only exist clientside for rendering, probably one of those. There is no legitimate way of obtaining them via Tinkers', so either some other mod or people are being stupid and using /give.

**Comment by darkhax** [comment]
After asking about it in more detail, it seems one of the other mods in the pack generates these broken items as a loot drop. While it's technically not an issue with tcon, I would appreciate it if you could handle this exception to prevent the client from crashing.

**Comment by bonii-xx** [comment]
It has already been taken care of quite a while ago.
