### ISSUE TITLE
Broadsword class not found

### ISSUE THREAD

**Issue by checkium** [SlimeKnights/TinkersConstruct#2618]
```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/items/tools/Broadsword
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/items/tools/Broadsword
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: tconstruct.items.tools.Broadsword
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: tconstruct.library.tools.Weapon
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at weatherpony.partial.asmedit.ExtentionListenerTransformer.transform(ExtentionListenerTransformer.java:51)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 37 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.tools.Weapon
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at weatherpony.partial.asmedit.ExtentionListenerTransformer.transform(ExtentionListenerTransformer.java:44)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 243922664 bytes (232 MB) / 552407040 bytes (526 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 101 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	OpenComputers|Core{1.6.0.9} [OpenComputers (Core)] (minecraft.jar) 
	UC	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UC	securitycraft{v1.8.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.1.jar) 
	UC	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UC	deconstruction{2.2.6} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.6].jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UC	ae2stuff{0.5.1.61} [AE2 Stuff] (ae2stuff-0.5.1.61-mc1.7.10.jar) 
	UC	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-LATEST-1.7.10.jar) 
	UC	AppleCore{1.3.2} [AppleCore] (AppleCore-mc1.7.10-1.3.2.jar) 
	UC	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UC	BetterFoliage{2.0.14} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.14.jar) 
	UC	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UC	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UC	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
	UC	blocklings{1.0.4} [Blocklings] (Blocklings-Mod-1.7.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UC	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UC	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UC	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UC	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UC	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UC	ChunkAnimator{@VERSION@} [Chunk Animator] (ChunkAnimator-MC1.7.10-1.0.1.jar) 
	UC	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UC	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UC	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UC	farseek{1.0.11} [farseek] (Farseek-1.0.11.jar) 
	UC	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UC	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
	UC	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
	UC	GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
	UC	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UC	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UC	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UC	LogisticsPipes{0.9.3.128} [Logistics Pipes] (logisticspipes-0.9.3.128.jar) 
	UC	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a (1).jar) 
	UC	mcheli{1.0.2} [MC Helicopter] (mcheli) 
	UC	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UE	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7 (1).jar) 
	UC	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MorePistons{2.0.0} [More Pistons] (MorePistons-2.0.0-1.7.10.jar) 
	UC	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UC	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UC	numina{0.4.1.103} [Numina] (Numina-0.4.1.103.jar) 
	UC	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UC	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UC	OpenComputers{1.6.0.9} [OpenComputers] (OpenComputers-MC1.7.10-1.6.0.9-universal.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UC	ShetiPhianCore{3.0.0} [ShetiPhian-Core] (ShetiPhianCore-1.7.10-3.0.0.jar) 
	UC	platforms{0.1.2} [Platforms] (platforms-1.7.10-0.1.2.jar) 
	UC	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UC	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UC	PushShove{1.0} [Push and Shove] (PushShove-1.7.10-1.0.jar) 
	UC	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UC	signpic{2.5.1} [SignPicture] (SignPicture-1.7.10-2.5.1-universal.jar) 
	UC	skinport{1.7.10-v8c} [SkinPort] (SkinPort-1.7.10-v8c.jar) 
	UC	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.6.jar) 
	UC	streams{0.2} [streams] (Streams-0.2.jar) 
	UC	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
	UC	universalcoins{1.7.10-1.7.5} [Universal Coins] (UniversalCoins-1.7.10-1.7.5.jar) 
	UC	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UC	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
	UC	UniDict{1.7.10-2.9.2} [UniDict] (UniDict-1.7.10-2.9.2.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GT 730/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	ThermalDynamics: -[1.7.10]1.2.0-171
```

**Comment by ArukaAlter** [comment]
1.7 is no longer supported.

**Comment by bonii-xx** [comment]
Either your jar file is broken or some coremod breaks your classloading due to errors.

**Comment by Eufranio** [comment]
kek

**Comment by bonii-xx** [comment]
Out of curiousity, which one was it?

**Comment by checkium** [comment]
@bonii-xx It was with partial modificator loader, I already reported the bug to the author, since the crashes weren't only with tinkers.
