### ISSUE TITLE
[1.10.2] TiC 2.6.0 Reinforced Arrows client crash

### ISSUE THREAD

**Issue by desvandev** [SlimeKnights/TinkersConstruct#2622]
I think it happens when the reinforced trait triggers:

`
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at slimeknights.tconstruct.tools.modifiers.ModReinforced.onToolDamage(ModReinforced.java:42)
	at slimeknights.tconstruct.library.utils.ToolHelper.damageTool(ToolHelper.java:498)
	at com.sosnitzka.taiga.traits.TraitInstable.afterHit(TraitInstable.java:52)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:741)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:566)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.dealDamage(EntityProjectileBase.java:314)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.onHitEntity(EntityProjectileBase.java:241)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.updateInAir(EntityProjectileBase.java:436)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:363)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at slimeknights.tconstruct.tools.modifiers.ModReinforced.onToolDamage(ModReinforced.java:42)
	at slimeknights.tconstruct.library.utils.ToolHelper.damageTool(ToolHelper.java:498)
	at com.sosnitzka.taiga.traits.TraitInstable.afterHit(TraitInstable.java:52)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:741)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:566)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.dealDamage(EntityProjectileBase.java:314)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.onHitEntity(EntityProjectileBase.java:241)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.updateInAir(EntityProjectileBase.java:436)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:363)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: tconstruct.arrow (slimeknights.tconstruct.tools.common.entity.EntityArrow)
	Entity ID: 3208
	Entity Name: entity.tconstruct.arrow.name
	Entity's Exact location: 121.35, 58.48, -269.32
	Entity's Block location: World: (121,58,-270), Chunk: (at 9,3,2 in 7,-17; contains blocks 112,0,-272 to 127,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.19, -5.04, 0.24
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: Libertalia 2
	All players: 1 total; [EntityPlayerMP['Desv'/401, l='Libertalia 2', x=121.30, y=62.87, z=-269.30]]
	Chunk stats: ServerChunkCache: 578 Drop: 0
	Level seed: -1040154011
	Level generator: ID 07 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2783329 game time, 20765 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 34425 (now: false), thunder time: 108347 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by bonii-xx** [comment]
> at com.sosnitzka.taiga.traits.TraitInstable.afterHit(TraitInstable.java:52)

Seems to be caused by Taiga, please report it to them
