### ISSUE TITLE
Bug - 1.10.2 Latest Forge and Latest TinkersConstruct

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SlimeKnights/TinkersConstruct#2707]
[15:47:06] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:30) ~[bzc.class:?]
	at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:26) ~[bzc.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_184134_a(WorldClient.java:546) ~[bln.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_184148_a(WorldClient.java:534) ~[bln.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_184327_a(NetHandlerPlayClient.java:1554) ~[bll.class:?]
	at net.minecraft.network.play.server.SPacketSoundEffect.func_148833_a(SourceFile:90) ~[ic.class:?]
	at net.minecraft.network.play.server.SPacketSoundEffect.func_148833_a(SourceFile:12) ~[ic.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 17 more

This is seen anytime I build a tool.

Here is my modlist
[TheLoversRepack-v22.txt](https://github.com/SlimeKnights/TinkersConstruct/files/691732/TheLoversRepack-v22.txt)

**Comment by KnightMiner** [comment]
First off, there is no "latest Forge", an exact build number is needed.

Secondly, does this happen with just Tinkers and Forge? You have a quite sizable mod list, so its a little hard to debug especially when your issue seems to be with with the sound engine itself.

**Comment by P3rf3ctXZer0** [comment]
I will run some tests; till then please keep this issue open.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by KnightMiner** [comment]
Closing for lack of response, it has been nearly a year.
