### ISSUE TITLE
Crash on loading, may be related to settings/mod conflict

### ISSUE THREAD

**Issue by DelBreck** [SlimeKnights/TinkersConstruct#2713]
I use a fair few mods, but adding TiC is when it started crashing.  Got Mantle and updated JEI for dependencies, but I don't know if there's perhaps a conflict with another mod.

  IvToolkit (IvToolkit-1.2.8.4.jar)
  RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 1/9/17 12:09 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Building Bricks (buildingbricks)
Caused by: java.lang.RuntimeException: Could not load material from tconstruct:materials/vine.json
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:30)
	at com.hea3ven.buildingbricks.core.ProxyCommonBuildingBricks.onPreInitEvent(ProxyCommonBuildingBricks.java:86)
	at com.hea3ven.buildingbricks.core.ModBuildingBricks.preInit(ModBuildingBricks.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.JsonParseException: material does not have an id
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser$MaterialDeserializer.deserialize(MaterialParser.java:46)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser$MaterialDeserializer.deserialize(MaterialParser.java:37)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialParser.loadMaterialFromStream(MaterialParser.java:34)
	at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:26)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 222901784 bytes (212 MB) / 893911040 bytes (852 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	buildingbrickshooks{1.10.2-2.0.12} [Building Bricks Hooks] (minecraft.jar) 
	UCH	ivtoolkit{1.2.8.4} [IvToolkit] (minecraft.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	backpack{3.0.0} [Backpack] (backpack-3.0.0-1.10.2.jar) 
	UCE	buildingbricks{1.10.2-2.0.12} [Building Bricks] (BuildingBricks-1.10.2-2.0.12.jar) 
	UCH	chiselsandbits{11.7} [Chisels & Bits] (chiselsandbits-11.7.jar) 
	UCH	conquest{0.0.1} [Conquest Reforged] (conquest_reforged_MOD_v.1.4.51.jar) 
	UCH	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
	UCH	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	graves{1.10.2-b17-universal} [Graves Mod] (Graves-Mod-1.10.2.jar) 
	UCH	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCH	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCH	progressiveautomation{1.6.49} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.49.jar) 
	UCH	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UCH	seeddrop{1.0.0-1.10} [SeedDrop] (SeedDrop-1.0.0-1.10.jar) 
	UCH	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCH	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.2.8.4.jar)
  
RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1065.0' Renderer: 'AMD Radeon(TM) R6'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1065.0
	OpenGlRenderer: AMD Radeon(TM) R6
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by KnightMiner** [comment]
Update Building Bricks, this was fixed ages ago.
