### ISSUE TITLE
GAME CRASH WHEN I TRY TO OPEN

### ISSUE THREAD

**Issue by WoltenHabbar** [SlimeKnights/TinkersConstruct#2725]
I TRY TO OPEN MY MODPACK IN 1.10.2 WITH:

-BiomesOPlenty-1.10.2-5.0.0.2109-universal
-Chisel-MC1.10.2-0.0.7.7
-CodeChickenLib-1.10.2-2.5.0.178-universal
-ironchest-1.10.2-7.0.11.797
-jei_1.10.2-3.13.6.393
-Mantle-1.10.2-1.1.4
-OptiFine_1.10.2_HD_U_D4
-TConstruct-1.10.2-2.6.2
-Xaeros_Minimap_1.11.4_Forge_1.10.2
-XaerosWorldMap_b1.7_Forge_1.9.4
AND THE GAME CRASH BECAUSE THE TCONSTRUCT. HELP ME PLEASE <3

CRASH ERROR:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 1/16/17 11:05 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:217)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:538)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:217)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:538)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 133727840 bytes (127 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 Optifine OptiFine_1.10.2_HD_U_D4 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2202.jar) 
	UCHIJA	Forge{12.18.3.2202} [Minecraft Forge] (forge-1.10.2-12.18.3.2202.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJA	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	JEI{3.13.6.393} [Just Enough Items] (jei_1.10.2-3.13.6.393.jar) 
	UCHIJA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJA	XaeroMinimap{1.11.4} [Xaero's Minimap] (Xaeros_Minimap_1.11.4_Forge_1.10.2.jar) 
	UCHIJA	XaeroWorldMap{1.7} [Xaero's World Map] (XaerosWorldMap_b1.7_Forge_1.9.4.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 9.17.10.2884' Renderer: 'Intel(R) HD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2202
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.17.10.2884, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §lDefault 3D§r Lite        §l16w12a.zip
	Current Language: Português (Brasil)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 9.17.10.2884
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by ArukaAlter** [comment]
First off, avoid going full caps, it's not good conversation-wise on the internet.
Your game has only 512mb of RAM memory allocated, nowhere near enough to run a modded instance, this is not a problem with the mod.

**Comment by KnightMiner** [comment]
Like @ArukaAlter said, you need more RAM allocated. It is not a fault of Tinkers, modded Minecraft (and Minecraft in general) just needs a decent amount of RAM.

**Comment by WoltenHabbar** [comment]
ah, okay. Thanks and excuse me about the full caps! well job.
