### ISSUE TITLE
Tinkers construct Crash

### ISSUE THREAD

**Issue by SavageKiller13** [SlimeKnights/TinkersConstruct#2739]
I have a problem with Tinkers construct (And maybe other mods) where I get a crash (which EU2 catches). here is my crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/24/17 10:57 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
Caused by: java.lang.NoSuchMethodError: slimeknights.tconstruct.library.materials.BowMaterialStats.<init>(FFF)V
	at com.rwtema.extrautils2.modcompat.tcon.TConstructIntegration$1.addStats(TConstructIntegration.java:80)
	at com.rwtema.extrautils2.modcompat.tcon.TConstructIntegration.init(TConstructIntegration.java:166)
	at com.rwtema.extrautils2.backend.entries.EntryHandler.init(EntryHandler.java:76)
	at com.rwtema.extrautils2.ExtraUtils2.init(ExtraUtils2.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161471040 bytes (153 MB) / 1191706624 bytes (1136 MB) up to 2386558976 bytes (2276 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2560M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2215 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2215.jar) 
	UCHI	Forge{12.18.3.2215} [Minecraft Forge] (forge-1.10.2-12.18.3.2215.jar) 
	UCHI	actuallyadditions{1.10.2-r98} [Actually Additions] (ActuallyAdditions-1.10.2-r98.jar) 
	UCHI	BetterAchievements{0.3.0.28} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.28.jar) 
	UCHI	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHI	JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar) 
	UCHI	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UCHI	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.12.jar) 
	UCHI	mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
	UCHI	tconstruct{1.10.2-2.5.3.jenkins387} [Tinkers' Construct] (TConstruct-1.10.2-2.5.3.jar) 
	UCHI	exnihiloomnia{1.2.5} [Ex Nihilo Omnia] (exnihiloomnia-1.2.5.jar) 
	UCHE	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.2.0.jar) 
	UCHI	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UCHI	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHI	Schematica{1.7.8.149} [Schematica] (Schematica-1.10.2-1.7.8.149-universal.jar) 
	UCHI	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0 (1).jar) 
	UCHI	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0 (1).jar) 
	UCHI	worldedit{6.1.4-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.9836 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4200 '
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Soren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

I think it has something to do with the missing class ("Tesla API Class") but i'm not sure. I have looked all over to find a solutions but haven't found one. I did have Optifine installed then removed it and I still have this error. I have found that there are no other crash reports on this thread. All I need to know if if i need to get a new version of these mods or if I can get into one of the mod .jar files and add the class. Also Tinkers construct is a great mod. I only have this problem when I have EU2 installed.

**Comment by KnightMiner** [comment]
Update Tinkers.
