### ISSUE TITLE
Lumber axe causing Exception on Server when breaking trees

### ISSUE THREAD

**Issue by apex2top** [SlimeKnights/TinkersConstruct#2751]
Hey, I got this exception when i tried to break a tree.
The lumber axe was made out of wood, iron and duranite from the TAIGA-Addon. The block i hit, dissapeared (got invisible) but the tree was not cut down.

[20:58:33] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_102]
	at com.sosnitzka.taiga.traits.TraitAnalysing.getUpdateXP(TraitAnalysing.java:55) ~[TraitAnalysing.class:?]
	at com.sosnitzka.taiga.traits.TraitAnalysing.onBlockBreak(TraitAnalysing.java:38) ~[TraitAnalysing.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_224_TraitAnalysing_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:742) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:287) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by bonii-xx** [comment]
Can you reproduce it?

**Comment by apex2top** [comment]
Yes i can:

Every time i cut something the exception occures.

=== Exception same as shown above ===

Axe 1: Duranite - Iron - Wood
Axe 2: Treated Wood - Duranite - Carbon

It could be the Duranite from TAIGA, but I am not sure.

> at com.sosnitzka.taiga.traits.TraitAnalysing.getUpdateXP(TraitAnalysing.java:55)

**Comment by apex2top** [comment]
Seems to be TAIGA related... [https://github.com/TeamFRM/TAIGA/issues/111](TAIGA-Ticket)
