### ISSUE TITLE
Travel Wings pulled from ProjectE Transmutation table causes crash loop

### ISSUE THREAD

**Issue by Trisscar05** [SlimeKnights/TinkersConstruct#2760]
I suspect this is a recognized issue already, so I'm mostly just wondering if there's a way to easily remove the offending item from my inventory. Other than NBTExplorer that is, as any changes I make there are reverted as soon as the world attempts to load. 
I'd rather not remove Tinker's outright due to a high level Iguana pick, and the same for my entire playerdata file due to possible issues with ProjectE and how it stores what you have in the Transmu-table (though if no other option appears those are the next steps). Already attempted to remove Battlegear, which merely slightly changed the crash log to not mention it. Is there an easy way to get to and edit the item IDs or something?

[05/2/2017 05:09:49 AM] java.lang.NullPointerException: Ticking player
[05/2/2017 05:09:49 AM] 	at tconstruct.armor.items.TravelWings.onArmorTick(TravelWings.java:41)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319)
[05/2/2017 05:09:49 AM] 	at mods.battlegear2.api.core.InventoryPlayerBattle.func_70429_k(InventoryPlayerBattle.java:189)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[05/2/2017 05:09:49 AM] 
[05/2/2017 05:09:49 AM] 
[05/2/2017 05:09:49 AM] A detailed walkthrough of the error, its code path and all known details is as follows:
[05/2/2017 05:09:49 AM] ---------------------------------------------------------------------------------------
[05/2/2017 05:09:49 AM] 
[05/2/2017 05:09:49 AM] -- Head --
[05/2/2017 05:09:49 AM] Stacktrace:
[05/2/2017 05:09:49 AM] 	at tconstruct.armor.items.TravelWings.onArmorTick(TravelWings.java:41)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319)
[05/2/2017 05:09:49 AM] 	at mods.battlegear2.api.core.InventoryPlayerBattle.func_70429_k(InventoryPlayerBattle.java:189)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
[05/2/2017 05:09:49 AM] 
[05/2/2017 05:09:49 AM] -- Player being ticked --
[05/2/2017 05:09:49 AM] Details:
[05/2/2017 05:09:49 AM] 	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
[05/2/2017 05:09:49 AM] 	Entity ID: 226
[05/2/2017 05:09:49 AM] 	Entity Name: **MINECRAFTUSERNAME**
[05/2/2017 05:09:49 AM] 	Entity's Exact location: -102.11, 48.00, 2.18
[05/2/2017 05:09:49 AM] 	Entity's Block location: World: (-103,48,2), Chunk: (at 9,3,2 in -7,0; contains blocks -112,0,0 to -97,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
[05/2/2017 05:09:49 AM] 	Entity's Momentum: 0.00, -0.08, 0.00
[05/2/2017 05:09:49 AM] Stacktrace:
[05/2/2017 05:09:49 AM] 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[05/2/2017 05:09:49 AM] 
[05/2/2017 05:09:49 AM] -- Ticking connection --
[05/2/2017 05:09:49 AM] Details:
[05/2/2017 05:09:49 AM] 	Connection: net.minecraft.network.NetworkManager@5b62820b
[05/2/2017 05:09:49 AM] Stacktrace:
[05/2/2017 05:09:49 AM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[05/2/2017 05:09:49 AM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[05/2/2017 05:09:49 AM] 
[05/2/2017 05:09:49 AM] -- System Details --
[05/2/2017 05:09:49 AM] Details:
[05/2/2017 05:09:49 AM] 	Minecraft Version: 1.7.10
[05/2/2017 05:09:49 AM] 	Operating System: Windows 7 (amd64) version 6.1
[05/2/2017 05:09:49 AM] 	Java Version: 1.8.0_111, Oracle Corporation
[05/2/2017 05:09:49 AM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[05/2/2017 05:09:49 AM] 	Memory: 539330744 bytes (514 MB) / 1024770048 bytes (977 MB) up to 1056309248 bytes (1007 MB)
[05/2/2017 05:09:49 AM] 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -Xms256M -Xmx1024M -XX:MetaspaceSize=128M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
[05/2/2017 05:09:49 AM] 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[05/2/2017 05:09:49 AM] 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
[05/2/2017 05:09:49 AM] 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 112 mods loaded, 112 mods active
[05/2/2017 05:09:49 AM] 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	NotEnoughItems{1.0.4.105} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.105-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	VeinMiner_coremod{0.27.1_build.unknown} [Core mod] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	asielib{0.3.8} [asielib] (AsieLib-1.7.10-0.3.8.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	atum{0.6} [Atum] (Atum-1.7.10-0.6.60.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Automagy{0.23} [Automagy] (Automagy-1.7.10-0.23.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	betterstorage{0.12.0.124} [BetterStorage] (BetterStorage-1.7.10-0.12.0.124.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Botania{r1.7-219} [Botania] (Botania r1.7-219.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenters Blocks v3.3.6 - MC 1.7.10.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	lootablebodies{1.3.5} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.5-backport.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	dungeonpack{1.7.10-1.0} [Dungeon Pack] (dungeonpack-1.7.10-1.0.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ExtraUtilities{1.2.4b} [Extra Utilities] (extrautilities-1.2.4b.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
[05/2/2017 05:09:49 AM] 	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
[05/2/2017 05:09:49 AM] Checking for updated files!
[05/2/2017 05:09:50 AM] No updates found!

**Comment by bonii-xx** [comment]
We don't support 1.7.10 anymore.
