### ISSUE TITLE
Progectile Weaponry

### ISSUE THREAD

**Issue by TerraVenator** [SlimeKnights/TinkersConstruct#2799]
i don't know whats wrong with it, it says it's the projectie stuff, but heres the crash report: ---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 3/11/17 3:24 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/ProjectileWeapon
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/ProjectileWeapon
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.weaponry.ProjectileWeapon
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.tools.ToolCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 133094728 bytes (126 MB) / 322564096 bytes (307 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UC	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UC	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UC	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UC	dynamicswordskills{1.7.10-1.7} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.7.jar) 
	UC	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UC	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	MovingWorld{1.7.10-1.8.1} [Moving World] (movingworld-1.7.10-1.8.1.jar) 
	UC	ArchimedesShipsPlus{1.7.10-1.8.1} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.1.jar) 
	UC	Backpack{2.0.0} [Backpack] (Backpacks-Mod.jar) 
	UC	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UC	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UC	lootablebodies{1.3.7} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.7.jar) 
	UC	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UC	dragonrealm{1.2a} [Dragon Realm] (DragonRealm_v1.2a.jar) 
	UC	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UC	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
	UC	ExtraMobs{1.01} [ExtraMobs] (ExtraMobs Mod v1.01.zip) 
	UC	gvc{0.6.1} [§aGliby's§f Voice Chat Mod] (GlibysVC-1.7.10-0.6.2a.jar) 
	UC	Growthcraft{1.7.10-2.7.0} [Growthcraft] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Cellar{1.7.10-2.7.0} [Growthcraft Cellar] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Apples{1.7.10-2.7.0} [Growthcraft Apples] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Bamboo{1.7.10-2.7.0} [Growthcraft Bamboo] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Bees{1.7.10-2.7.0} [Growthcraft Bees] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Fishtrap{1.7.10-2.7.0} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Grapes{1.7.10-2.7.0} [Growthcraft Grapes] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Hops{1.7.10-2.7.0} [Growthcraft Hops] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Milk{1.7.10-2.7.0} [Growthcraft Milk] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	Growthcraft|Rice{1.7.10-2.7.0} [Growthcraft Rice] (growthcraft-1.7.10-2.7.0-complete.jar) 
	UC	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UC	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UC	levelup{0.4} [Level Up!] (Level-Up-Mod-1.7.10.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UC	mybukkitcommands{1710.01} [MybukkitCommands] (mycommands-1710.01.jar) 
	UC	Mystcraft{0.12.3.03} [Mystcraft] (mystcraft-1.7.10-0.12.3.03.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UC	rfpr{7.0.0} [Real First-Person Render] (realistic-first-person-rendering-mod-1.7.10.jar) 
	UC	ropebridge{1.3} [Rope Bridge] (Rope-Bridge-Mod-1.7.10.jar) 
	UC	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UC	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UC	SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UE	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UC	teamup{1.1.2:1.7.10} [TeamUp] (TeamUp-1.1.2-1.7.10.jar) 
	UC	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UC	tc{4.3.0_002} [Traincraft] (Traincraft-Mod-1.7.10.jar) 
	UC	VeinMiner{0.35.2_1.7.10-e134bd4} [Vein Miner] (VeinMiner-1.7.10-0.35.2.487+e134bd4.jar) 
	UC	VeinMinerModSupport{0.35.2_1.7.10-e134bd4} [Mod Support] (VeinMiner-1.7.10-0.35.2.487+e134bd4.jar) 
	UC	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UC	witcherycmd{1.1} [WitcheryCommand] (WitcheryCommand-1.1.jar) 
	UC	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by KnightMiner** [comment]
It is hard to tell exactly what is going on there, but you both have the unsupported mod Optifine and 1.7.10 builds are no longer supported, so this issue is invalid.

Try removing Optifine, and redownload Tinkers Construct and Mantle to see if either fixes the issue.
