### ISSUE TITLE
[Crash report] Crash on start up

### ISSUE THREAD

**Issue by ml0130** [SlimeKnights/TinkersConstruct#2877]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.368.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/1/17 5:32 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBUtilities (ftbu)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_150895_a(Lnet/minecraft/item/Item;Lnet/minecraft/creativetab/CreativeTabs;Ljava/util/List;)V
	at com.feed_the_beast.ftbl.lib.client.DrawableObjectList.<init>(DrawableObjectList.java:59)
	at com.feed_the_beast.ftbu.integration.TiCIntegration.onGuideEvent(TiCIntegration.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_431_TiCIntegration_onGuideEvent_ClientGuideEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at com.feed_the_beast.ftbu.gui.Guides.func_110549_a(Guides.java:171)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at com.feed_the_beast.ftbu.client.FTBUClient.postInit(FTBUClient.java:45)
	at com.feed_the_beast.ftbu.FTBU.onPostInit(FTBU.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 607140840 bytes (579 MB) / 1981284352 bytes (1889 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2286 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2286.jar) 
	UCHIJ	forge{13.20.0.2286} [Minecraft Forge] (forge-1.11.2-13.20.0.2286.jar) 
	UCHIJ	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJ	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHIJ	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJ	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.jar) 
	UCHIJ	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHIJ	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJ	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCHIJ	biomesoplenty{6.1.0.2205} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2205-universal.jar) 
	UCHIJ	guideapi{1.11-2.1.0-51} [Guide-API] (Guide-API-1.11-2.1.0-51.jar) 
	UCHIJ	bloodmagic{1.11-2.1.9-78} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.9-78.jar) 
	UCHIJ	bookshelf{1.5.0.368} [Bookshelf] (Bookshelf-1.11.2-1.5.0.368.jar) 
	UCHIJ	botania{r1.9-343} [Botania] (Botania r1.9-343.jar) 
	UCHIJ	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJ	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCHIJ	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJ	darkutils{1.2.0.126} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.126.jar) 
	UCHIJ	forestry{5.3.3.95} [Forestry] (forestry_1.11.2-5.3.3.95.jar) 
	UCHIJ	eleccore{1.7.418} [ElecCore] (ElecCore-1.11-1.7.418.jar) 
	UCHIJ	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.3} [Storage Drawers] (StorageDrawers-1.11.2-4.2.3.jar) 
	UCHIJ	bitdrawers{0.41} [Drawers & Bits] (DrawersBits-1.11.2-0.41.jar) 
	UCHIJ	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCHIJ	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.1.jar) 
	UCHIE	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.0.jar) 
	UCHIJ	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCHIJ	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJ	jei{4.3.3.270} [Just Enough Items] (jei_1.11.2-4.3.3.270.jar) 
	UCHIJ	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJ	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJ	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJ	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJ	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJ	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCHIJ	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJ	refinedstorage{1.4.4} [Refined Storage] (refinedstorage-1.4.4.jar) 
	UCHIJ	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCHIJ	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJ	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJ	tconstruct{1.11.2-2.7.0.6} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.6.jar) 
	UCHIJ	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJ	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.368.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 2500'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r106.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* bloodmagic|API (1.11-2.1.9-78) from BloodMagic-1.11-2.1.9-78.jar
		* BotaniaAPI (86) from Botania r1.9-343.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* compatlayer (0.2.5) from compatlayer-1.11.2-0.2.5.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.418.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.418.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.3.95.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.3.95.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* Guide-API|API (1.11-2.1.0-51) from Guide-API-1.11-2.1.0-51.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.12.0) from jei_1.11.2-4.3.3.270.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* PsiAPI (4) from Psi-r1.1-47.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* veinminerApi (0.3) from VeinMiner-1.11-0.35.3.605+dad98e1.jar

**Comment by bonii-xx** [comment]
>net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTBUtilities (ftbu)
Caused by: java.lang.NoSuchMethodError: 

You're in the Tinkers github, not ftb utils.
