### ISSUE TITLE
Tinkers Conflict with Buildcraft

### ISSUE THREAD

**Issue by TensorTime** [SlimeKnights/TinkersConstruct#2881]
Simple setup.  With Curse client create new 1.11.2 profile and select any recent version of forge (.2282-.2286)

Install nothing but Buildcraft and Tinkers and get the following crash.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/1/17 2:52 PM
Description: Initializing game

java.lang.IllegalStateException: Failed to set the frozen variant of tconstruct:blocks/fluids/molten_metal!
	at buildcraft.lib.client.render.fluid.FluidRenderer.onTextureStitchPre(FluidRenderer.java:65)
	at buildcraft.lib.BCLibEventDist.textureStitchPre(BCLibEventDist.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_BCLibEventDist_textureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:90)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:500)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at buildcraft.lib.client.render.fluid.FluidRenderer.onTextureStitchPre(FluidRenderer.java:65)
	at buildcraft.lib.BCLibEventDist.textureStitchPre(BCLibEventDist.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_BCLibEventDist_textureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:90)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:500)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Mac OS X (x86_64) version 10.12.4
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 924839016 bytes (881 MB) / 1374683136 bytes (1311 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2286 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2286.jar) 
	UCH	forge{13.20.0.2286} [Minecraft Forge] (forge-1.11.2-13.20.0.2286.jar) 
	UCH	buildcraftlib{7.99.1} [BuildCraft Lib] (buildcraft-7.99.1.jar) 
	UCH	buildcraftcore{7.99.1} [BuildCraft] (buildcraft-7.99.1.jar) 
	UCH	buildcraftfactory{7.99.1} [BC Factory] (buildcraft-7.99.1.jar) 
	UCH	buildcrafttransport{7.99.1} [BC Transport] (buildcraft-7.99.1.jar) 
	UCH	buildcraftbuilders{7.99.1} [BC Builders] (buildcraft-7.99.1.jar) 
	UCH	buildcraftenergy{7.99.1} [BC Energy] (buildcraft-7.99.1.jar) 
	UCH	buildcraftrobotics{7.99.1} [BC Robotics] (buildcraft-7.99.1.jar) 
	UCH	buildcraftsilicon{7.99.1} [BC Silicon] (buildcraft-7.99.1.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	tconstruct{1.11.2-2.7.0.6} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.6.jar) 
	Loaded coremods (and transformers): 
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: forge-13.20.0.2286
	LWJGL: 2.9.2
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-10.24.45, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.

Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz

**Comment by LuigiHutch** [comment]
BuildCraft issue, I believe it is the same issue as: https://github.com/BuildCraft/BuildCraft/issues/3534

**Comment by KristjanKr** [comment]
Can confirm, with crash log: https://paste.ee/p/Tc5FX

**Comment by spideruk07** [comment]
so its buildcraft causing crash not tinkers ??

**Comment by TensorTime** [comment]
My understanding is they have fixed it in the upcoming release.

**Comment by LuigiHutch** [comment]
Fixed in BC 7.99.3. This can now be closed :D
