### ISSUE TITLE
game crash at startup

### ISSUE THREAD

**Issue by spideruk07** [SlimeKnights/TinkersConstruct#2890]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Failed to set the frozen variant of tconstruct:blocks/fluids/molten_metal!

i have 48 mods installed all works fine until i install tinkers
crash report as follows;

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/5/17 3:44 PM
Description: Initializing game

java.lang.IllegalStateException: Failed to set the frozen variant of tconstruct:blocks/fluids/molten_metal!
	at buildcraft.lib.client.render.fluid.FluidRenderer.onTextureStitchPre(FluidRenderer.java:65)
	at buildcraft.lib.BCLibEventDist.textureStitchPre(BCLibEventDist.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_137_BCLibEventDist_textureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:90)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:500)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at buildcraft.lib.client.render.fluid.FluidRenderer.onTextureStitchPre(FluidRenderer.java:65)
	at buildcraft.lib.BCLibEventDist.textureStitchPre(BCLibEventDist.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_137_BCLibEventDist_textureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:90)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:500)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2185204408 bytes (2083 MB) / 2798649344 bytes (2669 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2294 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2294.jar) 
	UCH	forge{13.20.0.2294} [Minecraft Forge] (forge-1.11.2-13.20.0.2294.jar) 
	UCH	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCH	actuallyadditions{1.11.2-r107} [Actually Additions] (ActuallyAdditions-1.11.2-r107.jar) 
	UCH	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCH	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.jar) 
	UCH	baubles{1.4.4} [Baubles] (Baubles-1.11-1.4.4.jar) 
	UCH	guideapi{1.11-2.1.0-51} [Guide-API] (Guide-API-1.11-2.1.0-51.jar) 
	UCH	bloodmagic{1.11-2.1.9-78} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.9-78.jar) 
	UCH	botania{r1.9-343} [Botania] (Botania r1.9-343.jar) 
	UCH	buildcraftlib{7.99.1} [BuildCraft Lib] (buildcraft-7.99.1.jar) 
	UCH	buildcraftcore{7.99.1} [BuildCraft] (buildcraft-7.99.1.jar) 
	UCH	buildcraftfactory{7.99.1} [BC Factory] (buildcraft-7.99.1.jar) 
	UCH	buildcrafttransport{7.99.1} [BC Transport] (buildcraft-7.99.1.jar) 
	UCH	buildcraftbuilders{7.99.1} [BC Builders] (buildcraft-7.99.1.jar) 
	UCH	buildcraftenergy{7.99.1} [BC Energy] (buildcraft-7.99.1.jar) 
	UCH	buildcraftrobotics{7.99.1} [BC Robotics] (buildcraft-7.99.1.jar) 
	UCH	buildcraftsilicon{7.99.1} [BC Silicon] (buildcraft-7.99.1.jar) 
	UCH	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCH	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCH	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCH	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCH	endertanks{1.5.4} [EnderTanks] (endertanks-1.11.0-1.5.4.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCH	zerocore{1.11.2-0.1.0.5} [Zero CORE] (zerocore-1.11.2-0.1.0.5.jar) 
	UCH	bigreactors{1.11.2-0.4.5.28} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.28.jar) 
	UCH	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCH	forestry{5.3.3.95} [Forestry] (forestry_1.11.2-5.3.3.95.jar) 
	UCH	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCH	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCH	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCH	inventorytweaks{1.62+beta.86.e69c6bf} [Inventory Tweaks] (InventoryTweaks-1.62+beta.86.jar) 
	UCH	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCH	jei{4.3.4.272} [Just Enough Items] (jei_1.11.2-4.3.4.272.jar) 
	UCH	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	metamorph{1.1.2} [Metamorph] (metamorph-1.1.2-1.11.2.jar) 
	UCH	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCH	reborncore{2.14.2.94} [Reborn Core] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCH	reborncore-mcmultipart{2.14.2.94} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCH	refinedstorage{1.4.4} [Refined Storage] (refinedstorage-1.4.4.jar) 
	UCH	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCH	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCH	tconstruct{1.11.2-2.7.0.9} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.9.jar) 
	UCH	techreborn{2.2.1.142} [Tech Reborn] (TechReborn-1.11.2-2.2.1.142-universal.jar) 
	UCH	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCH	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.514' Renderer: 'AMD Radeon R7 200 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.2.94
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-13.20.0.2294
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.14008 Compatibility Profile Context 21.19.137.514, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Unity-1.4.0.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-6600K APU with Radeon(tm) HD Graphics 

any help would be appreciated

**Comment by bonii-xx** [comment]
#2881
