### ISSUE TITLE
TConstruct 1.7.10-1.8.8 Crashes when pressing the G key.

### ISSUE THREAD

**Issue by Runburner** [SlimeKnights/TinkersConstruct#2966]
Whenever I press G whether it be typing or just even pressing it, the game full on crashes and spits this out.

java.lang.NoSuchFieldError: isKeyBindingPressed

We rolled back to 1.7.10-1.8.7 and it no longer happens. 1.8.8 is the latest version that is a release and we would like to have it.

**Comment by Runburner** [comment]
Here is the full error code.

java.lang.NoSuchFieldError: isKeyBindingPressed
	at tconstruct.client.ArmorControls.keyEventSpecial(ArmorControls.java:101)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_533_ArmorControls_keyEventSpecial_KeyBindingPressedEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at modwarriors.notenoughkeys.keys.KeyEvents.refreshBindings(KeyEvents.java:73)
	at modwarriors.notenoughkeys.keys.KeyEvents.onKeyEvent(KeyEvents.java:44)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_694_KeyEvents_onKeyEvent_KeyInputEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1873)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported, and based on no one else has reported this issue in the [year and a half](https://minecraft.curseforge.com/projects/tinkers-construct/files/2264246) since that version was released, this is probably an issue with your setup.

The specific changes in that version are related to updating to the latest NotEnoughKeys API, so there is a good chance you are using the wrong version of NotEnoughKeys.
