### ISSUE TITLE
Minecraft with Huzuni crash

### ISSUE THREAD

**Issue by patrol1120** [SlimeKnights/TinkersConstruct#2971]
Hello
Can somebody help me when i started minecraft client 1.7.10 with huzuni i get crash 
I think  it is  something with java version 
Here is crashlog:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 13/06/17 21:11
Description: Initializing game

java.lang.IllegalAccessError: tried to access class c from class net.kf
	at net.kf.<clinit>(kf.java)
	at net.fb.a(fb.java)
	at net.minecraft.client.v.d(v.java)
	at net.minecraft.client.v.m(v.java)
	at net.minecraft.client.main.Main.main(Main.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at meinkraft.aaaaAAaAaaAa.uioy(Unknown Source)
	at meinkraft.aaaaAAaAaaAa._iet(Unknown Source)
	at meinkraft.Loader.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:90)
	at net.minecraft.Launcher.replace(Launcher.java:147)
	at net.minecraft.Launcher$1.run(Launcher.java:88)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.kf.<clinit>(kf.java)
	at net.fb.a(fb.java)
	at net.minecraft.client.v.d(v.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.v.m(v.java)
	at net.minecraft.client.main.Main.main(Main.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at meinkraft.aaaaAAaAaaAa.uioy(Unknown Source)
	at meinkraft.aaaaAAaAaaAa._iet(Unknown Source)
	at meinkraft.Loader.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:90)
	at net.minecraft.Launcher.replace(Launcher.java:147)
	at net.minecraft.Launcher$1.run(Launcher.java:88)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 431555880 bytes (411 MB) / 676855808 bytes (645 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MinecraftByZyczu
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7900 Series GL version 4.5.13474 Compatibility Profile Context 22.19.162.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Thanks!!

**Comment by ArukaAlter** [comment]
1.7 is no longer supported. Huzuni is a hacked client, which is also not supported.
