### ISSUE TITLE
Tconstruct crash version 1.8.8

### ISSUE THREAD

**Issue by MrXromik** [SlimeKnights/TinkersConstruct#2975]
`java.lang.IllegalArgumentException: Don't know how to add class tconstruct.mechworks.entity.item.ExplosivePrimed! Report this error to mod author.
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:717)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:434)
	at net.minecraft.entity.EntityTrackerEntry.func_73125_b(EntityTrackerEntry.java:555)
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:131)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:315)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1010)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported. That specific build was released nearly two years ago and no one else has had that issue, so it is probably on your end (some core mod or wrong version of a mod/forge)
