### ISSUE TITLE
Minecraft crashes when destroying blocks with shaders mod in survival

### ISSUE THREAD

**Issue by Hallk26** [SlimeKnights/TinkersConstruct#2990]
So I haven't played minecraft for a few years now and decided to reinstall it, and as I've got a beefy laptop I decided to do an amazing survival series on YouTube instead of a csgo video, because you know, minecraft is obviously better that csgo so I downloaded minecraft but the graphics where so bad I decided to download shaders, and my computer can run them decently (60-40fps in creative with texture pack) but in survival whenever I destroy a block it crashes, _saying_
----
Unreported exception thrown!
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    bvu.f()V @96: aload_0
  Reason:
    Type top (current frame, locals[0]) is not assignable to reference type
  Current Frame:
    bci: @96
    flags: { }
    locals: { }
    stack: { }
  Bytecode:
    0x0000000: 033c 1b07 a200 5c10 0e1b 683d 2ab4 002f
    0x0000010: 1c07 602a b400 242a b400 322a b400 2f1c
    0x0000020: 0760 2eb8 0038 b600 3d8d b600 40b8 0044
    0x0000030: 4f2a b400 2f1c 0760 0460 2ab4 0024 2ab4
    0x0000040: 0032 2ab4 002f 1c07 6004 602e b800 38b6
    0x0000050: 0046 8db6 0048 b800 444f 8401 01a7 ffa5
    0x0000060: 2ab4 002f b800 52b1                    
  Stackmap Table:
    append_frame(@2,Integer)
    chop_frame(@96,2)

	at cgd$a.a(SourceFile:114)
	at cgd$a.<init>(SourceFile:100)
	at bvk.a(SourceFile:45)
	at buw.a(SourceFile:2100)
	at buo.a(SourceFile:1308)
	at buo.b(SourceFile:1188)
	at buo.a(SourceFile:1033)
	at bhz.az(SourceFile:1023)
	at bhz.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
----
I suppose I have not dedicated enough memory to minecraft or it's some glitch with shaders mod. Plz help and thanks for reading

**Comment by KnightMiner** [comment]
This issue has nothing to do with Tinkers Construct, I am pretty sure you are not even using Forge. Report to the proper people for shaders, we are not a general tech support forum.

**Comment by Hallk26** [comment]
Ok :) sorry
