### ISSUE TITLE
Smeltery fails writing fluid NBT

### ISSUE THREAD

**Issue by thundR** [SlimeKnights/TinkersConstruct#2994]
I'm getting a similar error to #2402 , but thanks to the logger you added, I have a bit more info, and it isn't crashing our server. It is occurring multiple times a second, and I assume it happens every time it tries to write NBT. This is just an example, the fluids in the smeltery changed as people used it, but it always had blood. 

It looks like an interaction with EnderIO fluid conduits, and something trying to write empty NBT data. Could fluid conduits introduce a ghost empty fluid into the smeltery?

https://pastebin.com/85XqQQ7d

EDIT:
Breaking and reconstructing the smeltery elsewhere stopped the errors, this time chunk boundaries were respected, is that still a thing?

**Comment by bonii-xx** [comment]
I can't open the log, is pastebin down? Anyway, I suspect it somehow always defaults to blood, even when it's not, for some weird reason. We don't know if it's EIO related, or if it's on our or their side. Without a way to reproduce it we can't really fix it either way.

**Comment by thundR** [comment]
The log is up for me, link works fine. I'll paste it in its entirety here:

`[23:57:04] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Empty string not allowed
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:240) [SimpleNetworkWrapper.class:?]
        at slimeknights.tconstruct.common.TinkerNetwork.sendToAll(TinkerNetwork.java:73) [TinkerNetwork.class:?]
        at slimeknights.tconstruct.smeltery.tileentity.TileSmeltery.onTankChanged(TileSmeltery.java:355) [TileSmeltery.class:?]
        at slimeknights.tconstruct.library.smeltery.SmelteryTank.fill(SmelteryTank.java:115) [SmelteryTank.class:?]
        at com.enderio.core.common.fluid.CapabilityFluidWrapper.fill(CapabilityFluidWrapper.java:29) [CapabilityFluidWrapper.class:?]
        at crazypants.enderio.conduit.liquid.LiquidConduit.pushLiquid(LiquidConduit.java:263) [LiquidConduit.class:?]
        at crazypants.enderio.conduit.liquid.LiquidConduit.doExtract(LiquidConduit.java:138) [LiquidConduit.class:?]
        at crazypants.enderio.conduit.liquid.LiquidConduit.updateEntity(LiquidConduit.java:97) [LiquidConduit.class:?]
        at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:251) [TileConduitBundle.class:?]
        at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40) [TileEntityBase.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1804) [aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Empty string not allowed
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ee.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128) ~[dr.class:?]
        at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:100) ~[FluidStack.class:?]
        at slimeknights.tconstruct.smeltery.network.SmelteryFluidUpdatePacket.toBytes(SmelteryFluidUpdatePacket.java:65) ~[SmelteryFluidUpdatePacket.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[minecraft_server.1.10.2.jar:?]
        ... 24 more`

**Comment by miiichael** [comment]
I just experienced this with a brand new smeltery on an hours-old server. 1.11, so no EnderIO (sadly for some!).

forge-1.11.2-13.20.1.2454, TConstruct-1.11.2-2.7.1.34, and a bunch of others.

In-game, the smeltery is reporting as containing only seared stone, though the server log is of course complaining about the blood in there too (everyone's smeltery ends up with blood in it at one point or another, right?). The server doesn't die, but the client gets kicked when I try to switch fluids in the smeltery (even though it thinks there's only one in there).

The last 1000 lines of fml-server-latest.log can be found [here](https://github.com/SlimeKnights/TinkersConstruct/files/1246184/2994.log.txt).

**Comment by jefferyrlc** [comment]
Confirmed this still happens in 1.12.2

Forge: forge-1.12.2-14.23.0.2491-universal
Modlist:
ActuallyAdditions-1.12.2-r124
AppleSkin-mc1.12-1.0.9
appliedenergistics2-rv5-stable-1
AutoRegLib-1.3-15
Baubles-1.12-1.5.1
BetterFps-1.4.8
BiblioCraft[v2.4.3][MC1.12.0]
BiomesOPlenty-1.12.2-7.0.1.2302-universal
BrandonsCore-1.12-2.3.3.132-universal
Chameleon-1.12-4.1.3
ChickenChunks-1.12-2.4.0.70-universal
Chisel-MC1.12-0.0.14.18
cnoapm-mcv1.12-nojson
CodeChickenLib-1.12-3.1.3.313-universal
CoFHCore-1.12-4.3.6.14-universal
CoFHWorld-1.12-1.0.1.8-universal
ComputerCraft1.80pr1
CTM-MC1.12-0.2.3.9
densemetals-1.12.2-1.0.2
Draconic-Evolution-1.12-2.3.4.265-universal
EnderStorage-1.12-2.4.0.122-universal
extrautils2-1.12-1.6.5
ExtremeReactors-1.12-0.4.5.44
FastLeafDecay-v14
foamfix-0.8.0-1.12-anarchy
Forgelin-1.5.1
furniture-4.1.5-1.12
HammerCore-1.12.2-1.9.5.2
industrialcraft-2-2.8.16-ex112
InventoryTweaks-1.63
ironchest-1.12.2-7.0.34.820
jei_1.12.1-4.7.8.95
journeymap-1.12.2-5.5.2b1
Mantle-1.12-1.3.1.21
mcjtylib-1.12-2.4.5
MCMultiPart-2.3.3
Mekanism-1.12.1-9.4.1.326
MekanismGenerators-1.12.1-9.4.1.326
moartinkers-0.5.4
natura-1.12-4.3.0.23
NotEnoughItems-1.12-2.4.0.231-universal
OptiFine_1.12.2_HD_U_C6
oreberries-1.12.x-0.4.0
plustic-6.3.2.0
prefab-1.3.0.12
ProjectE-1.12-PE1.1.0
Psi-r1.1-58
RedstoneFlux-1.12-2.0.1.2-universal
refinedstorage-1.5.21
refinedstorageaddons-0.2
rflux-1.12-0.1.2
rftools-1.12-7.13
rftoolsdim-1.12-5.05
SolarFluxReborn_1.12.2-3.42r
StorageDrawers-1.12.1-5.3.3
TConstruct-1.12-2.7.4.34
theoneprobe-1.12-1.4.19
ThermalDynamics-1.12-2.3.6.13-universal
ThermalExpansion-1.12-5.3.6.20-universal
ThermalFoundation-1.12-2.3.6.16-universal
topaddons-1.12.2-1.1.3
torohealth-1.12.2-11
UniDict-1.12.2-1.2
UnlimitedChiselWorks-0.1.5
WanionLib-1.12.2-1.2
zerocore-1.12-0.1.1.0

Attached is my server log file containing the issue
[fml-junk-earlystartup.zip](https://github.com/SlimeKnights/TinkersConstruct/files/1504783/fml-junk-earlystartup.zip)

**Comment by bonii-xx** [comment]
I think after along time I've finally found the cause.. Next update will tell.

**Comment by Possemaster** [comment]
I have the same issue on a All the Mods 3 version 5.3 and it is easy to reproduce.

Please check video for clear reproduce.

We experienced the issue on our server. 
Sand will smelt but not display correct and crash the game if you select another liquid in the smeltery.
So I checked if this issue could be reproduced in a singleplayer session, no issues. (see video 1) [ [https://youtu.be/qZ_mE2x-UhQ](https://youtu.be/qZ_mE2x-UhQ) ])
I started a localhost server with new server files and experianced the same issue with tinkers as I have on the public server. (see video 2 [ [https://youtu.be/9lr8-5_47lk](https://youtu.be/9lr8-5_47lk) ])

If you check the fml-junk-earlystartup.log you will see that the server is outputting Exceptions from line 21686 concerning Tinkers.
And on line 30861 you see below and after that the exception keep on coming:
`[00:32:00] [Server thread/ERROR] [tconstruct-TinkerSmeltery]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[00:32:00] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.stone/4320mb
[00:32:00] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.glass/31000mb
[00:32:05] [Netty Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel tconstruct`

[fml-junk-earlystartup.log](https://github.com/AllTheMods/ATM-3/files/1544144/fml-junk-earlystartup.log)
[fml-server-1.log](https://github.com/AllTheMods/ATM-3/files/1544145/fml-server-1.log)
[fml-server-latest.log](https://github.com/AllTheMods/ATM-3/files/1544146/fml-server-latest.log)
[latest.log](https://github.com/AllTheMods/ATM-3/files/1544147/latest.log)

**Comment by besplash** [comment]
> 
> 
> I think after along time I've finally found the cause.. Next update will tell.

Still kicking players on the latest 1.10.2 version. Is this something you will fix or are you pretty much done with it?

**Comment by KnightMiner** [comment]
We've been done with 1.10 for awhile, there really is no reason to not to move on as nearly all 1.10 mods ported.
