### ISSUE TITLE
Crash Exception

### ISSUE THREAD

**Issue by R4D0N** [SlimeKnights/TinkersConstruct#3017]
I'm not really an expert when it comes to java but I keep crashing due to this
`Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: 16
	at tconstruct.smeltery.blocks.SmelteryBlock.func_149673_e(SmelteryBlock.java:137)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4549)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at tconstruct.smeltery.model.SmelteryRender.renderWorldBlock(SmelteryRender.java:37)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

can anyone help?

**Comment by KnightMiner** [comment]
Normally I'd say provide mod versions and a full crash report, but I can tell from the tiny bit you gave me that its 1.7 as its using the old packaging. 1.7.10 is no longer supported, but since no one else has had this crash in the year and a half since it was released I am betting it is an mod conflict. Probably Optifine if I had to guess.
