### ISSUE TITLE
crash on world load with pokecube

### ISSUE THREAD

**Issue by Oxosorrel** [SlimeKnights/TinkersConstruct#3030]
When creating a new world with only Pokecubes' mods, and TinkerConstruct, using latest forge and latest copies of the mods, game crashes on entering a new world. 

Description: Ticking player

java.lang.ClassCastException: slimeknights.tconstruct.library.capability.piggyback.TinkerPiggybackHandler cannot be cast to pokecube.core.interfaces.IPokemob
	at pokecube.core.interfaces.capabilities.CapabilityPokemob.getPokemobFor(CapabilityPokemob.java:21)
	at pokecube.mobs.PokecubeMobs.livingUpdate(PokecubeMobs.java:518)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_PokecubeMobs_livingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:544)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2080)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at pokecube.core.interfaces.capabilities.CapabilityPokemob.getPokemobFor(CapabilityPokemob.java:21)
	at pokecube.mobs.PokecubeMobs.livingUpdate(PokecubeMobs.java:518)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_PokecubeMobs_livingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:544)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2080)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 2331
	Entity Name: Oxosorrel
	Entity's Exact location: -136.50, 64.00, 252.50
	Entity's Block location: World: (-137,64,252), Chunk: (at 7,4,12 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@43fd4e5f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3788479600 bytes (3612 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -Xmx5G -Xms5G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2420 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2420.jar) 
	UCHIJAAAA	forge{14.21.1.2420} [Minecraft Forge] (forge-1.12-14.21.1.2420.jar) 
	UCHIJAAAA	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCHIJAAAA	thutcore{5.4.0} [Thut Core] (thutcore-5.4.0.jar) 
	UCHIJAAAA	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-6.9.1.jar) 
	UCHIJAAAA	pokecube{6.9.1} [Pokécube Core] (Pokecube Core-6.9.1.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-6.9.1.jar) 
	UCHIJAAAA	pokecube_adventures{6.6.0} [Pokécube Revival] (Pokecube Revival-6.6.0.jar) 
	UCHIJAAAA	pokecube_mobs{2.10.0} [Pokécube Mobs] (Pokecube Mobs-2.10.0.jar) 
	UCHIJAAAA	pokecube_moves{@VERSION@} [Pokecube Movess] (Pokecube Mobs-2.10.0.jar) 
	UCHIJAAAA	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.10.0.jar) 
	UCHIJAAAA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-6.6.0.jar) 
	UCHIJAAAA	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-6.6.0.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Oxosorrel'/2331, l='New World', x=-136.50, y=64.00, z=252.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Oxosorrel** [comment]
https://github.com/Thutmose/Pokecube/issues/193

**Comment by bonii-xx** [comment]
Bug on their side.

**Comment by KnightMiner** [comment]
Turns out it was on our side as well as we were never registering the capability thus our instance was always null, fixed with a3703b1.
