### ISSUE TITLE
Crash when smelting sand into glass

### ISSUE THREAD

**Issue by metaphoricalstate** [SlimeKnights/TinkersConstruct#3042]
Caused my client to disconnect from server and gave me this error in the server log.

> [22:42:04] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:42:04] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:42:04] [Netty Epoll Server IO #1/DEBUG] [FML/]: FMLHandshakeServerState: $HandshakeAck:{5}->FMLHandshakeServerState$5:DONE
[22:42:04] [Netty Epoll Server IO #1/DEBUG] [FML/]:   Next: DONE
[22:42:12] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:42:12] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:42:27] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:42:27] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:42:29] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[22:42:29] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:42:29] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:42:29] [Server thread/ERROR] [FML/]: A TileEntity type slimeknights.tconstruct.smeltery.tileentity.TileCastingBasin has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ee.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128) ~[dr.class:?]
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:100) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77) ~[FluidTank.class:?]
	at slimeknights.tconstruct.smeltery.tileentity.TileCasting.func_189515_b(TileCasting.java:271) ~[TileCasting.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[22:42:42] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:42:42] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:42:57] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:42:57] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:43:12] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:43:12] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:43:14] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[22:43:14] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:43:14] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:43:14] [Server thread/ERROR] [FML/]: A TileEntity type slimeknights.tconstruct.smeltery.tileentity.TileCastingBasin has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ee.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128) ~[dr.class:?]
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:100) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77) ~[FluidTank.class:?]
	at slimeknights.tconstruct.smeltery.tileentity.TileCasting.func_189515_b(TileCasting.java:271) ~[TileCasting.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[22:43:27] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:43:27] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:43:42] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:43:42] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:43:57] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:43:57] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb
[22:43:59] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[22:44:12] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[22:44:12] [Server thread/ERROR] [tconstruct-TinkerSmeltery/]:   fluid.tconstruct.glass/17856mb

**Comment by KnightMiner** [comment]
What version are you in? Not sure how glass fluid could not be registered as we always register them, but registration changed quite a bit.

Also, can you explain more of your setup? Did you have any fluid pipes or anything around the smeltery for instance? The log also claims an issue with a fluid with no name in a casting basin

**Comment by metaphoricalstate** [comment]
Using the TConstruct-1.10.2-2.6.5 on the latest version of AllTheMods Lite, I right clicked the faucet into the basin after the invisible glass was in the smeltery. nothing else is around the smeltery.

**Comment by KnightMiner** [comment]
Does this happen in Single player? Also try to reproduce with minimal mods, I have never seen this issue myself.

**Comment by KnightMiner** [comment]
Closing for lack of response and not being able to reproduce.
