### ISSUE TITLE
Tinkers Error locks my server console.

### ISSUE THREAD

**Issue by MaraktoN** [SlimeKnights/TinkersConstruct#3044]
Hello all,

I'm experiencing a very annoying issue thanks to tinkers construct mod on my server.

I'm recieving the following error every couple of minutes on my console:

[00:52:54 ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$ItemCraftedEvent@432f75da:
java.lang.NullPointerException
at tconstruct.tools.TinkerToolEvents.onCrafting(TinkerToolEvents.java:39) ~[TinkerToolEvents.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_351_TinkerToolEvents_onCrafting_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-R0.1-SNAPSHOT]
at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:592) [FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
at vswe.production.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:109) [UnitCrafting.class:?]
at vswe.production.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:92) [UnitCrafting.class:?]
at vswe.production.page.unit.UnitCrafting.onProduction(UnitCrafting.java:529) [UnitCrafting.class:?]
at vswe.production.page.unit.Unit.produce(Unit.java:156) [Unit.class:?]
at vswe.production.page.unit.Unit.onUpdate(Unit.java:186) [Unit.class:?]
at vswe.production.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:270) [UnitCrafting.class:?]
at vswe.production.page.PageMain.onUpdate(PageMain.java:53) [PageMain.class:?]
at vswe.production.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:323) [TileEntityTable.class:?]
at net.minecraft.world.World.func_72939_s(World.java:2529) [ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633) [mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
[00:52:54 ERROR]: Index: 9 Listeners:
[00:52:54 ERROR]: 0: NORMAL
[00:52:54 ERROR]: 1: ASM: ic2.core.IC2Achievements@7a5ac4c7 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 2: ASM: WayofTime.alchemicalWizardry.common.achievements.AchievementTrigger@388af2f6 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 3: ASM: thaumcraft.common.lib.events.EventHandlerWorld@7d109425 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 4: ASM: vazkii.botania.common.item.ItemCraftingHalo@6d7315dd onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 5: ASM: vazkii.botania.common.achievement.AchievementTriggerer@3b915ad0 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 6: ASM: cofh.thermalexpansion.util.crafting.TECraftingHandler@52c9c629 handleOnItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 7: ASM: mods.railcraft.common.util.crafting.CraftingHandler@78ba2edc onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 8: ASM: com.brandon3055.draconicevolution.common.achievements.Achievements@48c1aa09 craftEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 9: ASM: tconstruct.tools.TinkerToolEvents@79e8555e onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 10: ASM: tconstruct.smeltery.TinkerSmelteryEvents@357d6d9b onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 11: ASM: minetweaker.mc1710.FMLEventHandler@488df453 onPlayerItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 12: ASM: appeng.core.stats.AchievementCraftingHandler@493c8762 onPlayerCraftingEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 13: ASM: buildcraft.core.AchievementManager@50b514a8 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 14: ASM: twilightforest.TFEventListener@452ce874 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 15: ASM: blusunrize.immersiveengineering.common.EventHandler@6bdc86d9 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 16: ASM: thaumic.tinkerer.common.item.SpellClothCraftingHandler@2e2c564e ItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 17: ASM: fox.spiteful.forbidden.FMEventHandler@9b661ab onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 18: ASM: mcjty.rftools.FMLEventHandlers@6e8324d2 onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 19: ASM: tonius.simplyjetpacks.crafting.PlatingReturnHandler@6dac5195 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 20: ASM: stevesaddons.recipes.ClusterUncraftingRecipe@7ed46b00 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 21: ASM: vswe.stevescarts.Helpers.CraftingHandler@2be4461d onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 ERROR]: 22: ASM: tconstruct.weaponry.WeaponryHandler@50610b47 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[00:52:54 WARN]: java.lang.NullPointerException
[00:52:54 WARN]: at tconstruct.tools.TinkerToolEvents.onCrafting(TinkerToolEvents.java:39)
[00:52:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_351_TinkerToolEvents_onCrafting_ItemCraftedEvent.invoke(.dynamic)
[00:52:54 WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[00:52:54 WARN]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[00:52:54 WARN]: at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:592)
[00:52:54 WARN]: at vswe.production.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:109)
[00:52:54 WARN]: at vswe.production.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:92)
[00:52:54 WARN]: at vswe.production.page.unit.UnitCrafting.onProduction(UnitCrafting.java:529)
[00:52:54 WARN]: at vswe.production.page.unit.Unit.produce(Unit.java:156)
[00:52:54 WARN]: at vswe.production.page.unit.Un
it.onUpdate(Unit.java:186)
[00:52:54 WARN]: at vswe.production.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:270)
[00:52:54 WARN]: at vswe.production.page.PageMain.onUpdate(PageMain.java:53)
[00:52:54 WARN]: at vswe.production.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:323)
[00:52:54 WARN]: at net.minecraft.world.World.func_72939_s(World.java:2529)
[00:52:54 WARN]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
[00:52:54 WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
[00:52:54 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[00:52:54 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[00:52:54 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[00:52:54 WARN]: at java.lang.Thread.run(Thread.java:745)

Also, this error makes me unable to type in any console command (like op user).

What I've tried:
Server restart
Download tinkers again

Additional info:

Server: FTB Infinity Evolved - v2.6.0
Minecraft: v1.7.10
Tinkers Construct v1.8.8

Any ideas on how to fix this people? Or maybe why this is happening? :(

**Comment by KnightMiner** [comment]
First off, 1.7.10 is no longer supported. Last build was nearly 2 years ago, another one is not going to come.

Your error appears to be caused by someone firing the ItemCraftedEvent with a null player. I'd argue their fault as its a generic player event just the player should never be null, they should be passing a fake player. Given that this is the first time I've seen this conflict, its probably on that mod's side. Stacktrace points to [Steve's Workshop](https://minecraft.curseforge.com/projects/steves-workshop), but that has not received an update in 3 years so I doubt you will get support there either.

**Comment by MaraktoN** [comment]
Thanks for the reply KnightMiner! Yes im totally aware about 1.7.10 unsupport but since I couldn't find any info about this error I tought I'd give a try.

Nevertheless, the bug stopped on my server... And I have no idea why lol. Maybe it was being fired by a specific bugged tinkers tool which stopped being used from the players? Thats my best bet!
