### ISSUE TITLE
Crash on startup with AE2

### ISSUE THREAD

**Issue by TheSnowyChickens** [SlimeKnights/TinkersConstruct#3068]
Hello
I update AE2 and TIC + Mantle and start my Modpack test pack and it crash with this log :

MC: 1.12
AE2 : applied-llamagistics-1.12-rv5-beta-3
TIC : TConstruct-1.12-2.7.2.15
Mantle : Mantle-1.12-1.3.1.18
Forge : 2428

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModLoader (applied-llamagistics-1.12-rv5-beta-3.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/30/17 5:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Llamagistics (appliedenergistics2)
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: appeng.block.misc.BlockInscriber.<init>()void/newInvokeSpecial
	at appeng.core.api.definitions.ApiBlocks.<init>(ApiBlocks.java:281)
	at appeng.core.ApiDefinitions.<init>(ApiDefinitions.java:45)
	at appeng.core.Api.<init>(Api.java:55)
	at appeng.core.Api.<clinit>(Api.java:41)
	at appeng.core.Registration.preInitialize(Registration.java:150)
	at appeng.core.AppEng.preInit(AppEng.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: no such constructor: appeng.block.misc.BlockInscriber.<init>()void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: appeng/tile/misc/TileInscriber
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
	... 48 more
Caused by: java.lang.ClassNotFoundException: appeng.tile.misc.TileInscriber
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 53 more
Caused by: java.lang.NoClassDefFoundError: appeng/tile/grid/AENetworkPowerTile
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 55 more
Caused by: java.lang.ClassNotFoundException: appeng.tile.grid.AENetworkPowerTile
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 59 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 154760928 bytes (147 MB) / 360927232 bytes (344 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2428 Optifine OptiFine_1.12_HD_U_C5_pre 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2428.jar) 
	UCH	forge{14.21.1.2428} [Minecraft Forge] (forge-1.12-14.21.1.2428.jar) 
	UCH	appliedenergistics2-core{rv5-beta-3} [Applied Llamagistics Core] (minecraft.jar) 
	UCE	appliedenergistics2{rv5-beta-3} [Applied Llamagistics] (applied-llamagistics-1.12-rv5-beta-3.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCH	jei{4.7.2.76} [Just Enough Items] (jei_1.12-4.7.2.76.jar) 
	UCH	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCH	tconstruct{1.12-2.7.2.15} [Tinkers' Construct] (TConstruct-1.12-2.7.2.15.jar) 
	UCH	theoneprobe{1.4.13} [The One Probe] (theoneprobe-1.12-1.4.13.jar) 
	Loaded coremods (and transformers): 
CoreModLoader (applied-llamagistics-1.12-rv5-beta-3.jar)
  appeng.coremod.transformer.ASMIntegration
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.94' Renderer: 'GeForce GTX 780 Ti/PCIe/SSE2'
	AE2 Version: beta rv5-beta-3 for Forge 14.21.1.2387
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12_HD_U_C5_pre
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 384.94
	OpenGlRenderer: GeForce GTX 780 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	
Now its a bug from your side or from AE2 Team ?

Thx

**Comment by BrianEdmonds** [comment]
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught
> exception from Applied Llamagistics (appliedenergistics2)

Why are you even asking off the top if this is Tinkers?  The very first
thing in the crash log appears to point pretty clearly at AE2.

**Comment by alexbegt** [comment]
You are missing the mod "Redstone Flux" (CurseForge: [Link](https://minecraft.curseforge.com/projects/redstone-flux) ) and the version of "Applied Llamagistics" you have is a fork of Applied Energistics 2. I would also look at issues 41 on the forks github : https://github.com/thiakil/Applied-Energistics-2/issues/41

**Comment by TheSnowyChickens** [comment]
Ahh okay ,  mb.
Then I think this post can be closed.
