### ISSUE TITLE
1.12.1 Crash clicking a tinkers crafting table

### ISSUE THREAD

**Issue by winsrp** [SlimeKnights/TinkersConstruct#3092]
I put crafted a tinkers crafting table and right click it... boom... crash. This is in single player, hardcore mode.

[16:53:27] [main/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  IvToolkit (RecurrentComplex IvToolkit-1.3.3-1.12.jar)
  AppleCore (SpiceOfLife AppleCore-mc1.12.1-2.2.2.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/9/17 4:53 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_191878_b(SourceFile:137)
	at slimeknights.tconstruct.tools.common.client.GuiCraftingStation.func_73863_a(GuiCraftingStation.java:111)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:549)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by KnightMiner** [comment]
You are missing the majority of the crash report. Paste the whole thing on a site such as pastebin and link it here

**Comment by winsrp** [comment]
I pastes as much as paste bin allowed me to, since it goes way over 512kb it wont let me paste the whole thing https://pastebin.com/wY15nUxb

**Comment by KnightMiner** [comment]
Normally you can just grab the crash report from the crash reports folder, but I can see it in the game log.

Somehow, the vanilla recipe book is null, I'm pretty sure that should not be possible. Can you try to reduce your mod list a bit and reproduce it? I feel like some mod could be messing with recipe book loading.

**Comment by winsrp** [comment]
sure.... I'll try to post the result in 15 mins

**Comment by winsrp** [comment]
no need to wait so long... putting only mantle-1.12-1.3.1.18 and the tconstruct 1.12-2.7.2.15 got this crash, no other mods present. This time full log.

https://pastebin.com/eDmVnyR4

**Comment by bonii-xx** [comment]
Probably 1.12.1 related

**Comment by klj911qq** [comment]
I guess I have the same issue. Probably Recipe book related. Crush report https://pastebin.com/1B60Fa19

**Comment by cragrim** [comment]
I also just had this issue after updating and testing 1.12.1. Glad to see you're on it :) Keep up the great work

**Comment by wibblywobble** [comment]
So how exactly does this problem get fixed? I also get a crash when I click on my tinkers table. I have NEI and Pams Harvestcraft present, along with all the core mods (codechicken, jei, mantle, etc)
It's the same error as above I believe, but I can't follow how to correct it. Please assist!

**Comment by bonii-xx** [comment]
Update Tinkers.
