### ISSUE TITLE
[1.11.2] This mod stops my mod pack working help fix?

### ISSUE THREAD

**Issue by DJPhilGaming** [SlimeKnights/TinkersConstruct#3110]
I have recently found interest in trying to make my own mod pack and found issues with adding tinkers construct I will add the crash report underneath but I can't seem to notice what the problem is

Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (CXLibrary-1.11.2.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.298-universal (2).jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  CreativePatchingLoader (CreativeCore-1.11.2.jar)
  IC2core (Industrial-Craft-2-Mod-Experimental-1.11.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.11.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 8/18/17 5:00 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.func_110970_k(AtlasSpriteSwappable.java:116)
	at slimeknights.tconstruct.library.client.texture.TextureColoredTexture.loadData(TextureColoredTexture.java:70)
	at slimeknights.tconstruct.library.client.texture.TextureColoredTexture.colorPixel(TextureColoredTexture.java:44)
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.processData(AbstractColoredTexture.java:106)
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.load(AbstractColoredTexture.java:87)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:94)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:764)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:373)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.func_110970_k(AtlasSpriteSwappable.java:116)
	at slimeknights.tconstruct.library.client.texture.TextureColoredTexture.loadData(TextureColoredTexture.java:70)
	at slimeknights.tconstruct.library.client.texture.TextureColoredTexture.colorPixel(TextureColoredTexture.java:44)
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.processData(AbstractColoredTexture.java:106)
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.load(AbstractColoredTexture.java:87)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:94)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:764)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:373)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 900312752 bytes (858 MB) / 2193551360 bytes (2091 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2454 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2454.jar) 
	UCHIJA	forge{13.20.1.2454} [Minecraft Forge] (forge-1.11.2-13.20.1.2454.jar) 
	UCHIJA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJA	bibliocraft{2.3.2} [BiblioCraft] (BiblioCraft-Mod-1.11.2.jar) 
	UCHIJA	blockarmor{2.4.3} [Block Armor] (Block-Armor-Mod-1.11.2.jar) 
	UCHIJA	guideapi{1.11.2-2.1.4-56} [Guide-API] (Guide-API-1.11.2-2.1.4-56.jar) 
	UCHIJA	bloodmagic{1.11-2.1.2-71} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.2-71.jar) 
	UCHIJA	buildcraftlib{7.99.0} [BuildCraft Lib] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcraftcore{7.99.0} [BuildCraft] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcraftfactory{7.99.0} [BC Factory] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcrafttransport{7.99.0} [BC Transport] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcraftbuilders{7.99.0} [BC Builders] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcraftenergy{7.99.0} [BC Energy] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcraftrobotics{7.99.0} [BC Robotics] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	buildcraftsilicon{7.99.0} [BC Silicon] (BuildCraft-Mod-1.11.2.jar) 
	UCHIJA	codechickenlib{3.0.0.298} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.298-universal (2).jar) 
	UCHIJA	cookingforblockheads{5.3.23} [Cooking for Blockheads] (Cooking-for-Blockheads-Mod-1.11.2.jar) 
	UCHIJA	creativecore{1.7.4} [CreativeCore] (CreativeCore-1.11.2.jar) 
	UCHIJA	cxlibrary{1.4.0} [CXLibrary] (CXLibrary-1.11.2.jar) 
	UCHIJA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJA	aroma1997sdimension{1.0} [Aroma1997sDimension] (Dimensional-World-Mod-1.11.2.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (Extra-Utilities-Mod-1.11.2.jar) 
	UCHIJA	ic2{2.7.81-ex111} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.11.2.jar) 
	UCHIJA	ironchest{1.11.2-7.0.24.809} [Iron Chest] (Iron-Chests-Mod-1.11.2.jar) 
	UCHIJA	jei{4.5.1.296} [Just Enough Items] (jei_1.11.2-4.5.1.296.jar) 
	UCHIJA	littletiles{1.4.8} [LittleTiles] (LittleTiles-Mod-1.11.2.jar) 
	UCHIJA	lucky{7.4.0} [Lucky Block] (Lucky-Block-Mod-1.11.2.zip) 
	UCHIJA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-Mod-1.11.2.jar) 
	UCHIJA	mob_grinding_utils{0.2.0} [mob_grinding_utils] (MobGrindingUtils-0.2.0.jar) 
	UCHIJA	morefurnaces{1.9.5} [More Furnaces] (More-Furnaces-Mod-1.11.2.jar) 
	UCHIJE	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.3.0.227-universal.jar) 
	UCHIJA	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCHIJA	bspkrscore{at_0.9} [bspkrsCore] (TreeCapitator-Mod-1.11.2.jar) 
	UCHIJA	treecapitator{at_0.9} [Treecapitator] (TreeCapitator-Mod-1.11.2.jar) 
	UCHIJA	uncraftingtable{1.7.2} [Uncrafting Table] (Uncrafting-Table-Mod-1.11.2.jar) 
	UCHIJA	veinminer{0.38.1} [Vein Miner] (Vein-Miner-Mod-1.11.2.jar) 
	UCHIJA	veinminermodsupport{0.38.1} [Mod Support] (Vein-Miner-Mod-1.11.2.jar) 
	UCHIJA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (CXLibrary-1.11.2.jar)
  cubex2.cxlibrary.CoreModTransformer
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.298-universal (2).jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  codechicken.nei.asm.NEITransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
CreativePatchingLoader (CreativeCore-1.11.2.jar)
  
IC2core (Industrial-Craft-2-Mod-Experimental-1.11.2.jar)
  
LittlePatchingLoader (LittleTiles-Mod-1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4300' Renderer: 'Intel(R) HD Graphics 530'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: 1.11.2-forge1.11.2-13.20.1.2454
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 20.19.15.4300, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by bonii-xx** [comment]
You realize you're using the oldest possible version of buildcraft, yes? Go update it.

**Comment by xenxero1** [comment]
The dangers of 9minecraft and other shady mod-distribution sites...
