### ISSUE TITLE
Tconstruct crashing client

### ISSUE THREAD

**Issue by Raycoms** [SlimeKnights/TinkersConstruct#3120]
> [19:46:28] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LootingLevelEvent@5d538861:
java.lang.NoSuchMethodError: net.minecraft.util.DamageSource.getSourceOfDamage()Lnet/minecraft/entity/Entity;
	at slimeknights.tconstruct.tools.ToolEvents.onLooting(ToolEvents.java:150) ~[ToolEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_ToolEvents_onLooting_LootingLevelEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:579) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:571) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1254) [EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1093) [EntityLivingBase.class:?]
	at net.minecraft.entity.passive.EntityBat.attackEntityFrom(EntityBat.java:234) [EntityBat.class:?]
	at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:556) [Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:265) [EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:248) [EntityLiving.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:454) [Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2221) [EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:344) [EntityLiving.class:?]
	at net.minecraft.entity.passive.EntityBat.onUpdate(EntityBat.java:121) [EntityBat.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2130) [World.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:883) [WorldServer.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2096) [World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1907) [World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:651) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:795) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:699) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

> 

I'm getting this with:

minecraft_version=1.11.2
forge_version=13.20.1.2429
mantle_version=1.2.0.25
tinker_version=2.7.0.26
minecolonies_mappings=stable_32

**Comment by bonii-xx** [comment]
Update TiC. Try reproducing with only TiC and Mantle if it still happens.

**Comment by Raycoms** [comment]
The newer tc version is already on maven/gradle?

**Comment by KnightMiner** [comment]
It's on maven before it's actually released. This does look like #2938 though

**Comment by bonii-xx** [comment]
Why do you care about maven? It's on curseforge. You're on 1.11.2. That was released quite a while ago.

**Comment by Raycoms** [comment]
Because I get this bug debugging our mod in intellij in 1.11.2

**Comment by bonii-xx** [comment]
Would be nice to have those infos in the report. Anyway, use the latest version for 1.11.2. https://github.com/SlimeKnights/TinkersConstruct/releases/tag/2.7.1.34

**Comment by Raycoms** [comment]
pretty certain the same thing like #2938

**Comment by Raycoms** [comment]
The difference is that I deobfcompile already:

    deobfCompile "slimeknights.mantle:Mantle:${config.minecraft_version}-${config.mantle_version}"
    deobfCompile "slimeknights:TConstruct:${config.minecraft_version}-${config.tinker_version}"

**Comment by bonii-xx** [comment]
Then you need to refresh your cache probably. deobfCompile takes the jar and deobfuscates it with your mappings. Note that it uses the regular jar, not the deobf jar.

**Comment by bonii-xx** [comment]
Could you try the build 2.7.1.36 for 1.11.2 and see if that works?

**Comment by KnightMiner** [comment]
Closing for lack of response. The build boni mentioned should fix the issue
