### ISSUE TITLE
Crashes forge server when with other mods

### ISSUE THREAD

**Issue by Svanzscape** [SlimeKnights/TinkersConstruct#3199]
Tried running it with other mods, doesn't work. 

Related crash report : 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (CXLibrary-1.12.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 16/10/17 18:30
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
Caused by: java.lang.NullPointerException
	at com.rwtema.extrautils2.modcompat.TinkersIntegration.doRegister(TinkersIntegration.java:244)
	at com.rwtema.extrautils2.modcompat.TinkersIntegrationEntry.preInitLoad(TinkersIntegrationEntry.java:27)
	at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:55)
	at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 634886520 bytes (605 MB) / 914358272 bytes (872 MB) up to 3808428032 bytes (3632 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2512 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                         | Signature                                |
	|:----- |:----------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2            | minecraft.jar                                  | None                                     |
	| UCH   | mcp               | 9.42              | minecraft.jar                                  | None                                     |
	| UCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.0.2512-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.0.2512      | forge-1.12.2-14.23.0.2512-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | cxlibrary         | 1.6.1             | CXLibrary-1.12.1.jar                           | None                                     |
	| UCH   | jei               | 4.7.10.97         | Just-Enough-Items-Mod-1.12.2.jar               | None                                     |
	| UCH   | mantle            | 1.12-1.3.1.21     | Mantle-Mod-1.12.1.jar                          | None                                     |
	| UCH   | tconstruct        | 1.12-2.7.3.30     | Tinkers-Construct-Mod-1.12.1.jar               | None                                     |
	| UCE   | extrautils2       | 1.0               | Extra-Utilities-Mod-1.12.1.jar                 | None                                     |
	| UCH   | ichunutil         | 7.0.2             | iChun-Util-Mod-1.12.2.jar                      | None                                     |
	| UCH   | ic2               | 2.8.16-ex112      | Industrial-Craft-2-Mod-Experimental-1.12.1.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | ironchest         | 1.12.2-7.0.34.820 | Iron-Chests-Mod-1.12.2.jar                     | None                                     |
	| UCH   | journeymap        | 1.12-5.5.0        | journeymap-1.12-5.5.0.jar                      | None                                     |
	| UCH   | mercurius_updater | 1.0               | MercuriusUpdater-1.12.2.jar                    | None                                     |
	| UCH   | metamorph         | 1.1.4             | Metamorph-1.12.2.jar                           | None                                     |
	| UCH   | portalgun         | 7.0.0             | Portal-Gun-Mod-1.12.2.jar                      | None                                     |
	| UCH   | treechopper       | 1.2.2             | Tree-Chopper-Mod-1.12.1.jar                    | None                                     |

	Loaded coremods (and transformers): 
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by KnightMiner** [comment]
This crash is from Extra Utilities 2 in their Tinkers integration, report to that tracker.
