### ISSUE TITLE
Stack trace in server log related to slime boots, java.lang.RuntimeException: Missing

### ISSUE THREAD

**Issue by Ricket** [SlimeKnights/TinkersConstruct#3340]
Quite a few of these in the log.

```
 Jan 17, 2018 8:36:03 PM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
java.lang.RuntimeException: Missing
        at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:298)
        at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:553)
        at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$8.selectNetworks(FMLOutboundHandler.java:248)
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:289)
        at slimeknights.tconstruct.common.TinkerNetwork.sendToServer(TinkerNetwork.java:98)
        at slimeknights.tconstruct.gadgets.item.ItemSlimeBoots.onFall(ItemSlimeBoots.java:168)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_993_ItemSlimeBoots_onFall_LivingFallEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.common.ForgeHooks.onLivingFall(ForgeHooks.java:597)
        at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1305)
        at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1946)
        at net.minecraft.block.Block.func_180658_a(Block.java:821)
        at net.minecraft.entity.Entity.func_184231_a(Entity.java:1130)
        at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:213)
        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:838)
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:583)
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126)
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```

TConstruct-1.12.2-2.9.0.55.jar

FTB Revelation pack v1.3.0

**Comment by bonii-xx** [comment]
#3334
