### ISSUE TITLE
Crash on mod load

### ISSUE THREAD

**Issue by Minecraftschurli** [SlimeKnights/TinkersConstruct#3417]
I keep crashing on loading tinkers

crash report:

 ----Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 3/12/18 5:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Construct (tconstruct)
Caused by: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/materials/IMaterialStats
	at slimeknights.tconstruct.shared.TinkerFluids.setupFluids(TinkerFluids.java:87)
	at slimeknights.tconstruct.shared.TinkerFluids.<clinit>(TinkerFluids.java:79)
	at slimeknights.tconstruct.TConstruct.<clinit>(TConstruct.java:106)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.materials.IMaterialStats
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 400462056 bytes (381 MB) / 942669824 bytes (899 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version         | Source                         | Signature                                |
	|:----- |:---------- |:--------------- |:------------------------------ |:---------------------------------------- |
	| UC    | minecraft  | 1.12.2          | minecraft.jar                  | None                                     |
	| UC    | mcp        | 9.42            | minecraft.jar                  | None                                     |
	| UC    | FML        | 8.0.99.99       | forge-1.12.2-14.23.2.2624.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge      | 14.23.2.2624    | forge-1.12.2-14.23.2.2624.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | jei        | 4.8.5.159       | jei_1.12.2-4.8.5.159.jar       | None                                     |
	| UC    | mantle     | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar       | None                                     |
	| UE    | mfm        | 1.12.2-0.0.1.4  | MFM-1.12.2-0.0.1.4.jar         | None                                     |
	| UC    | nbttooltip | 0.5             | nbttooltip-0.5.jar             | None                                     |
	| UE    | tconstruct | 1.12.2-2.9.1.65 | TConstruct-1.12.2-2.9.1.65.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.54' Renderer: 'GeForce GT 755M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)

**Comment by Minecraftschurli** [comment]
I don't know if my mod(mfm) is it that causes the crash but in the dev env it works

**Comment by KnightMiner** [comment]
Does your mod depend on Tinkers Construct at all, and removing it fixes the error? Good chance you are missing an `after:tconstruct` in your mod dependencies.

**Comment by Minecraftschurli** [comment]
no it doesn't depend it just integrates when tconstruct is there

**Comment by KnightMiner** [comment]
But you use Tinkers Construct code is what I am asking. Try adding the dependency string I gave you to your main mod class, as class loading works different in dev

**Comment by Minecraftschurli** [comment]
yeah that's it
