### ISSUE TITLE
Stencil table not opening on SMP

### ISSUE THREAD

**Issue by Wolfey180** [SlimeKnights/TinkersConstruct#3487]
Hi! I just made a new modpack for 1.12.2 and the stencil table does not open.

I just did some more looking and when rightclicking on the table an error is generated:

`java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3077]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3975) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171]
	at org.spongepowered.common.item.inventory.lens.impl.collections.MutableLensCollectionImpl.getLens(MutableLensCollectionImpl.java:123) ~[MutableLensCollectionImpl.class:1.12.2-2655-7.1.0-BETA-3077]
	at org.spongepowered.common.item.inventory.lens.impl.collections.MutableLensCollectionImpl.get(MutableLensCollectionImpl.java:118) ~[MutableLensCollectionImpl.class:1.12.2-2655-7.1.0-BETA-3077]
	at org.spongepowered.common.item.inventory.lens.impl.collections.MutableLensCollectionImpl.get(MutableLensCollectionImpl.java:39) ~[MutableLensCollectionImpl.class:1.12.2-2655-7.1.0-BETA-3077]
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309) ~[?:1.8.0_171]
	at net.minecraft.inventory.Slot.handler$onConstructed$zih004(Slot.java:1067) ~[agr.class:?]
	at net.minecraft.inventory.Slot.<init>(Slot.java:23) ~[agr.class:?]
	at net.minecraft.inventory.SlotCrafting.<init>(SlotCrafting.java:18) ~[ago.class:?]
	at slimeknights.mantle.inventory.SlotCraftingCustom.<init>(SlotCraftingCustom.java:23) ~[SlotCraftingCustom.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerStencilTable.<init>(ContainerStencilTable.java:41) ~[ContainerStencilTable.class:?]
	at slimeknights.tconstruct.tools.common.tileentity.TileStencilTable.createContainer(TileStencilTable.java:31) ~[TileStencilTable.class:?]
	at slimeknights.mantle.common.GuiHandler.getServerGuiElement(GuiHandler.java:18) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.redirect$setRemoteContainerPlugin$bag000(NetworkRegistry.java:547) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:256) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at slimeknights.tconstruct.tools.common.block.BlockToolTable.openGui(BlockToolTable.java:85) ~[BlockToolTable.class:?]
	at slimeknights.mantle.block.BlockInventory.func_180639_a(BlockInventory.java:52) ~[BlockInventory.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1268) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zil000(NetHandlerPlayServer.java:2393) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) ~[PacketUtil.class:1.12.2-2655-7.1.0-BETA-3077]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

Would this be something on tconstruct's end, or just a direct conflict with sponge? Either way, thank you!

Relevant mods:
TConstruct-1.12.2-2.9.1.65.jar
Mantle-1.12-1.3.2.24.jar
Forge 2665
spongeforge-1.12.2-2655-7.1.0-BETA-3077.jar (Not sure if this would affect Tconstruct or not)

Full modlist: (Can get any versions needed)
`Thaumcraft (Needs Baubles)
Pam's Harvest Craft
Actual Additions
OpenBlocks (Needs Openmods)
Applied Energistics
Extra Utilities
Tinker's Construct (Needs mantle)
HWYLA
Iron Chests
IndustrialCraft 2
EnderIO (EnderCore)
Just enough Items
Gendustry (Needs BDLib and Forestry)
MineColonies
Forestry (Needed by Gendustry)
Immersive Engineering (Connected Texture mod)
More Bees
Blood Magic (Needs Guide-API)
BiblioCraft
ExtremeReactors (Needs Zerocore)
Project Red (Needs Code Chicken lib and MrTJLib and ForgeMultipartCBE)
Thermal Expansion, Dynamics, Innovation (Needs thermalfoundation and COFH core and Redstone Flux)
Tails (Needs foxlib)	ic
Avaritia (Needs CodeChickenLib)
Chisel (Requires connected texture mod)
DecoCraft (Requires PTRLib)
Storage Drawers (Requires Chameleon)
Draconic Evolution (requires Brandon's core)
Appleskin
Inventory Tweaks
Roguelike Dungeons
Fast Leaf Decay
Light Overlay
Item Scroller
Inductive Logistics Pipes (Requires CD4017BElib)
OpenComputers
Natura (needs mantle)
Advanced Solar Panels (needs IC2)
Thaumic JEI
Thaumic Inventory Scanning
Thaumic Peripheryr`

**Comment by Wolfey180** [comment]
Replying to help anyone else who might get this problem:

Updating spongeforge to 3080+ fixed the problem.
