### ISSUE TITLE
TConstruct-1.12.2-2.10.0.81 Crashing due to registry conflict with base metals mod?

### ISSUE THREAD

**Issue by WilliamBlaze** [SlimeKnights/TinkersConstruct#3513]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.2-universal.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.15-98.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.7.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 5/30/18 2:31 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Moar Tinkers (moartinkers)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "platinum": It was already registered by Base Metals
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:129)
	at com.bartz24.moartinkers.MoarMaterialIntegration.preInit(MoarMaterialIntegration.java:71)
	at com.bartz24.moartinkers.registry.ModMaterials.ingotMaterial(ModMaterials.java:720)
	at com.bartz24.moartinkers.registry.ModMaterials.preInit(ModMaterials.java:120)
	at com.bartz24.moartinkers.proxy.CommonProxy.preInit(CommonProxy.java:24)
	at com.bartz24.moartinkers.proxy.ClientProxy.preInit(ClientProxy.java:14)
	at com.bartz24.moartinkers.MoarTinkers.preInit(MoarTinkers.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by WilliamBlaze** [comment]
even with platinum generation by base metals turned off; this issue still happens.

**Comment by YaibaToKen** [comment]
Wrong issue tracker, the crash is caused by Moar Tinkers attempting to register a material without checking if it already exists, a fix is already being implemented and will hopefully be available till the end of the week.

**Comment by KnightMiner** [comment]
Yep, this is a conflict between base metals and Moar Tinkers. There may be other conflicting materials which would cause the crash without platinum
