### ISSUE TITLE
AE2 Autocrafting causing "java.lang.ArrayIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by a20eac1d** [SlimeKnights/TinkersConstruct#3546]
Tinkers Construct is causing a java.lang.ArrayIndexOutOfBoundsException.

This error happens, even if I start autocrafting using the latest AE2. There are no TCon materials in the recipe (trying to autocraft a Molecular Assembler):

```
[18:58:46] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$ItemCraftedEvent@74de9413:
java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraft.server.MinecraftServer.func_191949_aK(MinecraftServer.java:1415) ~[MinecraftServer.class:?]
	at slimeknights.tconstruct.shared.AchievementEvents.grantAdvancement(AchievementEvents.java:57) ~[AchievementEvents.class:?]
	at slimeknights.tconstruct.shared.AchievementEvents.onCraft(AchievementEvents.java:33) ~[AchievementEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1804_AchievementEvents_onCraft_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:594) [FMLCommonHandler.class:?]
	at appeng.crafting.CraftingTreeProcess.<init>(CraftingTreeProcess.java:80) [CraftingTreeProcess.class:?]
	at appeng.crafting.CraftingTreeNode.<init>(CraftingTreeNode.java:86) [CraftingTreeNode.class:?]
	at appeng.crafting.CraftingTreeProcess.<init>(CraftingTreeProcess.java:139) [CraftingTreeProcess.class:?]
	at appeng.crafting.CraftingTreeNode.<init>(CraftingTreeNode.java:86) [CraftingTreeNode.class:?]
	at appeng.crafting.CraftingJob.getCraftingTree(CraftingJob.java:98) [CraftingJob.class:?]
	at appeng.crafting.CraftingJob.<init>(CraftingJob.java:92) [CraftingJob.class:?]
	at appeng.me.cache.CraftingGridCache.beginCraftingJob(CraftingGridCache.java:515) [CraftingGridCache.class:?]
	at appeng.core.sync.packets.PacketCraftRequest.serverPacketData(PacketCraftRequest.java:100) [PacketCraftRequest.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:57) [AppEngServerPacketHandler$1.class:?]
	at appeng.core.sync.AppEngPacket.func_148833_a(AppEngPacket.java:128) [AppEngPacket.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[18:58:46] [Server thread/ERROR] [FML]: Index: 11 Listeners:
[18:58:46] [Server thread/ERROR] [FML]: 0: NORMAL
[18:58:46] [Server thread/ERROR] [FML]: 1: ASM: crafttweaker.mc1120.events.CommonEventHandler@6046b84 onPlayerItemCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 2: ASM: com.brandon3055.draconicevolution.achievements.Achievements@1384f38 craftEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 3: ASM: com.rwtema.extrautils2.crafting.PlayerSpecificCrafting$EventHandler@32385cc0 onCraft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 4: ASM: com.rwtema.extrautils2.crafting.PlayerSpecificCrafting$EventHandler@794589ce onCraft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 5: ASM: org.cyclops.cyclopscore.advancement.criterion.ItemCraftedTrigger@4cf17f93 onCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 6: ASM: org.cyclops.cyclopscore.advancement.criterion.ModItemObtainedTrigger@4bf2ce87 onCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 7: ASM: org.cyclops.integrateddynamics.part.PartTypeConnectorOmniDirectional@2d4a6b57 onCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 8: ASM: com.kashdeya.tinyprogressions.main.TinyProgressions@2b8ad0d9 itemCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 9: ASM: mekanism.common.recipe.BinRecipe@271935a6 onCrafting(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 10: ASM: de.ellpeck.actuallyadditions.mod.event.CommonEvents@6296a12b onCraftedEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 11: ASM: slimeknights.tconstruct.shared.AchievementEvents@36eeafe onCraft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 12: ASM: li.cil.oc.common.EventHandler$@56019d03 onCrafting(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 13: ASM: reborncore.shields.RebornCoreShields@3a8ea36b craft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 14: ASM: tonius.simplyjetpacks.crafting.PlatingReturnHandler@283bca55 onItemCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 15: ASM: vswe.stevescarts.handlers.EventHandler@6efe1f91 onCrafting(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[18:58:46] [Server thread/ERROR] [FML]: 16: ASM: com.rwtema.extrautils2.items.ItemUnstableIngots@5667b237 onPlayerEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent;)V
```

**Comment by KnightMiner** [comment]
Going to need more information, such as actual mod version. A crash report of it crashed, or a full game log if not. (Use pastebin for those please)

**Comment by bonii-xx** [comment]
Looks like the fake player of AE2 has problems when TiC is trying to give it some achievements. Either AE2 is missing something in its implementation, or we have an API oversight. That part is pretty new.

**Comment by TheQuadShot** [comment]
Just a heads up, AE2 has changed it's API, so it's not really compatible anymore. I saw something like/related to this on GC's db. https://github.com/micdoodle8/Galacticraft/issues/3265

**Comment by a20eac1d** [comment]
The entire logfile is very large and exceeds Pastebin's limit:

http://pastebin.xyz/p?q=d0NyWXk

**Comment by a20eac1d** [comment]
The issue happens with many items from many different mods. Right now, it's basically impossible to have both AE2 and TCon running at the same time.

Any advice on how to fix?

Maybe add a config option to disable TCon advance/achievements?

**Comment by bonii-xx** [comment]
Have you reported it to the AE2 team?

**Comment by Bibz87** [comment]
Someone commented [here](https://github.com/DarkPacks/SevTech-Ages/issues/3161#issuecomment-407014712) that TiC tries to give an advancement to AE's player, which seems to be causing problems.

I've got the exact same bug in my game. :(

**Comment by Rodg88** [comment]
I've now had this in both FTB Continuum and Modern Skyblock 3. Latest time was in Modern Skyblock 3, with Tinkers 2.10.1.87 and AE2 rv5 stable11

**Comment by GoneTesting** [comment]
For anyone suffering with this, a workaround is to instead create a processing pattern - e.g. 4 planks = 1 crafting table - and set it up through a different autocrafter such as those from ender IO (Crafter Tier 1/2/3). 
It seems to be able to use the tables fine once they are crafted so this fixed all future recipes from them for me as well

**Comment by bonii-xx** [comment]
9a7235813de0de79e9eaf73af09fd943c0c228c1 contains some extra checks that will probably also prevent this.
