### ISSUE TITLE
Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by Sakata-MC** [SlimeKnights/TinkersConstruct#3548]
Possibly related info:
Pack - All the Mods 3-v5.9.7b:
Forge:  14.23.4.2707 
TiCo:  1.12.2-2.10.1.87
PlusTiC:  6.5.2.0

Likely related to:
https://github.com/BluSunrize/ImmersiveEngineering/issues/2756

Not sure if this is TiCo, PlusTiC, or Draconic Evolution issue. Please let me know if this is not TiCo, I will report in correct location.

I created some armor and tools, placed them in Draconic Evolution chest, and a PlusTiC gun, placed gun in Drconic Evolution chest, and immediately crashed with error:

[04:50:17] [Netty Client IO #3/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by KnightMiner** [comment]
I have never seen this issue with normal TiC tools, we have a reasonable amount of NBT on the tools. Reproduce this using a "vanilla" Tinkers tool (meaning *not* a PlusTiC gun) and it might be worth looking into. Right now it sounds like you are reporting the issue to the least involved mod.

**Comment by KnightMiner** [comment]
Closing for lack of response and since this seems to be a PlusTiC issue.
