### ISSUE TITLE
Cannot create a fluidstack from a null fluid

### ISSUE THREAD

**Issue by sanchezxd** [SlimeKnights/TinkersConstruct#3612]
My game crashed when placed a fluiduct from Thermal Expansion to a Tinker's Construct Smeltery drain, after that crash i can't join the world.
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 12.08.18 20:16
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at cofh.thermaldynamics.ducts.fluid.TileFluidDuct.<init>(TileFluidDuct.java:42)
	at cofh.thermaldynamics.ducts.fluid.TileFluidDuctFragile.<init>(TileFluidDuctFragile.java:39)
	at cofh.thermaldynamics.ducts.DuctFactory$8.createTileEntity(DuctFactory.java:85)
	at cofh.thermaldynamics.block.BlockDuct.func_149915_a(BlockDuct.java:92)
	at cofh.core.block.BlockCoFHBase.createTileEntity(BlockCoFHBase.java:64)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at cofh.thermaldynamics.block.BlockMultiBlock.func_149731_a(BlockMultiBlock.java:103)
	at net.minecraft.world.World.func_147447_a(World.java:1221)
	at net.minecraft.world.World.func_72901_a(World.java:1029)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:92)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:55)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:70)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_273_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by JacobFrodermann** [comment]
I've the same problem but it just happends when i look in te smeltery when something is nearly molten
