### ISSUE TITLE
Leaking resources during model generation?

### ISSUE THREAD

**Issue by 3TUSK** [SlimeKnights/TinkersConstruct#3810]
**Issue description:**
Large log spam comes out from vanilla `FallbackResourceManager`, claiming that TiCon is causing resources leaking out. No game contents seem to be affected in any manner.

**If crashed, link to crash report (use a site such as pastebin):**
N/A, game is not crashing. However, for sake of completeness, here is the game log directly copied from MultiMC console: https://paste.ubuntu.com/p/KWpT4Fpngc/ (caution: very long!)  
Sample exception & stacktrace excerpt:
<details>
<summary>
<code>Leaked resource: 'tconstruct:textures/items/cast_large_plate.png' loaded from pack: 'FMLFileResourcePack:Tinkers' Construct'</code>
</summary>

```
[23:54:28] [Finalizer/WARN] [minecraft/FallbackResourceManager]: Leaked resource: 'tconstruct:textures/items/cast_large_plate.png' loaded from pack: 'FMLFileResourcePack:Tinkers' Construct'
java.lang.Exception
	at net.minecraft.client.resources.FallbackResourceManager$InputStreamLeakedResourceLogger.<init>(FallbackResourceManager.java:128)
	at net.minecraft.client.resources.FallbackResourceManager.func_177245_a(FallbackResourceManager.java:76)
	at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:98)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:79)
	at slimeknights.tconstruct.library.client.CustomTextureCreator.exists(CustomTextureCreator.java:250)
	at slimeknights.tconstruct.library.client.CustomTextureCreator.createPatternTexturesFor(CustomTextureCreator.java:217)
	at slimeknights.tconstruct.library.client.CustomTextureCreator.createPatterntextures(CustomTextureCreator.java:193)
	at slimeknights.tconstruct.library.client.CustomTextureCreator.createCustomTextures(CustomTextureCreator.java:100)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_61_CustomTextureCreator_createCustomTextures_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:211)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
</details>

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2808
* Mantle: 1.12-1.3.3.49
* Tinkers Construct: 1.12.2-2.12.0.135

Remark: this has also been verified on slightly older versions of Mantel+TiCon, but for sake of correctness, I only listed the most recent (as of I am writing this sentence) Mantel + TiCon releases here.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes. The log does indicate that I also have JEI installed in addition to Mantle + TiCon, but I assert that JEI is irrelevant to this issue. 
I have `-Dforge.logging.mojang.level=ALL` in my JVM arguments if that matters.

**Comment by bonii-xx** [comment]
That's from an old workaround to check if a texture exists. It doesn't cause any leakage from what I see, since it will be loaded normally anyway if it exists, but custom logic requires to know whether it exists. The custom logic does not actually use the resource.

**Comment by liach** [comment]
but you do open an input stream (iresource) and leave it. just move the getallresources call to the parentheses in the try and declare a useless local variable

**Comment by bonii-xx** [comment]
Indeed, you are correct, however that's not what the log is about. That part of the code just is an old copy&paste from another project. Might also be the underlying code completely changed after 1.8.
