### ISSUE TITLE
Player got "Internal Server Error" when attacking themselves with shuriken

### ISSUE THREAD

**Issue by HerobrineXia** [SlimeKnights/TinkersConstruct#3827]
**Issue description:**
Player got "Internal Server Error" when attacking themselves with shuriken. (In my personal server) They are wearing Manyullyn armor from the mod cornarm, which had the attribute revenge. It might be caused by the revenge attribute. I wonder if there is any solution other than deleting player data.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-forge1.12.2-14.23.5.2768
* Mantle: Mantle-1.12-1.3.3.42
* Tinkers Construct: TConstruct-1.12.2-2.12.0.115

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
conarm-1.12.2-1.2.3

**Comment by ToeiRei** [comment]
Maybe related: Attacking mobs with Tinkers' tools crashed the server.

**Comment by ToeiRei** [comment]
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.entity.Entity.func_184191_r(Entity.java:2315)
        at net.minecraft.entity.ai.EntityAIHurtByTarget.func_190105_f(SourceFile:57)
        at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:38)
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
        at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
        at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
        at net.minecraft.world.World.func_72866_a(World.java:1993)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
        at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
        Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
        Entity ID: 3889
        Entity Name: Zombie
        Entity's Exact location: -1301.11, 13.06, 1167.70
        Entity's Block location: World: (-1302,13,1167), Chunk: (at 10,0,15 in -82,72; contains blocks -1312,0,1152 to -1297,255,1167), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535)
        Entity's Momentum: -0.10, -0.09, 0.00
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1759)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
        Level name: world
        All players: 1 total; [EntityPlayerMP['ToeiRei'/3618, l='world', x=-1298.75, y=13.00, z=1163.89]]
        Chunk stats: ServerChunkCache: 715 Drop: 0
        Level seed: -6132425295594766855
        Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: true
        Level generator options:
        Level spawn location: World: (120,64,244), Chunk: (at 8,4,4 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 11462070 game time, 13295045 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 86764 (now: false), thunder time: 32942 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by bonii-xx** [comment]
Effects that return damage are quite prone to crashing things due to how attacking works in Minecraft. TiC has no relation to whatever the armor mod does. The crash doesn't show any relation to TiC, but in vanilla. Most likely a coremods fault.
