### ISSUE TITLE
crash when loading a world or joining a server

### ISSUE THREAD

**Issue by ZephyrDasher** [SlimeKnights/TinkersConstruct#4160]
the game have no loading problem but when i load a world or i joining a server my game crash

https://pastebin.com/szzn2Kaf

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2 14.23.5.2845
* Mantle: 1.12.2 1.3.3.55
* Tinkers Construct: 1.12.2 2.13.0.171

Modpack : https://www.curseforge.com/minecraft/modpacks/lapitos-galacticraft/files 
 version:2.2.8

**Comment by ShadowBoxx-LLC** [comment]
This doesn't look like an issue with TiC, this looks like an issue with Bibliocraft:
```
[16:56:19] [Netty Client IO #1/INFO] [FML]: [Netty Client IO #1] Client side modded connection established
[16:56:25] [Thread-9/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §2CustomNpcs§f installed. For more info §9§nClick here
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.bibliocraftmod.com/vcheck/version.txt
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.net.URL.openStream(Unknown Source)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck.getNetVersion(VersionCheck.java:58)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck$1.run(VersionCheck.java:46)
[16:56:32] [Thread-29/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by KnightMiner** [comment]
Yeah, I see nothing in that crash report that would bring you here. Go to bibliocraft's repo as the error is in their code, unless you uploaded the wrong log
