### ISSUE TITLE
NoSuchMethodException TinkerOredict.doTheOredict FMLInitializationEvent

### ISSUE THREAD

**Issue by Macleykun** [SlimeKnights/TinkersConstruct#4422]
**Issue description:**
I noticed when looking trough the logs, that there's an error thrown when JAOPCA and TConstruct is used.

My question is if this can be resolved from TConstruct or if this issue has to be resolved by JAOPCA. If it can be resolved by TConstruct, i would like to ask if it's possible to implement a fix for this.

**If crashed, link to crash report (use a site such as pastebin):**
As the error is short, i'll post it in the issue itself.
```
java.lang.NoSuchMethodException: slimeknights.tconstruct.common.TinkerOredict.doTheOredict(net.minecraftforge.fml.common.event.FMLInitializationEvent)
        at java.lang.Class.newNoSuchMethodException(Class.java:567)
        at java.lang.Class.throwExceptionOrReturnNull(Class.java:1222)
        at java.lang.Class.getMethodHelper(Class.java:1308)
        at java.lang.Class.getDeclaredMethod(Class.java:936)
        at thelm.oredictinit.compat.CompatTinkersConstruct.register(CompatTinkersConstruct.java:19)
        at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
        at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_859_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_547_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
        at java.lang.Thread.run(Thread.java:823)
```

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
The mods that are required:
JAOPCA-1.12.2-2.2.8.104.jar
Mantle-1.12-1.3.3.55.jar
TConstruct-1.12.2-2.13.0.183.jar
WrapUp-1.12-1.1.3.jar

**Comment by KnightMiner** [comment]
JAOPCA is calling one of our internal methods. Its not in our API, so any errors with calling it are on them.

**Comment by Macleykun** [comment]
Thanks for the quick reply! Will pass this on!

**Comment by KnightMiner** [comment]
For the record, we changed this in 2018. So odds are you have an old build. If not this mod has been broken for 3 years.

Also, this mod has no reason to call our method in the first place. That is dumb mod compat.

**Comment by Macleykun** [comment]
I'm afraid it's the latter :P 
https://github.com/TheLMiffy1111/JAOPCA/issues/102

Thanks again for the clear and very fast explanation :)
