### ISSUE TITLE
crash on smeltery break

### ISSUE THREAD

**Issue by maverag** [SlimeKnights/TinkersConstruct#4541]
**Issue description:**
crash on breaking smeltery ladder to fully destroy a smeltery not just shrink size

**If crashed, link to crash report (use a site such as pastebin):**
14:05:48.461
net.minecraft.util.concurrent.ThreadTaskExecutor
Server thread
Error executing task on Server
java.lang.NullPointerException
	at net.minecraftforge.common.util.LazyOptional.lambda$invalidate$1(LazyOptional.java:335)
	at net.minecraftforge.common.util.LazyOptional$$Lambda$23235/1988412364.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraftforge.common.util.LazyOptional.invalidate(LazyOptional.java:335)
	at slimeknights.tconstruct.smeltery.tileentity.MelterTileEntity.invalidateCaps(MelterTileEntity.java:112)
	at net.minecraft.tileentity.TileEntity.func_145843_s(TileEntity.java:143)
	at net.minecraft.world.chunk.Chunk.func_177425_e(Chunk.java:449)
	at net.minecraft.world.World.func_175713_t(World.java:662)
	at net.minecraft.block.AbstractBlock.func_196243_a(AbstractBlock.java:136)
	at slimeknights.mantle.block.InventoryBlock.func_196243_a(InventoryBlock.java:131)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196947_b(AbstractBlock.java:616)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:267)
	at net.minecraft.world.World.func_241211_a_(World.java:199)
	at net.minecraft.world.World.func_180501_a(World.java:176)
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:200)
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157)
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:254)
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220)
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$21937/1224358368.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$20440/1002772234.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
**Versions:**
* Minecraft:1.16.5
* Forge: 36.1.32
* Mantle: 1.6.109
* Tinkers Construct: 3.0.4.179

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
?
**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
?
Should be fewer than 10 mods, you should be running no mods besides those 10 when you reproduce the issue.

**Comment by KnightMiner** [comment]
`?` is not a valid answer, and you ignored the instructions on how to add your crash report. Actually follow the instructions so we have a full crash report.

**Comment by KnightMiner** [comment]
Closing for lack of response. Looking at the code this issue should be impossible unless someone adds an invalid capability listener
