### ISSUE TITLE
my client crashes whenever i disconect from my server

### ISSUE THREAD

**Issue by kuba26038** [SlimeKnights/TinkersConstruct#4656]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

Mantle-1.16.5-1.6.127

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.3.271

### Describe your issue

my client crashes whenever i leave my server

### Crash Report

https://justpaste.it/8vgb1

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Does the server have the same version of the mod as the client?

> Reproduced with only Tinkers' Construct?
> Yes

If this is true, include a crash report with only Tinkers' Construct

**Comment by kuba26038** [comment]
here you go chief 
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11/12/21 8:22 AM
Description: mouseClicked event handler

java.lang.NullPointerException: Registry Object not present: tconstruct:molten_enderium
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:39) ~[forge:?] {re:classloading}
	at slimeknights.mantle.registration.DelayedSupplier.get(DelayedSupplier.java:23) ~[mantle:1.16.5-1.6.127] {re:classloading}
	at net.minecraft.block.FlowingFluidBlock.getFluid(FlowingFluidBlock.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:flowingfluidblock}
	at net.minecraft.block.FlowingFluidBlock.func_220071_b(FlowingFluidBlock.java:65) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:flowingfluidblock}
	at net.minecraft.block.AbstractBlock$AbstractBlockState$Cache.<init>(AbstractBlock.java:765) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState$Cache.<init>(AbstractBlock.java:736) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215692_c(AbstractBlock.java:397) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:519) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:525) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.GameData.lambda$revertTo$7(GameData.java:332) ~[forge:?] {re:classloading}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528) ~[guava-21.0.jar:?] {}
	at net.minecraftforge.registries.GameData.revertTo(GameData.java:332) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.GameData.revertToFrozen(GameData.java:314) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientHooks.handleClientWorldClosing(ClientHooks.java:208) ~[forge:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_213231_b(Minecraft.java:1926) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_213254_o(Minecraft.java:1893) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.IngameMenuScreen.func_213067_a(SourceFile:77) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.8.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) [proxyserver.jar:2.12.3] {}
	at crystallauncher.MineClient.start(MineClient.java:188) [proxyserver.jar:2.12.3] {}
	at crystallauncher.MineClient.main(MineClient.java:33) [proxyserver.jar:2.12.3] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:39) ~[forge:?] {re:classloading}
	at slimeknights.mantle.registration.DelayedSupplier.get(DelayedSupplier.java:23) ~[mantle:1.16.5-1.6.127] {re:classloading}
	at net.minecraft.block.FlowingFluidBlock.getFluid(FlowingFluidBlock.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:flowingfluidblock}
	at net.minecraft.block.FlowingFluidBlock.func_220071_b(FlowingFluidBlock.java:65) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:flowingfluidblock}
	at net.minecraft.block.AbstractBlock$AbstractBlockState$Cache.<init>(AbstractBlock.java:765) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState$Cache.<init>(AbstractBlock.java:736) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215692_c(AbstractBlock.java:397) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:519) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:525) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.GameData.lambda$revertTo$7(GameData.java:332) ~[forge:?] {re:classloading}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528) ~[guava-21.0.jar:?] {}
	at net.minecraftforge.registries.GameData.revertTo(GameData.java:332) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.GameData.revertToFrozen(GameData.java:314) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientHooks.handleClientWorldClosing(ClientHooks.java:208) ~[forge:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_213231_b(Minecraft.java:1926) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_213254_o(Minecraft.java:1893) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.IngameMenuScreen.func_213067_a(SourceFile:77) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.IngameMenuScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:classloading}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['kuba26038'/138, l='ClientLevel', x=194.57, y=65.00, z=53.87]]
	Chunk stats: Client Chunk Cache: 529, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,64,32), Chunk: (at 0,4,0 in 12,2; contains blocks 192,0,32 to 207,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25200 game time, 34999 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.8.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) [proxyserver.jar:2.12.3] {}
	at crystallauncher.MineClient.start(MineClient.java:188) [proxyserver.jar:2.12.3] {}
	at crystallauncher.MineClient.main(MineClient.java:33) [proxyserver.jar:2.12.3] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3016222296 bytes (2876 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -Xms4096M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.8.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.8
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.8-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.2.0.290.jar                   |Tinkers' Construct            |tconstruct                    |3.2.0.290           |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.8-universal.jar                 |Forge                         |forge                         |36.2.8              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Mantle-1.16.5-1.6.127.jar                         |Mantle                        |mantle                        |1.6.127             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: ae4fb93a-27dc-49a7-8aa6-42da0e990426
	Launched Version: 1.16.5-forge-36.2.8
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/PackSMP.zip, file/Tetra Caves Cliffs Backport Compat Resources, file/Tetra Darker Depths Compat Resources, file/Tetra End Remastered Compat Resources, file/Tetra Omnis Compat Resources, file/Soft-Weather-1.0-1.16.zip, file/VanillaTweaks_r896887.zip, file/Better+Maps+1.16.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor

**Comment by KnightMiner** [comment]
You did not answer my first question. Also use paste bin or something similar for all crash reports

**Comment by KnightMiner** [comment]
For the record, I have tested this myself and I had no issues, I can join and leave servers with no issues. The mod is also being used in SkyFactory with no reported issues of problems joining and leaving servers. Something is wrong in your setup.

Unless you answer confirming otherwise, I am going to assume you have different versions of the mod on client and server and close this. For a reopen, answer my questions and confirm you have the same mod list down to versions on both sides.
