### ISSUE TITLE
1.18.2 in wrong

### ISSUE THREAD

**Issue by jingerbreadBiliBili** [SlimeKnights/TinkersConstruct#4974]
### Minecraft Version

1.18.2

### Forge Version

40.1.63

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

when i send anything to block in Tinker`s mod it might be gone
Game was in Catserver

### Other mods

Jei journeymap

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
I have absolutely no idea what you are saying. What did you do? What is the bug here?

Please describe your issue in detail, the more detail the better. Explain
* What are you trying to do
* What happened when you did it
* What you expected to happen

**Comment by Insane96** [comment]
CatServer is a forge+spigot+bukkit+whatever server
https://github.com/Luohuayu/CatServer/blob/1.12.2/docs/README_EN.md

**Comment by jingerbreadBiliBili** [comment]
> 

i want to put wood into the desk,then the wood gone

**Comment by KnightMiner** [comment]
Since you ignored my earlier comment, I will save effort by just writing it again. 

> I have absolutely no idea what you are saying. What did you do? What is the bug here?
>
> Please describe your issue in detail, the more detail the better. Explain
>
> * What are you trying to do
> * What happened when you did it
> * What you expected to happen

One additional sentence is not explaining in detail. Explain **in detail**.

**Comment by jingerbreadBiliBili** [comment]
I'll tell you everything
My friend and I played online with catserver. I placed my pickaxe on the assembly platform. After clicking the copper pickaxe in the backpack, the pickaxe on the assembly platform disappeared
translate by baidu

**Comment by jingerbreadBiliBili** [comment]
here is log
[00:21:44] [Server thread/ERROR] [net.minecraft.server.level.ChunkMap]: Failed to save chunk [9, -5]
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class slimeknights.tconstruct.tables.block.entity.table.TinkerStationBlockEntity does not define or inherit an implementation of the resolved method 'abstract java.util.List getViewers()' of interface net.minecraft.world.Container.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:477) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:448) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:362) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:645) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:656) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:801) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:242) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class slimeknights.tconstruct.tables.block.entity.table.TinkerStationBlockEntity does not define or inherit an implementation of the resolved method 'abstract java.util.List getViewers()' of interface net.minecraft.world.Container.
	at net.minecraft.server.level.ServerLevel.m_8712_(ServerLevel.java:905) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.level.ChunkMap.m_202998_(ChunkMap.java:507) ~[server-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 9 more

**Comment by KnightMiner** [comment]
It sound to me like catserver is the problem here, please attempt to reproduce in single player, and if the bug does not happen try to reproduce on a regular forge server. There is not much I can do to reproduce a bug that only happens on a third party server nor to fix it.

**Comment by jingerbreadBiliBili** [comment]
here is log
 [10:46:01] [Server thread/ERROR]: Error executing task on Server
net.minecraft.ReportedException: Container click
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:377) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at slimeknights.mantle.inventory.MultiModuleContainerMenu.m_150399_(MultiModuleContainerMenu.java:119) ~[Mantle-1.18.2-1.9.27.jar%2354!/:1.18.2-1.9.27]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1698) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:24) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:898) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:123) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:881) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:875) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:861) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:242) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.InventoryView.convertSlot(int)" because "what" is null
        at org.bukkit.event.inventory.InventoryDragEvent.<init>(InventoryDragEvent.java:77) ~[forge-1.18.2-40.1.63-universal.jar%2363!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:446) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:363) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
        ... 18 more

**Comment by jingerbreadBiliBili** [comment]
perhaps it`s really in catserver
