### ISSUE TITLE
Smeltery error

### ISSUE THREAD

**Issue by vaniron** [SlimeKnights/TinkersConstruct#5205]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

Hi, seeing a lot of errors when using smeltery:
```
[net.minecraft.tileentity.TileEntity/]: Failed to load data for block entity tconstruct:smeltery
java.lang.NullPointerException: Cannot read field "field_72995_K" because "this.field_145850_b" is null
	at slimeknights.tconstruct.smeltery.tileentity.controller.HeatingStructureTileEntity.dropItem(HeatingStructureTileEntity.java:215) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.module.MeltingModuleInventory.resize(MeltingModuleInventory.java:159) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.controller.SmelteryTileEntity.setStructure(SmelteryTileEntity.java:120) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.controller.HeatingStructureTileEntity.func_230337_a_(HeatingStructureTileEntity.java:508) ~[tconstruct:1.16.5-3.3.4.335]
	at net.minecraft.tileentity.TileEntity.func_235656_a_(TileEntityMixin.java:88) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.tileentity.TileEntity.func_235657_b_(TileEntityMixin.java:86) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:51) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:30) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.Material.mdfeaa0c$lambda$setupBlockStateFunc$21$4(MaterialMixin.java:9133) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.handler$bgp000$arclight$getState(CraftBlockMixin.java:817) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getState(CraftBlockMixin.java) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at io.izzel.arclight.common.mod.server.api.DefaultTickingTracker.getTickingBlockEntity(DefaultTickingTracker.java:66) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at io.izzel.arclight.common.mod.server.api.DefaultTickingTracker.getTickingSource(DefaultTickingTracker.java:26) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at com.griefdefender.provider.ArclightProvider.getTickingSource(ArclightProvider.java:45) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.handleEntitySpawn(EntityEventHandler.java:857) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onItemSpawn(EntityEventHandler.java:754) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactoryMixin.java:679) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactoryMixin.java:587) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at net.minecraft.world.server.ServerWorld.handler$bge000$arclight$addEntityEvent(ServerWorldMixin.java:1803) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorldMixin.java:814) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorldMixin.java:755) ~[?:?]
	at slimeknights.tconstruct.smeltery.tileentity.controller.HeatingStructureTileEntity.dropItem(HeatingStructureTileEntity.java:222) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.module.MeltingModuleInventory.resize(MeltingModuleInventory.java:159) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.controller.SmelteryTileEntity.setStructure(SmelteryTileEntity.java:120) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.controller.HeatingStructureTileEntity.checkStructure(HeatingStructureTileEntity.java:291) ~[tconstruct:1.16.5-3.3.4.335]
	at slimeknights.tconstruct.smeltery.tileentity.controller.HeatingStructureTileEntity.func_73660_a(HeatingStructureTileEntity.java:166) ~[tconstruct:1.16.5-3.3.4.335]
	at net.minecraft.world.World.func_217391_K(WorldMixin.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:372) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

### Other mods

none

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
You're using a hybrid server which tend to cause issues with mods, craftbukkit in this case. If you tried with just tinkers we need that log.

**Comment by KnightMiner** [comment]
Yeah, I am just going to close this issue, the world on a block entity should never be null, if Bukkit is changing that then Bukkit is dumb. Don't use Bukkit
